SonarSource/rspec

rules/S1265/cfamily/rule.adoc

Modify rule S1265: LaYC format

---

rules/S3034/java/rule.adoc

Modify rule S3034: LaYC format

---

rules/S3012/java/rule.adoc

Modify rule S3012: fix code diff view

---

rules/S2274/java/rule.adoc

Modify rule S2274: Update in line with LayC (SONARJAVA-4495)

---

rules/S2273/java/metadata.json
rules/S2273/java/rule.adoc

Modify rule S2273: LaYC format

---

rules/S1171/java/rule.adoc
rules/S1452/java/rule.adoc
rules/S1598/java/rule.adoc
rules/S1948/java/rule.adoc
rules/S2122/java/rule.adoc
rules/S2157/java/rule.adoc
rules/S2160/java/rule.adoc
rules/S2254/java/rule.adoc
rules/S2975/java/rule.adoc

Diff blocks: fix some incorrect use for java

---

rules/S1523/metadata.json
rules/S2077/metadata.json
rules/S5782/cfamily/metadata.json

This PR adds multiple impacts for a few rules to test CCT features.

Add multiple impacts for CCT

---

rules/S6466/java/metadata.json
rules/S6466/java/rule.adoc

Modify rule S6466: Fix typos

---

rules/S1488/javascript/rule.adoc

Fixes https://github.com/SonarSource/eslint-plugin-sonarjs/issues/413

Modify rule S1488: add code example when returning awaited promise

---

rspec-tools/Pipfile.lock
rules/S5144/common/fix/how-does-this-work.adoc
rules/S5144/common/fix/pre-approved-list.adoc
rules/S5144/csharp/how-to-fix-it/dotnet.adoc
rules/S5144/java/how-to-fix-it/java-se.adoc
rules/S5144/javascript/how-to-fix-it/node.adoc
rules/S5144/php/how-to-fix-it/core.adoc
rules/S5144/php/how-to-fix-it/guzzle.adoc
rules/S5144/python/how-to-fix-it/python.adoc
rules/S5144/python/how-to-fix-it/requests.adoc
rules/S6547/common/fix/how-does-this-work.adoc
rules/S6547/common/fix/pre-approved-list.adoc
rules/S6547/csharp/how-to-fix-it/dotnet.adoc
rules/S6547/java/how-to-fix-it/java-se.adoc
rules/S6680/csharp/rule.adoc

Modify S5144&S6547: Improve fixes

---

rules/S6661/javascript/metadata.json

Modify rule S6661: Quote the method's name in the title

---

rules/S5273/cfamily/metadata.json
rules/S5273/cfamily/rule.adoc

**Caution:** our analyzer currently does not correctly detect the issue in the first code example in section `Why is this an issue?`.

Modify rule S5273: Expand and adjust for LaYC

---

rules/S5280/cfamily/metadata.json

Modify rule S5280: Update quickfix status

---

rules/S6320/java/metadata.json
rules/S6322/java/metadata.json
rules/S6464/python/metadata.json
rules/S6465/python/metadata.json
rules/S6466/java/metadata.json
rules/S6466/python/metadata.json

Adjust clean code attributes for DBD rules

---

rules/S6688/secrets/rule.adoc
rules/S6695/secrets/rule.adoc
rules/S6701/secrets/rule.adoc
rules/S6708/secrets/rule.adoc
shared_content/secrets/impact/malware_distribution.adoc
shared_content/secrets/impact/personal_data_compromise.adoc
shared_content/secrets/impact/phishing.adoc

Create Shared content: Make impacts consistents across messenger secrets

---

rules/S6497/docker/metadata.json

Related ticket: [**SONARIAC-1075**](https://sonarsource.atlassian.net/browse/SONARIAC-1075).

Modify S6497(docker): Remove from SonarWay

---

rules/S117/php/rule.adoc

Modify rule S117: Update regular expression for PHP

---

rules/S2566/plsql/rule.adoc

Modify rule S2566: Fix code example

---

rules/S4144/php/rule.adoc

Modify rule S4144: Add more exceptions for PHP

---

rules/S5785/php/rule.adoc

Modify rule S5785: add examples with boolean literals

---

rules/S5689/ask-yourself.adoc
rules/S5689/description.adoc
rules/S5689/java/rule.adoc
rules/S5689/javascript/rule.adoc
rules/S5689/message.adoc
rules/S5689/recommended.adoc

For review, have a look to our docs: https://docs.sonarsource.com/sonarqube/9.8/extension-guide/adding-coding-rules/#coding-rule-guidelines
This should not be merged by an AppSec member, because it contains message information. It should be merged by someone from SonarJS.

Modify S5689: Clarify the rule stakes

---

rules/S3590/cfamily/metadata.json
rules/S3590/cfamily/rule.adoc

Modify rule S3590: LaYC format 

---

rules/S6437/docker/rule.adoc

This PR aims to make the sample testable. It has been erroneously merged before the completion of [this sonariac ticket](https://sonarsource.atlassian.net/browse/SONARIAC-583). The Wget part is going to be stored in another PR while we wait for the implementation.

Modify S6437(docker): Improve the samples

---

docs/header_names/allowed_framework_names.adoc
rules/S5876/common/fix/new-session.adoc
rules/S5876/common/resources/standards.adoc
rules/S5876/description.adoc
rules/S5876/impact.adoc
rules/S5876/java/how-to-fix-it/spring.adoc
rules/S5876/java/rule.adoc
rules/S5876/javascript/how-to-fix-it/passportjs.adoc
rules/S5876/javascript/rule.adoc
rules/S5876/php/how-to-fix-it/symfony.adoc
rules/S5876/php/rule.adoc
rules/S5876/rationale.adoc
rules/S5876/summary.adoc

Modify rule S5876: Update to LayC format (APPSEC-969) 

---

docs/header_names/allowed_framework_names.adoc
rules/S6301/common/extra-mile/avoid-local-data.adoc
rules/S6301/common/fix/android-apis.adoc
rules/S6301/common/fix/dynamic-retrieval.adoc
rules/S6301/common/resources/docs.adoc
rules/S6301/common/resources/standards.adoc
rules/S6301/description.adoc
rules/S6301/impact.adoc
rules/S6301/java/how-to-fix-it/realm.adoc
rules/S6301/java/how-to-fix-it/sqlcipher.adoc
rules/S6301/java/rule.adoc
rules/S6301/kotlin/how-to-fix-it/realm.adoc
rules/S6301/kotlin/how-to-fix-it/sqlcipher.adoc
rules/S6301/kotlin/rule.adoc
rules/S6301/rationale.adoc
rules/S6301/summary.adoc

Modify rule S6301: update to LaYC format (APPSEC-973)

---

rules/S5335/php/metadata.json

Modify S5335(php): Title update

---

rules/S6723/secrets/rule.adoc

Modify S6723(secrets): Fix docs links

---

rules/S6173/java/how-to-fix-it/java-se.adoc

Modify S6173(Java): Improve samples

---

rules/S6321/terraform/rule.adoc
rules/S6388/azureresourcemanager/examples/Microsoft.Compute_disks.compliant.adoc
rules/S6388/azureresourcemanager/examples/Microsoft.Compute_disks.noncompliant.adoc
rules/S6388/azureresourcemanager/examples/Microsoft.Compute_snapshots.compliant.adoc
rules/S6388/azureresourcemanager/examples/Microsoft.Compute_virtualMachineScaleSets.compliant.adoc
rules/S6388/azureresourcemanager/examples/Microsoft.Compute_virtualMachines.compliant.adoc
rules/S6506/docker/rule.adoc

https://cirrus-ci.com/task/4983664824549376?logs=asciidoc_tests#L117
https://github.com/SonarSource/rspec/blob/master/rules/S6388/azureresourcemanager/examples/Microsoft.Compute_disks.noncompliant.adoc is empty for no reason

Modify S6388(IAC): Fix diff IDs

---

rules/S1764/cfamily/rule.adoc

Modify rule S1764: update to LaYC and sync with implementation

---

rules/S6292/secrets/rule.adoc

APPSEC-1061 Modify S6292(secrets): Make text compliant

---

rules/S6379/azureresourcemanager/rule.adoc

APPSEC-1015 Validate S6379(secrets): ARM

---

rules/S6378/description.adoc
rules/S6378/terraform/rule.adoc

APPSEC-1050 Modify S6378(ARM): Fix typo and adjust code examples

---

rules/S6336/secrets/rule.adoc

APPSEC-1056 Modify S6336(secrets): Make text compliant

---

rules/S1599/php/rule.adoc

Modify rule S1599: remove extra diff-view

---

rules/S2004/php/rule.adoc

Modify rule S2004: remove extra diff-view

---

rules/S6364/azureresourcemanager/rule.adoc

[Specification ticket](https://sonarsource.atlassian.net/browse/SONARIAC-768)
[Implementation ticket](https://sonarsource.atlassian.net/browse/SONARIAC-810)
[RSPEC Preview](https://sonarsource.github.io/rspec/#/rspec/S6364/azureresourcemanager)
ARM template PR for S6364: #1912

Modify rule S6364: Add language AzureResourceManager (Bicep)

---

docs/header_names/allowed_framework_names.adoc
rules/S6656/azureresourcemanager/how-to-fix-it/bicep.adoc
rules/S6656/azureresourcemanager/rule.adoc

Specification ticket: [APPSEC-805](https://sonarsource.atlassian.net/browse/APPSEC-805)
Implementation ticket: [SONARIAC-930](https://sonarsource.atlassian.net/browse/SONARIAC-930)
[RSPEC Preview](https://sonarsource.github.io/rspec/#/rspec/S6656/azureresourcemanager)
JSON PR for S6656: #2322 
[APPSEC-805]: https://sonarsource.atlassian.net/browse/APPSEC-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARIAC-930]: https://sonarsource.atlassian.net/browse/SONARIAC-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify rule S6656: add language AzureResourceManager (Bicep)

---

rules/S6381/ask-yourself.adoc
rules/S6381/azureresourcemanager/rule.adoc

APPSEC-1082 Validate S6381 ARM

---

rules/S2251/java/rule.adoc

Modify rule S2251: fix diff-id

---

rules/S127/java/rule.adoc

Modify rule S127: fix diff-id and diff-type

---

rules/S4423/azureresourcemanager/how-to-fix-it/azure-storage-account.adoc
rules/S6378/azureresourcemanager/rule.adoc
rules/S6387/azureresourcemanager/rule.adoc
rules/S6656/azureresourcemanager/how-to-fix-it/arm.adoc
rules/S6656/azureresourcemanager/how-to-fix-it/bicep.adoc

Modify rule S4423, S6378, S6387, S6656: Fix diff view errors in ARM examples

---

rules/S6382/azureresourcemanager/rule.adoc

APPSEC-1083: S6382 Fixed incorrect ARM examples

---

rules/S6338/secrets/rule.adoc

Modify S6338: Improve samples

---

ci/asciidoc_validation/validate.sh
ci_tests/asciidoc_validation/run_tests.sh

Turn on what was done in #2790.

RULEAPI-788 Turn diff-view validation on

---

rules/S6290/secrets/rule.adoc
shared_content/secrets/impact/malware_distribution.adoc

Modify S6290(secrets): Validation

---

rules/S6334/secrets/rule.adoc

Modify S6334: Make the description consistent and add sample

---

rules/S6335/secrets/rule.adoc

Modify S6335: Validation

---

rules/S6388/azureresourcemanager/examples/Microsoft.Compute_virtualMachineScaleSets.compliant.adoc
rules/S6388/azureresourcemanager/examples/Microsoft.Compute_virtualMachineScaleSets.noncompliant.adoc
rules/S6388/azureresourcemanager/examples/Microsoft.Compute_virtualMachines.noncompliant.adoc

This PR improves the examples for S6388.

APPSEC-1049: S6388 Improve code examples

---

rules/S6413/azureresourcemanager/rule.adoc
rules/S6413/recommended.adoc

APPSEC-1087: S6413 Improve RSPEC

---

rules/S6337/secrets/rule.adoc

Modify S6337: Validation

---

rules/S6385/azureresourcemanager/how_to_fix_it.adoc
rules/S6385/description.adoc

APPSEC-1088: S6385 Improve RSPEC

---

rules/S4423/azureresourcemanager/how-to-fix-it/azure-mysql.adoc

APPSEC-1090: S4423 Improved RSPEC example

---

rules/S6506/docker/rule.adoc
rules/S6584/docker/rule.adoc
rules/S6587/docker/rule.adoc

S6506, S6584, S6587 Change links to 3-rd party resources

---

rules/S6692/secrets/rule.adoc

APPSEC-1125: S6692 Adjust example to contain correct secret format

---

rules/S6584/docker/rule.adoc

Modify rule S6584: apply LaYC format

---

rules/S6697/secrets/rule.adoc
rules/S6698/secrets/rule.adoc
rules/S6703/secrets/rule.adoc
shared_content/secrets/fix/default.adoc

Modify S6698&S6703&S6697: Add a warning against default values

---

rules/S6723/secrets/rule.adoc

Modify S6723(secrets): Improve code sample

---

rules/S6710/secrets/rule.adoc

Modify S6710: Improve the sample

---

rules/S6710/secrets/rule.adoc

Modify S6710(secrets): Improve sample

---

rules/S6721/secrets/rule.adoc

Modify S6721(secrets): Add samples

---

rules/S5332/azureresourcemanager/rule.adoc

Modify rule S5332: Improve RSPEC text and examples (APPSEC-1089)

---

rules/S6570/docker/rule.adoc

Modify rule S6570: Convert to LaYC format

---

rules/S6504/docker/rule.adoc

Modify rule S6504: Update code example

---

rules/S6500/docker/rule.adoc

Modify rule S6500: Update code example

---

rules/S6505/docker/rule.adoc

Modify rule S6505: Fix FN by mentioning standalone `yarn` command

---

rules/S6597/docker/rule.adoc

Modify rule S6597: Update wording for LaYC

---

rules/S6437/docker/rule.adoc

To merge when SONARIAC-583 is complete.

SONARIAC-583 Modify S6437(docker): Add Wget samples

---

rules/S6320/java/rule.adoc

Modify rule S6320: Adapt to LaYC format

---

rules/S3518/impact.adoc
rules/S3518/introduction.adoc
rules/S3518/java/rule.adoc
rules/S3518/python/rule.adoc
shared_content/layc/exception-impact.adoc

Modify rule S3518: More LaYC Content for Python and Java

---

rules/S5301/java/rule.adoc

Modify S5301: Change text for LaYC (APPSEC-1105)

---

rules/S4684/java/rule.adoc

Modify S4684: Change text to education framework format (APPSEC-1104)

---

rules/S6373/java/common/code-rationale.adoc
rules/S6373/java/how-to-fix/dom4j.adoc
rules/S6373/java/how-to-fix/java-se.adoc
rules/S6373/java/how-to-fix/jdom2.adoc
rules/S6373/java/rule.adoc

Modify S6373: Change text to the LaYC format (APPSEC-1108)

---

rules/S2589/python/rule.adoc
rules/S2589/see.adoc

Modify rule S2589: Extend LaYC content for Python

---

rules/S5344/java/rule.adoc

Add texts that were not merged.

---

rules/S6416/java/rule.adoc

Modify rule S6416: Adapt to LaYC format

---

rules/S5786/java/rule.adoc

Modify rule S5786: Migrate to LaYC format

---

rules/S3241/rule.adoc

Modify rule S3241: Add C# snippet

---

rules/S6471/docker/rule.adoc

Modify S6471(docker): Improve fix section

---

rules/S2190/java/rule.adoc

Modify rule S2190: Extend LaYC content for Java

---

rules/S3740/java/rule.adoc

Modify rule S3740: Migrate to LaYC format

---

rules/S1120/abap/rule.adoc
rules/S1120/description.adoc
rules/S1120/extra-mile.adoc
rules/S1120/how-to-fix.adoc
rules/S1120/impact.adoc
rules/S1120/introduction.adoc
rules/S1120/java/rule.adoc
rules/S1120/rule.adoc
rules/S1120/vb6/rule.adoc
rules/S1120/why.adoc
rules/S1120/xml/rule.adoc

Modify rule S1120: Migrate to LaYC format

---

rules/S2583/python/rule.adoc

Modify rule S2583: Migrate Python description to LaYC format

---

rules/S6700/secrets/rule.adoc

Modify rule S6700: Fix broken link

---

rules/S6742/python/rule.adoc

Modify rule S6742: allow for up to 6 chained operation on pandas

---

rules/S4204/javascript/rule.adoc

Modify S4204: Migrate To LayC

---

rules/S3498/javascript/rule.adoc

Modify S3498: Migrate To LayC

---

rules/S4666/css/rule.adoc

Modify S4666: Migrate To LayC

---

rules/S134/abap/rule.adoc
rules/S134/apex/rule.adoc
rules/S134/cfamily/rule.adoc
rules/S134/cobol/rule.adoc
rules/S134/csharp/rule.adoc
rules/S134/description.adoc
rules/S134/flex/rule.adoc
rules/S134/go/rule.adoc
rules/S134/java/rule.adoc
rules/S134/javascript/rule.adoc
rules/S134/kotlin/rule.adoc
rules/S134/php/rule.adoc
rules/S134/pli/rule.adoc
rules/S134/plsql/rule.adoc
rules/S134/python/rule.adoc
rules/S134/resources.adoc
rules/S134/rpg/rule.adoc
rules/S134/ruby/rule.adoc
rules/S134/scala/rule.adoc
rules/S134/swift/rule.adoc
rules/S134/tsql/rule.adoc
rules/S134/vbnet/rule.adoc

Modify S134: Migrate to LayC - nested control flow statements shouldn't be too deep

---

rules/S2933/csharp/rule.adoc
rules/S2933/how.adoc
rules/S2933/javascript/metadata.json
rules/S2933/javascript/rule.adoc
rules/S2933/why.adoc

Modify S2933: Migrate to LayC

---

rules/S4649/css/rule.adoc

Modify S4649: Migrate to LayC

---

rules/S1481/abap/rule.adoc
rules/S1481/apex/rule.adoc
rules/S1481/cfamily/rule.adoc
rules/S1481/comments-and-links.adoc
rules/S1481/csharp/rule.adoc
rules/S1481/description.adoc
rules/S1481/flex/rule.adoc
rules/S1481/how-to-fix-it.adoc
rules/S1481/java/rule.adoc
rules/S1481/javascript/rule.adoc
rules/S1481/kotlin/rule.adoc
rules/S1481/message.adoc
rules/S1481/php/rule.adoc
rules/S1481/plsql/rule.adoc
rules/S1481/python/rule.adoc
rules/S1481/rationale.adoc
rules/S1481/ruby/rule.adoc
rules/S1481/rule.adoc
rules/S1481/scala/rule.adoc
rules/S1481/swift/rule.adoc
rules/S1481/tsql/rule.adoc
rules/S1481/vbnet/rule.adoc

Modify S1481: Migrate to LaYC

---

rules/S125/cfamily/rule.adoc
rules/S125/description.adoc

Modify S125: Migrate to LayC - commented code

---

rules/S1066/cfamily/rule.adoc
rules/S1066/flex/rule.adoc
rules/S1066/java/rule.adoc
rules/S1066/kotlin/rule.adoc
rules/S1066/scala/rule.adoc
rules/S1068/cfamily/rule.adoc
rules/S109/cfamily/rule.adoc
rules/S109/description.adoc
rules/S112/cfamily/rule.adoc
rules/S1481/cfamily/rule.adoc
rules/S1905/cfamily/rule.adoc

⚠️  To be rebased and merged, not squashed.

Fix a couple of small things in several CFamily rules

---

rules/S117/apex/rule.adoc
rules/S117/cfamily/rule.adoc
rules/S117/description.adoc
rules/S117/flex/rule.adoc
rules/S117/go/rule.adoc
rules/S117/how-to-fix-it.adoc
rules/S117/introduction.adoc
rules/S117/java/rule.adoc
rules/S117/javascript/rule.adoc
rules/S117/kotlin/rule.adoc
rules/S117/message.adoc
rules/S117/parameters.adoc
rules/S117/php/rule.adoc
rules/S117/plsql/rule.adoc
rules/S117/python/rule.adoc
rules/S117/ruby/metadata.json
rules/S117/ruby/rule.adoc
rules/S117/rule.adoc
rules/S117/scala/rule.adoc
rules/S117/swift/rule.adoc
rules/S117/tsql/rule.adoc
rules/S117/vbnet/rule.adoc
rules/S117/what-is-the-potential-impact.adoc
rules/S117/why-is-this-an-issue.adoc

Modify S117: Migrate to LaYC

---

docs/description.adoc

Modify docs: Add showcase rules

---

rules/S120/comments-and-links.adoc
rules/S120/description.adoc
rules/S120/flex/rule.adoc
rules/S120/java/rule.adoc
rules/S120/plsql/rule.adoc

Modify S120: migrate to LayC

---

rules/S5147/python/how-to-fix-it/dynamoDB.adoc

Modify S5147(python): Improved the description

---

rules/S5693/csharp/rule.adoc
rules/S5693/description.adoc
rules/S5693/vbnet/rule.adoc

Also update default value for parameter to match the description

Modify S5693: Fix issue in noncompliant code example

---

rules/S2208/java/rule.adoc
rules/S2208/javascript/rule.adoc
rules/S2208/python/rule.adoc

Modify S2208: Migrate To LayC - wildcard imports

---

rules/S1116/cfamily/rule.adoc
rules/S1116/csharp/rule.adoc
rules/S1116/description.adoc
rules/S1116/java/rule.adoc

Modify S1116: Migrate to LayC

---

docs/link_formatting.adoc
rules/S4263/cfamily/rule.adoc
rules/S4436/cfamily/rule.adoc
rules/S5314/cfamily/rule.adoc

Update docs.microsoft.com to learn.microsoft.com.

Normalize Wikipedia and Microsoft links in CFamily

---

rules/S117/cfamily/rule.adoc
rules/S2589/what-is-the-potential-impact.adoc
rules/S3252/cfamily/rule.adoc

3247a2ec0544c9c86666cb08f051166e673a568a may be a bit controversial. I can drop it/adapt it if desired.

Fix minor issues in a few rules

---

rules/S2230/java/metadata.json
rules/S2230/java/rule.adoc

Modify S2230: extends with all Spring proxy

---

rules/S1075/csharp/rule.adoc
rules/S1075/description.adoc
rules/S1075/go/rule.adoc
rules/S1075/java/rule.adoc
rules/S1075/php/rule.adoc
rules/S1075/resources.adoc
rules/S1075/swift/rule.adoc
rules/S1075/vbnet/rule.adoc

Modify S1075: Fix resources link format

---

rules/S6804/java/metadata.json
rules/S6804/java/rule.adoc

Modify S6804: fix some typos in the description

---

rules/S6353/java/rule.adoc

Modify S6353: correct typo

---

rules/S4212/csharp/metadata.json

Modify S4212(C#): Deprecation

---

rules/S1144/apex/rule.adoc
rules/S1144/cfamily/rule.adoc
rules/S1144/csharp/rule.adoc
rules/S1144/description.adoc
rules/S1144/exceptions-jvm.adoc
rules/S1144/flex/rule.adoc
rules/S1144/java/rule.adoc
rules/S1144/kotlin/rule.adoc
rules/S1144/metadata.json
rules/S1144/php/rule.adoc
rules/S1144/python/rule.adoc
rules/S1144/rule.adoc
rules/S1144/scala/rule.adoc
rules/S1144/swift/rule.adoc
rules/S1144/why.adoc

Modify S1144: Migrate to LaYC

---

rules/S3776/cfamily/rule.adoc
rules/S3776/resources.adoc
rules/S5798/cfamily/rule.adoc
rules/S6004/cfamily/rule.adoc

To be rebased and merged, not squashed.

Minor improvements on CFamily rules

---

rules/S3337/php/metadata.json
rules/S3337/php/rule.adoc

Modify S3337: Change text to LayC

---

rules/S3336/php/rule.adoc

Modify S3336: Change text to LaYC (APPSEC-1217)

---

rules/S3334/php/metadata.json
rules/S3334/php/rule.adoc

Modify S3334: Change text to LaYC (APPSEC-1219)

---

rules/S6385/azureresourcemanager/how_to_fix_it.adoc
rules/S6385/azureresourcemanager/rule.adoc
rules/S6385/common/description.adoc
rules/S6385/common/fix/extra-mile.adoc
rules/S6385/common/fix/rationale.adoc
rules/S6385/common/impact/description.adoc
rules/S6385/common/summary.adoc
rules/S6385/description.adoc
rules/S6385/see.adoc
rules/S6385/terraform/rule.adoc

Modify S6385: Change text to LayC (APPSEC-1234)

---

rules/S6469/docker/rule.adoc

Modify S6469(docker): Migrate to LayC

---

rules/S1860/java/rule.adoc

Modify S1860: migrate to LayC

---

rules/S3374/xml/rule.adoc

Modify S3374: Change text to LayC (APPSEC-1241)

---

rules/S113/metadata.json
rules/S113/rule.adoc

Modify S113: rephrase title and description

---

rules/S3281/xml/metadata.json
rules/S3281/xml/rule.adoc

Modify S3281(xml): Migrate to LayC

---

rules/S3394/cobol/metadata.json
rules/S3394/cobol/rule.adoc

Modify S3394(COBOL): Migrate to LayC

---

rules/S109/javascript/rule.adoc

Modify S109 for JS: document exclusions

---

rules/S5487/cfamily/rule.adoc

Modify rule S5487: Fix example code

---

rules/S6680/message.adoc

Modify rule S6680: Adapt rule message

---

rules/S3330/python/rule.adoc

Modify rule S3330: Add FastAPI (APPSEC-1260)

---

docs/header_names/allowed_framework_names.adoc
rules/S5131/python/how-to-fix-it/fastapi.adoc
rules/S5131/python/rule.adoc

Modify rule S5131: Add FastAPI (APPSEC-1250)

---

rules/S3394/cobol/rule.adoc

Modify S3394(COBOL): Fix wording and typos

---

rules/S6745/java/metadata.json
rules/S6745/java/rule.adoc

I copied the metadata of `rules/S6539/java/metadata.json`

 Modify rule S6745(Java): Update rule description about FP and reduce severity

---

rules/S5524/cfamily/rule.adoc

Modify rule S5524: Small language tweaks following docs team review

---

rules/S4507/python/rule.adoc

Modify rule S4507: Add examples for Python Flask

---

docs/header_names/allowed_framework_names.adoc
rules/S5547/python/how-to-fix-it/ssl.adoc
rules/S5547/python/rule.adoc

Modify rule S5547: Add ssl module

---

rules/S4790/metadata.json

https://sonarsource.atlassian.net/browse/APPSEC-1311

Modify rule S4790: Remove tag spring

---

rules/S5148/html/rule.adoc
rules/S5148/javascript/rule.adoc

Modify rule S5148: Adjust code example format

---

rules/S1788/metadata.json

We mentioned this one this morning when reviewing our selected ADAPTABLE rules from other languages.

Modify S1788: change CC attribute to ADAPTABLE

---

rules/S6802/csharp/metadata.json
rules/S6802/csharp/rule.adoc

Modify rule S6802: Add a code example

---

rules/S6785/python/rule.adoc

Modify S6785: Update the Set limits section

---

rules/S5247/html/rule.adoc

Modify rule S5247: Remove examples of non covered engines

---

rules/S5659/python/how-to-fix-it/pyjwt.adoc

Modify rule S5659: Improve code example for PyJWT

---

rules/S3743/cfamily/rule.adoc

Modify rule S3743(cfamily): remove a dead link

---

rules/S2083/java/how-to-fix-it/java-se.adoc

Modify S2083(java): Improve the compliant sample

---

rules/S5918/python/metadata.json

Modify S5918 (Python): Add to default quality profile

---

rules/S5899/python/metadata.json

Modify S5899 (Python): Add to default quality profile

---

rules/S1172/python/rule.adoc

Modify S1172 (Python): Document exceptions

---

rules/S6839/python/rule.adoc

Modify rule S6839: Fix typos in Python code snippets in description

---

rules/S3518/python/rule.adoc

Modify rule S3518: Correct examples to be valid python code

---

rules/S1876/html/metadata.json

Modify rule S1876: No more a hotspot, now a code smell (APPSEC-1400)

---

rules/S6865/kubernetes/metadata.json
rules/S6865/kubernetes/rule.adoc

Modify Rule S6865: Add CWE 306

---

rules/S5131/python/how-to-fix-it/flask.adoc

Modify rule S5131: Fix Flask example (APPSEC-448)

---

rules/S5254/html/rule.adoc
rules/S5973/java/rule.adoc
rules/S5976/java/rule.adoc

Fix broken links from blogs.bing.com and testng.org

---

rules/S6620/metadata.json
rules/S6778/java/metadata.json

Modify Rule S6620: Fix title

---

rules/S6864/kubernetes/rule.adoc
rules/S6869/kubernetes/rule.adoc
rules/S6870/kubernetes/rule.adoc

updates in S6864, S6869 and S6870

Modify rule S6864: Update examples and removal of LimitRange for now

---

rules/S4027/csharp/rule.adoc

Modify rule S1126: Fix code example

---

rules/S6473/kubernetes/rule.adoc

Modify S6473: Fix indentation

---

rules/S120/plsql/rspecator.adoc
rules/S120/plsql/rule.adoc

S120: Add code examples for PLSQL

---

rules/S107/description.adoc
rules/S1135/description.adoc
rules/S3776/why.adoc
rules/S4830/impact.adoc
rules/S4830/rationale.adoc

mostly minor improvements to words and simple sentence structure

Docs review patch 3

---

rules/S6741/python/rule.adoc

Modify rule S6741: Fix broken pandas docs link

---

rules/S6504/docker/rule.adoc
rules/S6504/metadata.json

Modify rule S6504: Clarify intention of rule (APPSEC-1350)

---

frontend/package-lock.json

This removes the need for npm authenticated access.

Replace repox-npm-proxy with registry.npmjs.org

---

rules/S6661/javascript/rule.adoc

Modify rule S6661: clarify advantages of new syntax

---

rspec-tools/rspec_tools/coverage.py

Add dbd to plugin list to compute rules coverage

---

rules/S5131/java/how-to-fix-it/spring.adoc

Modify rule S5131: Fix Spring example

---

rules/S2004/javascript/rule.adoc

Modify rule S2004: Increase default threshold to four nested functions

---

rules/S871/cfamily/rule.adoc

CPP-4982,CPP-4913 S871 Mention that copies are allowed.

---

rules/S6667/metadata.json
rules/S6667/why-dotnet.adoc

Modify Rule S667: Update title

---

rules/S1113/java/rule.adoc

Update S1113: exception case for the finalizer attack

---

frontend/public/covered_rules.json
rules/S1696/csharp/rule.adoc
rules/S1696/java/metadata.json
rules/S1696/metadata.json
rules/S1696/rspecator.adoc

S1696 CSharp:
- RSPEC cleanup
- Promote rule to `SonarWay` profile

Modify rule S1696: promote C# to SonarWay

---

rules/S1994/csharp/metadata.json
rules/S1994/csharp/rule.adoc
rules/S1994/rspecator.adoc

- Promote S1994 to SonarWay.
- Update to LaYC format

Modify rule S1994: promote C# to SonarWay

---

rules/S1120/java/rule.adoc

Update S1120: Add note about supported indentation settings

---

rules/S3329/java/how-to-fix-it/java-cryptography-extension.adoc

Minor fix in S3329 Java code example

---

rules/S1244/csharp/metadata.json
rules/S1244/csharp/rule.adoc
rules/S1244/rspecator.adoc

S1244 CSharp:
- RSPEC cleanup
- Promote rule to `SonarWay` profile

Modify rule S1244: promote C# to SonarWay

---

rules/S4423/python/how-to-fix-it/openssl.adoc
rules/S4423/python/how-to-fix-it/ssl.adoc

Modify rule S4423: Adjust Python compliant examples (APPSEC-1556)

---

docs/header_names/allowed_framework_names.adoc

Clean up allowed Python framework names

---

rules/S5344/common/fix/password-hashing.adoc
rules/S5344/common/fix/plaintext-password.adoc
rules/S5344/impact.adoc
rules/S5344/metadata.json
rules/S5344/rationale.adoc
rules/S5344/summary.adoc

Modify S5344: Improve common text

---

rules/S6889/java/metadata.json

The rule would be better implemented with DBD in the future

Update S6889: Add leak tag

---

rules/S796/cfamily/rule.adoc

Modify Rule S796: fix typo

---

rules/S6877/java/metadata.json
rules/S6877/java/rule.adoc

Modify Rule S6877: Fix tags and update description

---

rules/S2053/common/fix/salt.adoc
rules/S2053/csharp/rule.adoc
rules/S2053/exceptions.adoc
rules/S2053/java/rule.adoc
rules/S2053/kotlin/rule.adoc
rules/S2053/metadata.json
rules/S2053/php/rule.adoc
rules/S2053/python/rule.adoc
rules/S2053/vbnet/rule.adoc

Modify rule S2053: Add an exception section for key derivation use case of KDFs

---

rules/S2694/java/rule.adoc

Modify rule S2694: Add code example for local classes

---

rules/S3649/javascript/how-to-fix-it/sequelize.adoc

Modify S3649(js): Fix code samples

---

rules/S6878/java/rule.adoc

Modify rule S6878: Remove one exception

---

rules/S1871/cfamily/exceptions.adoc
rules/S1871/cfamily/rule.adoc
rules/S3923/cfamily/metadata.json
rules/S3923/cfamily/rule.adoc

Update the description of these two closely related rules in accordance with the new understanding (see ticket).
Implementation ticket: [CPP-2002](https://sonarsource.atlassian.net/browse/CPP-2002)
[CPP-2002]: https://sonarsource.atlassian.net/browse/CPP-2002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify rules S1871 and S3923: Update description in accordance with the new understanding

---

rules/S2629/metadata.json
rules/S6664/metadata.json
rules/S6667/metadata.json
rules/S6668/metadata.json
rules/S6669/metadata.json
rules/S6670/metadata.json
rules/S6672/metadata.json
rules/S6673/metadata.json
rules/S6674/metadata.json
rules/S6675/metadata.json
rules/S6677/metadata.json
rules/S6678/metadata.json

C# Logging rules: add impact and attribute

---

rules/S2053/python/how-to-fix-it/cryptodome.adoc
rules/S2053/python/how-to-fix-it/cryptography.adoc
rules/S2053/python/how-to-fix-it/std.adoc
rules/S2053/python/rule.adoc

Modify rule S2053: Add better code examples and more how to fix sections

---

rules/S5566/cfamily/rule.adoc

Modify rule S5566: Cover std::ranges::contains (CPP-5058)

---

rules/S5500/cfamily/rule.adoc

Modify rule S5500: Accept conditional move and C++23 new features (CPP-4621,CPP-4623)

---

rules/S6786/python/metadata.json
rules/S6786/python/rule.adoc

Modify S6786(python): Improve description

---

rules/S6876/java/metadata.json

Modify rule S6876: fix wrong tag

---

rules/S6229/cfamily/rule.adoc

- Add an example with a local locale
- Add links to documentation
- Correct a few typos
- I did not add an independent example using the global locale but added a comment

Modify rule S6229 Add example with locale (CPP-5045)

---

rules/S6654/javascript/rule.adoc

This comes partially from [user feedback](https://github.com/SonarSource/SonarJS/issues/4623).

Modify rule S6654: Fix a few typos

---

rules/S5148/html/rule.adoc
rules/S5148/recommended.adoc

This PR should be merged once https://sonarsource.atlassian.net/browse/SONARHTML-220 is implemented.

S5148: Adjust description to fit improved detection

---

rules/S5148/html/rule.adoc
rules/S5148/recommended.adoc

Reverts SonarSource/rspec#3786 because first the detection logic needs to change.

Revert "S5148: Adjust description to fit improved detection"

---

rules/S5135/python/how-to-fix-it/python.adoc
rules/S5135/python/how-to-fix-it/yaml.adoc

Modify S5135(Python): Fix code samples

---

rules/S2076/python/how-to-fix-it/paramiko.adoc
rules/S2076/python/how-to-fix-it/python.adoc

For Python particularly, users like to take our code samples and test them. Our analyzers will typically not raise an issue on the code samples we showed here and this PR aims to solve this.

Modify S2076(python): Improve code samples

---

rules/S6497/docker/metadata.json

[APPSEC-844](https://sonarsource.atlassian.net/browse/APPSEC-844)
[APPSEC-844]: https://sonarsource.atlassian.net/browse/APPSEC-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify rule S6497: deprecation (APPSEC-844)

---

rules/S1153/java/metadata.json
rules/S6816/java/metadata.json
rules/S6831/java/metadata.json
rules/S6880/java/metadata.json
rules/S6913/java/metadata.json
rules/S6916/java/metadata.json

Update quickfix status for Java rules

---

rules/S6878/java/metadata.json
rules/S6913/java/metadata.json
rules/S6915/java/metadata.json

Modify rules S6878,S6913,S6915: add tag java21

---

rules/S6906/java/metadata.json

Modify rule S6906: remove "native" from title

---

rules/S6437/java/rule.adoc

Modify rule S6437: Fix compliant message in Java

---

.cirrus.yml
frontend/src/RulePage.tsx
frontend/src/utils/useRuleCoverage.ts

Fix Azure Resource Manager rules coverage

---

rules/S1104/csharp/rule.adoc

Modify rule S1104: Add exception for [Serializable]

---

rules/S1192/azureresourcemanager/exceptions-arm.adoc

Modify rule S1192: Add exception for ARM

---

rules/S6956/azureresourcemanager/rule.adoc

SONARIAC-1381 S6956 improve description

---

rules/S1091/html/metadata.json

Mark S1091 HTML variant as deprecated

---

rules/S1089/html/metadata.json

Mark S1089 HTML variant as deprecated

---

docs/header_names/allowed_framework_names.adoc
rules/S5147/java/how-to-fix-it/spring-data-redis.adoc
rules/S5147/java/rule.adoc

Modify rule S5147: Adding a how to fix section for Spring Data Redis (APPSEC-1565)

---

docs/header_names/allowed_framework_names.adoc
rules/S5496/java/how-to-fix-it/groovy.adoc
rules/S5496/java/rule.adoc

Modify rule S5496: Add an how to fix session for Java and Groovy (APPSEC-1587)

---

rules/S2353/vbnet/metadata.json

https://github.com/SonarSource/sonar-dotnet/issues/9175

Close S2353

---

rules/S3358/javascript/rule.adoc

Fixes https://sonarsource.atlassian.net/browse/JS-152?atlOrigin=eyJpIjoiZTlkYTUwYmUzNzQ3NDc2Y2JiYzUwMWIwYzNkNmYxNzkiLCJwIjoiaiJ9

Modify rule S3358 for JS: clarify exception

---

rules/S104/rpg/metadata.json
rules/S104/rpg/rule.adoc
rules/S1151/rpg/metadata.json
rules/S1151/rpg/rule.adoc
rules/S138/rpg/metadata.json
rules/S1752/rpg/rule.adoc
rules/S1753/rpg/rule.adoc

Modify rule S104, S138, S1151, S1752, S1753: Adapt titles and messages

---

rules/S5344/csharp/message.adoc

10_000 -> 100_000
See [conversation](https://sonarsource.slack.com/archives/CFVHSSMKP/p1715696548443399)

S5344: Fix typo

---

rules/S5421/cfamily/rule.adoc

Modify rule S5421: Update RSPEC and add exception for volatile

---

rules/S6273/cloudformation/rule.adoc
rules/S6273/description.adoc
rules/S6273/see.adoc
rules/S6273/summary.adoc

Update S6273: Re-organize and simplify description

---

rules/S6931/vbnet/metadata.json

Should be reviewed and merged along with https://github.com/SonarSource/sonar-dotnet/pull/9319

Update rule S6931: Remove VB deprecation

---

rules/S6946/jcl/metadata.json

Modify rule S6946: change CCT attribute

---

rules/S2807/cfamily/metadata.json
rules/S2807/cfamily/rule.adoc

CPP-4070 S2807 Make rule SonarWay and enforce hidden friends and cover free func operators

---

rules/S6711/python/metadata.json

Modify rule S6711: Corrected impacts

---

rules/S3630/cfamily/rule.adoc

CPP-5126 S3630 Add exceptions and updated description

---

rules/S6418/java/rule.adoc

Modify rule S6418: Fix link

---

rules/S1871/csharp/exceptions.adoc
rules/S1871/vbnet/exceptions.adoc

Modify S1871: Improve codes examples

---

rules/S4963/cfamily/metadata.json
rules/S5018/cfamily/rule.adoc

Modify rule S4963 (CPP-5113)

---

rules/S1694/csharp/rule.adoc

Modify rule S1694: Update dead link

---

rules/S1135/java/metadata.json

Modify rule  S1135: Update rule scope to All

---

rules/S6909/java/rule.adoc

Modify rule S6909: Fix errors in code examples

---

rules/S1542/plsql/parameters.adoc
rules/S1542/plsql/rule.adoc

Modify Rule S1542: Update default regex for PL/SQL

---

rules/S6869/kubernetes/rule.adoc

Modify rule S6869: Add examples for LimitRange

---

rules/S6897/kubernetes/rule.adoc

Modify rule S6897: Add examples for LimitRange

---

rules/S955/cfamily/metadata.json
rules/S955/cfamily/rule.adoc

Modify rule S955: Mention // (CPP-5129)

---

rules/S117/kubernetes/rule.adoc

Modify rule S117: Fix incorrect example for Kubernetes

---

rspec-tools/rspec_template/single_language/secrets/rule.adoc
rules/S6992/secrets/rule.adoc
rules/S6999/secrets/rule.adoc

 Modify rule S6992/S6999: Add missing variables (APPSEC-1885)

---

rules/S841/cfamily/metadata.json
rules/S841/cfamily/rule.adoc

See also https://github.com/SonarSource/sonar-cpp/pull/3784

Modify rule S841 Update with the specification from M23_154 (CPP-5136)

---

rules/S6893/kubernetes/rule.adoc

Modify rule S6893 Ensure whitespace in-between braces

---

rules/S7028/docker/rule.adoc

Update rule S7028: change example and implementation details

---

rules/S6587/docker/rule.adoc

Modify rule S6587: Describe a soltuion with a cache mount

---

rules/S3168/csharp/rule.adoc

Modify S3168: Fix error in compliant code example

---

rules/S7021/docker/rule.adoc

Modify rule S7021: improve text

---

rules/S7018/docker/metadata.json
rules/S7018/docker/rule.adoc

Modify rule S7018: change title, make applicable for single-line instructions

---

rules/S101/dart/rule.adoc
rules/S106/dart/metadata.json
rules/S106/dart/rule.adoc
rules/S1065/dart/rule.adoc
rules/S1116/dart/rule.adoc
rules/S1123/dart/rule.adoc
rules/S1128/dart/rule.adoc
rules/S1135/dart/rule.adoc
rules/S1143/dart/rule.adoc
rules/S115/dart/metadata.json
rules/S115/dart/rule.adoc
rules/S1161/comments-and-links.adoc
rules/S1161/dart/rule.adoc
rules/S1161/java/rule.adoc
rules/S1185/dart/rule.adoc
rules/S1206/dart/rule.adoc
rules/S121/dart/rule.adoc
rules/S1481/dart/rule.adoc
rules/S1874/dart/rule.adoc
rules/S2486/dart/rule.adoc
rules/S4977/dart/rule.adoc
rules/S6531/dart/rule.adoc
rules/S6535/dart/rule.adoc

__DO NOT SQUASH__: one commit per rule
Implementation: https://github.com/SonarSource/sonar-dart/pull/15

First batch of rules

---

rules/S101/dart/rule.adoc
rules/S106/dart/rule.adoc
rules/S1116/dart/rule.adoc
rules/S1134/dart/non-compliant-example.adoc
rules/S6531/dart/rule.adoc

Modify rules S101, S106, S1116, S1134, S6531: fix formatting and highlighting

---

rules/S7036/text/metadata.json

Modify rule S7036: Add tags

---

rules/S4052/csharp/metadata.json
rules/S4052/csharp/rule.adoc

Also converted the rule description to LayC.

Modify S4052: Promote C# rule to Sonar way

---

rules/S6649/java/metadata.json

Modify rule S6649: Fix rule id

---

rules/S6646/java/rule.adoc

Modify rule S6646: Fix non compliant examples

---

rules/S2971/dart/rule.adoc

Modify rule S2971: Add Dart language

---

rules/S6207/dart/rule.adoc

Modify rule S6207: Add Dart language

---

rules/S4123/dart/rule.adoc

Modify rule S4123: Add Dart language

---

rules/S3257/dart/rule.adoc

Modify Rule S3257: Add Dart language

---

rules/S1314/cfamily/rule.adoc
rules/S7035/cfamily/metadata.json
rules/S7035/cfamily/rule.adoc
rules/S7040/cfamily/metadata.json
rules/S7040/cfamily/rule.adoc

Modify rules S1314,S7035,S7040: small improvements (CPP-5503)

---

rules/S3240/dart/rule.adoc

Modify Rule S3240: Update Dart description

---

.cirrus.yml
ci/cirrus-cache.sh
ci/validate_metadata.sh
rspec-tools/rspec_tools/checklinks.py
rules/S1049/cfamily/rule.adoc
rules/S1234/cfamily/rule.adoc
rules/S1248/cfamily/rule.adoc
rules/S1252/cfamily/rule.adoc
rules/S1260/cfamily/rule.adoc
rules/S1294/rule.adoc
rules/S1696/java/rule.adoc
rules/S2192/rule.adoc
rules/S2215/rule.adoc
rules/S2275/cfamily/rule.adoc
rules/S2275/java/rule.adoc
rules/S2389/java/rule.adoc
rules/S2390/java/rule.adoc
rules/S2992/cfamily/rule.adoc
rules/S3708/cfamily/rule.adoc
rules/S3941/cfamily/rule.adoc
rules/S3941/java/rule.adoc
rules/S3955/cfamily/rule.adoc
rules/S3955/java/rule.adoc
rules/S4066/java/rule.adoc
rules/S5272/cfamily/rule.adoc
rules/S801/cfamily/rule.adoc
rules/S865/cfamily/rule.adoc
rules/S901/cfamily/rule.adoc
rules/S901/java/rule.adoc

Rebase for merge.
Improve `validate_link.sh` and other CI tools (see commits for details).
Ignore link validation failures with wiki.sei.cmu.edu and drupal.org (see comments in the exception list).
---
Note: given that now the output is mostly `skip probing because it was reached recently`, we could consider reducing the amount of log output... but in a separate PR.

CI improvements

---

rules/S2068/description-no-recommend.adoc
rules/S2068/description.adoc
rules/S2068/python/rule.adoc

Modify rule S2068: Update documentation to not recommend the customization

---

rules/S3512/dart/rule.adoc

Modify rule S3512: Update Dart examples and resources

---

rules/S2471/dart/rule.adoc

Modify rule S2471: improve resources and add rspecator

---

rules/S2175/dart/rule.adoc

Modify rule S2175: improve resources and add rspecator

---

rules/S5416/dart/rule.adoc

Modify rule S5416: improve resources and add rspecator

---

rules/S3562/dart/rule.adoc

Modify rule S3562: improve resources and add rspecator

---

rules/S1065/dart/rule.adoc

Modify rule S1065: Fix resources

---

rules/S2432/dart/rule.adoc

Modify rule S2432: Fix resources and add rspecator

---

rules/S6320/java/rule.adoc
rules/S6416/java/rule.adoc
rules/S6555/java/rule.adoc
rules/S6707/java/rule.adoc
rules/S6976/java/rule.adoc

Modify rules S6320;S6416;S6555;S6707;S6976 Update examples

---

rules/S2589/python/rule.adoc
rules/S5633/python/rule.adoc
rules/S6417/python/rule.adoc
rules/S6466/python/rule.adoc
rules/S6886/python/rule.adoc

Modify rules S6886, S2589, S5633, S6417: Fix examples

---

docs/header_names/allowed_framework_names.adoc
rules/S5131/csharp/how-to-fix-it/blazor.adoc
rules/S5131/csharp/rule.adoc

Implementation ticket: https://sonarsource.atlassian.net/issues/SONARSEC-5284

Modify rule S5131: Add fix for Blazor (APPSEC-1898)

---

rules/S2259/java/metadata.json
rules/S2259/java/rule.adoc
rules/S2583/java/metadata.json
rules/S2583/java/rule.adoc
rules/S2589/java/metadata.json
rules/S2589/java/rule.adoc
rules/S3518/java/metadata.json
rules/S3518/java/rule.adoc
rules/S3655/java/metadata.json
rules/S3655/java/rule.adoc
rules/S3959/java/metadata.json
rules/S3959/java/rule.adoc

as the new rules are slightly different and are available in different SQ editions.

Modify rules S2259;S2583;S2589;S3518;S3655;S3959 Remove replacement rules and update description for deprecated SE rules

---

rules/S7046/dart/rule.adoc

Modify rule S7046: Add a link to "camel case" in the rule description

---

rules/S4502/see.adoc
rules/S5131/common/resources/articles.adoc

[S4502|S5131] Add resources and fix resources style

---

rules/S6865/kubernetes/metadata.json
rules/S6865/kubernetes/rule.adoc

Modify S6865(K8s): Rework Rule for realistic detection

---

rules/S6330/cloudformation/rule.adoc
rules/S6330/javascript/rule.adoc
rules/S6330/python/rule.adoc
rules/S6330/terraform/rule.adoc

Modify rule S6330: Default Queue encryption is now SSE-SQS (APPSEC-339)

---

rules/S6680/metadata.json

Modify rule S6680: Add correct Clean Code Taxonomy attributes

---

docs/header_names/allowed_framework_names.adoc
rules/S2755/java/how-to-fix-it/dom4j.adoc
rules/S2755/java/how-to-fix-it/java-se.adoc
rules/S2755/java/how-to-fix-it/jdom2.adoc
rules/S2755/java/how-to-fix-it/sax.adoc
rules/S2755/java/rule.adoc

Modify rule S2755: Simplify how to fix it section

---

rules/S6555/java/metadata.json
rules/S6646/java/metadata.json
rules/S6649/java/metadata.json
rules/S6651/java/metadata.json
rules/S6707/java/metadata.json
rules/S6780/java/metadata.json
rules/S6976/java/metadata.json

Modify rules S6651,S6649,S6646,S6555,S6976,S6707,S6780: Add to SonarWay

---

rules/S6249/cloudformation/rule.adoc

Specification ticket: [APPSEC-50](https://sonarsource.atlassian.net/browse/APPSEC-50)
Implementation ticket: [SONARIAC-976](https://sonarsource.atlassian.net/browse/SONARIAC-976)
[APPSEC-50]: https://sonarsource.atlassian.net/browse/APPSEC-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARIAC-976]: https://sonarsource.atlassian.net/browse/SONARIAC-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify rule S6249: Fix code CloudFornation code examples (APPSEC-50)

---

rules/S3329/java/how-to-fix-it/java-cryptography-extension.adoc
rules/S3329/kotlin/how-to-fix-it/java-cryptography-extension.adoc
rules/S3329/python/how-to-fix-it/pyca.adoc
rules/S3329/python/how-to-fix-it/pycryptodome.adoc

Modify rule S3329: Correct example code

---

rules/S6555/java/metadata.json
rules/S6646/java/metadata.json
rules/S6649/java/metadata.json
rules/S6651/java/metadata.json
rules/S6707/java/metadata.json
rules/S6780/java/metadata.json
rules/S6976/java/metadata.json

This reverts commit da7543e22ac16a09c055482858d4229747c8896f.

Modify rules S6651,S6649,S6646,S6555,S6976,S6707,S6780: Undo adding to SonarWay

---

rules/S7026/docker/rule.adoc

Modify rule S7026: Add exceptions

---

rules/S6382/terraform/highlighting.adoc
rules/S6382/terraform/message.adoc
rules/S6382/terraform/rule.adoc

Modify Rule S6382: Fix outdated properties (APPSEC-773)

---

rules/S3457/csharp/rule.adoc

Modify rule S3457: Fix link format

---

rules/S120/dart/rule.adoc

Modify S120: update Dart description

---

rules/S1854/dart/metadata.json

Modify rule S1854: Remove from Sonar-Way

---

docs/header_names/allowed_framework_names.adoc
rules/S6973/python/how-to-fix-it/pytorch.adoc
rules/S6973/python/how-to-fix-it/scikit-learn.adoc
rules/S6973/python/metadata.json
rules/S6973/python/rule.adoc

Modify rule S6973: Adding PyTorch optimizers

---

rules/S7036/text/rule.adoc

Modify rule S7036: Update rule description

---

rules/S7036/text/metadata.json

Modify rule S7036: Remove from Sonar Way

---

rules/S101/dart/rule.adoc
rules/S7046/dart/rule.adoc

Modify rules S101 and S7046: add related rules

---

rules/S5856/dart/rule.adoc

Modify rule S5856: Improve resources

---

rules/S7079/dart/rule.adoc

Modify rule S7079: Fix inline code formatting

---

rules/S7090/dart/rule.adoc

Modify rule S7090: Fix formatting of inline code

---

rules/S7089/dart/rule.adoc

Modify rule S7089: Add S7090 to related rules in resources

---

rules/S7084/dart/metadata.json

Modify rule S7084: Remove from Sonar-Way

---

rules/S5553/cfamily/metadata.json

Modify rule S5553: Update tags and add missing SE tag

---

rspec-tools/rspec_tools/coverage.py

Include "sonar-architecture" in the list of repos for updating rules coverage script

---

frontend/src/RulePage.tsx
rspec-tools/rspec_tools/coverage.py
rules/S2260/ansible/metadata.json
rules/S2260/ansible/rule.adoc

Modify S2260: add Ansible

---

rules/S7105/dart/rule.adoc

Modify rule S7105: Fix ellipses escaping in rule description

---

rules/S6781/csharp/rule.adoc

Modify S6781(C#): Add alternative message

---

rules/S6711/python/rule.adoc

Modify rule S6711: SONARPY-2016: Make rule examples for S6711 module-level

---

rules/S7108/dart/rule.adoc

Modify rule S7108: Fix formatting and improve description

---

rules/S7035/cfamily/rule.adoc

CPP-5803 S7035 Add exception for casts to bool

---

rules/S7107/dart/rule.adoc

Modify rule S7107: Fix non-compliant example

---

rules/S1190/java/rule.adoc

The rule implementation covers only the unnamed variable _, prior to Java 22

Modify rule S1190

---

rules/S7114/dart/rule.adoc

Modify rule S7114: Improve "Why is this an issue" grammar

---

rules/S7109/dart/rule.adoc

Modify rule S7109: Improve grammar in "how to fix" section

---

rules/S7113/dart/rule.adoc

Modify rule S7113: Fix S7112 rule number in related rules

---

rules/S7112/dart/rule.adoc

Modify rule S7112: Add S7113 as related rule

---

rules/S7124/dart/rule.adoc

Modify rule S7124: fix non-compiling code example

---

rules/S7120/dart/rule.adoc

Modify rule S7120: Improve description and fix code example

---

rules/S3422/xml/rule.adoc

SONARXML-194 S3422: Add Compliant code examples

---

rules/S6929/python/metadata.json

Modify rule S6929: Corrected quickfix metadata

---

rspec-tools/README.adoc
rspec-tools/rspec_tools/validation/description.py
rspec-tools/tests/resources/invalid-rules/S100/php/metadata.json
rspec-tools/tests/resources/invalid-rules/S100/php/rule.adoc
rspec-tools/tests/resources/invalid-rules/S100/php/rule.html
rspec-tools/tests/validation/test_description_validation.py

Existing violations were fixed:
* #4408
* #4409

Detect title as subsections

---

rules/S6709/python/metadata.json
rules/S6727/python/metadata.json
rules/S6729/python/metadata.json
rules/S6734/python/metadata.json
rules/S6735/python/metadata.json
rules/S6740/python/metadata.json
rules/S6882/python/metadata.json
rules/S6883/python/metadata.json
rules/S6886/python/metadata.json
rules/S6887/python/metadata.json
rules/S6890/python/metadata.json
rules/S6894/python/metadata.json
rules/S6899/python/metadata.json
rules/S6900/python/metadata.json
rules/S6903/python/metadata.json
rules/S6908/python/metadata.json
rules/S6911/python/metadata.json
rules/S6918/python/metadata.json
rules/S6919/python/metadata.json
rules/S6925/python/metadata.json
rules/S6928/python/metadata.json
rules/S6929/python/metadata.json
rules/S6969/python/metadata.json
rules/S6971/python/metadata.json
rules/S6972/python/metadata.json
rules/S6973/python/metadata.json
rules/S6974/python/metadata.json
rules/S6978/python/metadata.json
rules/S6984/python/metadata.json
rules/S6985/python/metadata.json

Ensure issue severities are consistent between old model and CCT

---

rules/S6473/kubernetes/rule.adoc

Modify rule S6473: Fix Kubernetes service code example

---

rules/S5144/csharp/how-to-fix-it/dotnet.adoc

Modified S5144(C#): Use HttpClient instead of old WebRequest

---

rules/S6473/ansible/rule.adoc
rules/S6473/docker/rule.adoc

Modify rule S6473: Add parameter

---

rules/S2260/dart/metadata.json
rules/S2260/dart/rule.adoc

Modify rule S2260: Improve title and description

---

rules/S2551/csharp/rule.adoc
rules/S2551/resources-dotnet.adoc
rules/S2551/vbnet/rule.adoc
rules/S2551/why-dotnet.adoc

Fixes [NET-407](https://sonarsource.atlassian.net/browse/NET-407)
[NET-407]: https://sonarsource.atlassian.net/browse/NET-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NET-407 Update S2551 rule description.

---

rules/S6603/metadata.json
rules/S6603/resources-dotnet.adoc
rules/S6603/why-dotnet.adoc

[NET-566](https://sonarsource.atlassian.net/browse/NET-566)
[NET-566]: https://sonarsource.atlassian.net/browse/NET-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify rule S6603: Remove from SonarWay and update benchmarks

---

rules/S6377/common/impact.adoc
rules/S6377/common/impacts/injection.adoc
rules/S6377/common/impacts/spoofing.adoc
rules/S6377/common/rationale.adoc
rules/S6377/csharp/how-to-fix/net-core.adoc

Modify rule S6377: Clarify C# compliant code sample (APPSEC-1731)

---

rules/S5144/common/fix/blacklist.adoc
rules/S5144/common/fix/pre-approved-list.adoc
rules/S5144/common/pitfalls/blacklist-toctou.adoc
rules/S5144/csharp/how-to-fix-it/dotnet.adoc
rules/S5144/java/how-to-fix-it/java-se.adoc
rules/S5144/javascript/how-to-fix-it/node.adoc
rules/S5144/php/how-to-fix-it/core.adoc
rules/S5144/php/how-to-fix-it/guzzle.adoc
rules/S5144/python/how-to-fix-it/httpx.adoc
rules/S5144/python/how-to-fix-it/python.adoc
rules/S5144/python/how-to-fix-it/requests.adoc

Modify Rule S5144: Add information on blacklisting

---

rules/S6287/message.adoc

Modify Rule S6287: Improve Message

---

rules/S5131/python/rule.adoc

Modify rule S5131: Fix dead link

---

rules/S6096/common/resources/articles.adoc

Modify rule S6096: Improve the resources section

---

rules/S6869/kubernetes/metadata.json
rules/S7018/docker/metadata.json
rules/S7019/docker/metadata.json
rules/S7019/docker/rule.adoc
rules/S7020/docker/metadata.json
rules/S7021/docker/metadata.json
rules/S7023/docker/metadata.json
rules/S7026/docker/metadata.json
rules/S7030/docker/metadata.json
rules/S7031/docker/metadata.json

SONARIAC-1789 Align software quality impact and defaultSeverities on IaC Rules

---

shared_content/secrets/impact/phishing.adoc

Modify shared `phising.adoc`

---

rules/S2068/php/rule.adoc

Modify rule S2068: Description should not recommend customizing it with tokens

---

rspec-tools/rspec_tools/checklinks.py
rules/S6639/common/resources/documentation.adoc

Fix link checker

---

rules/S1441/javascript/metadata.json
rules/S2310/javascript/metadata.json
rules/S3523/javascript/metadata.json
rules/S3723/metadata.json
rules/S6661/javascript/metadata.json
rules/S6666/javascript/metadata.json
rules/S6671/javascript/metadata.json
rules/S6676/javascript/metadata.json
rules/S6679/javascript/metadata.json
rules/S6749/javascript/metadata.json
rules/S6754/javascript/metadata.json
rules/S6759/javascript/metadata.json
rules/S6767/javascript/metadata.json
rules/S6770/javascript/metadata.json
rules/S6775/javascript/metadata.json
rules/S6836/javascript/metadata.json
rules/S6849/javascript/metadata.json

JS-399 - Fix MQR / legacy severity discrepancies

---

rules/S2175/java/rule.adoc

Modify rule S2175: SONARJAVA-5186 Improve Test Code Support Part 3

---

rules/S6721/secrets/rule.adoc

Modify rule S6721: Fix description

---

rules/S2077/vbnet/rule.adoc

NET-762 Remove S3649 mention from S2077 rspec

---

rules/S2325/csharp/rule.adoc

Modify rule S2325: Add WinForms and WPF EventHandler exception

---

rules/S5594/xml/metadata.json

Deprecate S5594

---

frontend/src/RulePage.tsx
rspec-tools/rspec_tools/coverage.py

[NO-JIRA] Fix rule coverage for Text and Secrets

---

rules/S6437/docker/rule.adoc
rules/S6587/docker/rule.adoc

Update rule S6437: add multi-stage build exceptions

---

rules/S7031/docker/rule.adoc

Update rule S7031: add multi-stage build exceptions

---

rules/S6961/csharp/metadata.json

Modify rule S6961: Add perftag back

---

rules/S2930/csharp/rule.adoc

NET-915 Modify S2930: Fix typo

---

rules/S1197/vbnet/metadata.json

[NET-988](https://sonarsource.atlassian.net/browse/NET-988)
[NET-988]: https://sonarsource.atlassian.net/browse/NET-988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NET-988 Remove S1197 from SonarWay for VB.NET

---

rules/S4487/csharp/rule.adoc

[Discuss post](https://discuss.sonarsource.com/t/non-compliant-code-example-is-invalid-for-csharpsquid-s4487/21595)

Modify rule S4487: Fix error in code example

---

rules/S7180/java/rule.adoc

[SONARJAVA-5285](https://sonarsource.atlassian.net/browse/SONARJAVA-5285)
[SONARJAVA-5285]: https://sonarsource.atlassian.net/browse/SONARJAVA-5285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5285 Modify rule S7180: update wrong rule description

---

rules/S7179/java/metadata.json

Modify S7179: change scope from Tests to Main

---

rules/S7177/java/metadata.json

[SONARJAVA-5322](https://sonarsource.atlassian.net/browse/SONARJAVA-5322)

SONARJAVA-5322 Modify rule S7177: add tests to tags

---

rspec-tools/rspec_template/single_language/secrets/metadata.json

DefaultSeverity and code impact should be in sync with each other.

Fix Secrets template rule

---

rules/S7190/java/metadata.json

Modify rule S7190: add tests tag

---

rules/S2144/java/metadata.json
rules/S2150/java/metadata.json
rules/S3273/javascript/metadata.json
rules/S3853/xml/metadata.json
rules/S5383/apex/metadata.json
rules/S5497/apex/metadata.json
rules/S5631/python/metadata.json
rules/S5650/python/metadata.json
rules/S5651/python/metadata.json
rules/S5654/python/metadata.json
rules/S5755/python/metadata.json
rules/S6290/secrets/metadata.json
rules/S6745/java/metadata.json
rules/S6950/jcl/metadata.json
rules/S6951/jcl/metadata.json

[RULEAPI-832](https://sonarsource.atlassian.net/browse/RULEAPI-832)
[RULEAPI-832]: https://sonarsource.atlassian.net/browse/RULEAPI-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RULEAPI-832 Fix missing automatically updatable rules

---

rules/S1050/cfamily/metadata.json
rules/S5405/cfamily/metadata.json
rules/S5410/cfamily/metadata.json
rules/S5782/cfamily/metadata.json
rules/S6778/java/metadata.json
rules/S6826/java/metadata.json
rules/S6879/java/metadata.json
rules/S6888/java/metadata.json
rules/S6938/jcl/metadata.json
rules/S6942/jcl/metadata.json
rules/S6947/jcl/metadata.json
rules/S6952/azureresourcemanager/metadata.json
rules/S6975/azureresourcemanager/metadata.json
rules/S6991/cfamily/metadata.json
rules/S7072/javascript/metadata.json
rules/S7073/javascript/metadata.json
rules/S7081/javascript/metadata.json

[RULEAPI-834](https://sonarsource.atlassian.net/browse/RULEAPI-834)
[RULEAPI-834]: https://sonarsource.atlassian.net/browse/RULEAPI-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RULEAPI-834 Update remaining rules where defaultSeverity is different from MQR

---

rules/S6660/python/metadata.json

Modify S6660: Fix impacts and default severity

---

rules/S6953/azureresourcemanager/metadata.json
rules/S7021/docker/metadata.json
rules/S7021/docker/rule.adoc

Modify rule S6953, S7021: Fix MQR inconsistencies

---

rules/S2053/message.adoc
rules/S2053/php/how-to-fix-it/core.adoc

Update S2053: Align recommended salt length

---

rules/S4507/kotlin/metadata.json
rules/S4507/kotlin/rule.adoc
rules/S4507/see-mobile.adoc
rules/S4507/xml/metadata.json
rules/S4507/xml/rule.adoc

[SONARKT-580](https://sonarsource.atlassian.net/browse/SONARKT-580)
[SONARKT-580]: https://sonarsource.atlassian.net/browse/SONARKT-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update S4507: Add kotlin code examples (SONARKT-580)

---

rules/S6426/javascript/metadata.json

Noticed this through the new configs realignment

Update S6426 to scope Tests

---

rspec-tools/rspec_template/single_language/secrets/metadata.json
rspec-tools/rspec_template/single_language/secrets/rule.adoc
rules/S6652/secrets/rule.adoc
rules/S6689/secrets/rule.adoc
rules/S6784/secrets/rule.adoc
rules/S7169/secrets/rule.adoc
shared_content/secrets/impact/generic_impact.adoc
shared_content/secrets/impact/specific_impact_intro.adoc

[SONARTEXT-328](https://sonarsource.atlassian.net/browse/SONARTEXT-328)
[SONARTEXT-328]: https://sonarsource.atlassian.net/browse/SONARTEXT-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARTEXT-328 Improve generic secret template

---

rules/S6809/java/rule.adoc

[SONARJAVA-5401](https://sonarsource.atlassian.net/browse/SONARJAVA-5401)
[SONARJAVA-5401]: https://sonarsource.atlassian.net/browse/SONARJAVA-5401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5401 S6809 Fix incomplete code in an example

---

rules/S7206/kotlin/metadata.json

Modify rule S7206: Fix Clean Code metadata

---

rules/S7190/java/rule.adoc

Modify rule S7190: improve test samples

---

rules/S6474/kotlin/rule.adoc

[SONARKT-600](https://sonarsource.atlassian.net/browse/SONARKT-600)
[SONARKT-600]: https://sonarsource.atlassian.net/browse/SONARKT-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update issue messages for S6474 (SONARKT-600)

---

rules/S6474/kotlin/rule.adoc

[SONARKT-600](https://sonarsource.atlassian.net/browse/SONARKT-600)
[SONARKT-600]: https://sonarsource.atlassian.net/browse/SONARKT-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update rule S6474: Update message and highlighting (SONARKT-600)

---

docs/header_names/allowed_framework_names.adoc
rules/S3649/common/fix/code-rationale.adoc
rules/S3649/common/fix/prepared-statements.adoc
rules/S3649/python/how-to-fix-it/databases.adoc
rules/S3649/python/how-to-fix-it/sqlalchemy.adoc
rules/S3649/python/how-to-fix-it/sqlite3.adoc
rules/S3649/python/rule.adoc

Modify rule S3649: Add databases support (APPSEC-1251)

---

rules/S7207/xml/rule.adoc

Modify rule S7207: Add additional documentation

---

rules/S1161/dart/rule.adoc
rules/S7055/dart/rule.adoc

[DART-213](https://sonarsource.atlassian.net/browse/DART-213)
Update RSPEC after upgrade of sonar-dart to Dart SDK 3.7.2 (https://github.com/SonarSource/sonar-dart/pull/210)
[DART-213]: https://sonarsource.atlassian.net/browse/DART-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DART-213 Modify rules S1161, S7055: update descriptions and messages

---

frontend/src/RulePage.tsx

Update Jira project keys for T-SQL, PL/SQL and VB6

---

rules/S5542/common/resources/standards-mobile.adoc

Modify S5542: Fix missing CWE link

---

rules/S6249/cloudformation/rule.adoc
rules/S6249/highlighting.adoc
rules/S6249/message.adoc
rules/S6249/terraform/rule.adoc

Ticket: [SONARIAC-389](https://jira.sonarsource.com/browse/SONARIAC-389)

Modify rule S6249: update message

---

rules/S106/rust/metadata.json
rules/S126/rust/metadata.json
rules/S1612/rust/metadata.json
rules/S2148/rust/metadata.json
rules/S7411/rust/metadata.json
rules/S920/rust/metadata.json

Modify rules S106,S126,S1612,S2148,S7411,S920 Remove from SonarWay

---

rules/S5443/cfamily/rule.adoc

Modify rule S5443(cfamily): Fix src blocks highlighting

---

rules/S2068/go/rule.adoc

[SONARGO-118](https://sonarsource.atlassian.net/browse/SONARGO-118)
[SONARGO-118]: https://sonarsource.atlassian.net/browse/SONARGO-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARGO-118 Update S2068 exception category

---

rules/S6362/see.adoc
rules/S7409/kotlin/metadata.json
rules/S7409/kotlin/rule.adoc

[SONARKT-637](https://sonarsource.atlassian.net/browse/SONARKT-637)
[SONARKT-637]: https://sonarsource.atlassian.net/browse/SONARKT-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update rule S7409: Clarify rule title and rule text (SONARKT-637)

---

rules/S7435/metadata.json

[SONARJAVA-5403](https://sonarsource.atlassian.net/browse/SONARJAVA-5403)
Related to [this comment](https://github.com/SonarSource/sonar-java/pull/5069#discussion_r2022218075).
[SONARJAVA-5403]: https://sonarsource.atlassian.net/browse/SONARJAVA-5403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5403 Modify rule S7435: set quickfix for all languages

---

rules/S5344/java/how-to-fix-it/java-cryptography-extension.adoc
rules/S5344/java/how-to-fix-it/spring.adoc
rules/S5344/java/rule.adoc

[SONARKT-582](https://sonarsource.atlassian.net/browse/SONARKT-582)
[SONARKT-582]: https://sonarsource.atlassian.net/browse/SONARKT-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Modify S5344: Add JCE code example for Java (SONARKT-582)

---

rules/S110/metadata.json

Modify rule S110: Added architecture tag

---

rules/S1200/metadata.json

Modify rule S1200: Added architecture & design tags

---

rules/S138/metadata.json

Modify rule S138: Added architecture & design tags

---

rules/S1448/metadata.json

Modify rule S1448: Added architecture & design tags

---

rules/S3776/metadata.json

Modify rule S3776: Added architecture & design tags

---

rules/S6627/metadata.json

Modify rule S6627: Added architecture & design tags

---

rules/S6861/javascript/metadata.json

Modify rule S6861: Added architecture & design tags

---

rules/S1217/java/rule.adoc

[SONARJAVA-5476](https://sonarsource.atlassian.net/browse/SONARJAVA-5476)
[SONARJAVA-5476]: https://sonarsource.atlassian.net/browse/SONARJAVA-5476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5476 Modify rule S1217: Fix broken link

---

rules/S5332/java/rule.adoc
rules/S5332/kotlin/rule.adoc

[SONARJAVA-5476](https://sonarsource.atlassian.net/browse/SONARJAVA-5476)
[SONARJAVA-5476]: https://sonarsource.atlassian.net/browse/SONARJAVA-5476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-5476 Modify rule S5332: Update link to JSch library to a replacement

---

rules/S3267/csharp/rule.adoc

[NET-1349](https://sonarsource.atlassian.net/browse/NET-1349)
[NET-1349]: https://sonarsource.atlassian.net/browse/NET-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NET-1349 Modify S3267: Mention IAsyncEnumerable

---

rules/S2076/kotlin/metadata.json
rules/S2078/kotlin/metadata.json
rules/S2083/kotlin/metadata.json
rules/S2091/kotlin/metadata.json
rules/S2631/kotlin/metadata.json
rules/S3649/kotlin/metadata.json
rules/S5131/kotlin/metadata.json
rules/S5135/kotlin/metadata.json
rules/S5144/kotlin/metadata.json
rules/S5145/kotlin/metadata.json
rules/S5146/kotlin/metadata.json
rules/S5147/kotlin/metadata.json
rules/S5334/kotlin/metadata.json
rules/S5496/kotlin/metadata.json
rules/S5883/kotlin/metadata.json
rules/S6096/kotlin/metadata.json
rules/S6173/kotlin/metadata.json
rules/S6287/kotlin/metadata.json
rules/S6350/kotlin/metadata.json
rules/S6384/kotlin/metadata.json
rules/S6390/kotlin/metadata.json
rules/S6398/kotlin/metadata.json
rules/S6399/kotlin/metadata.json
rules/S6547/kotlin/metadata.json
rules/S6549/kotlin/metadata.json
rules/S7044/kotlin/metadata.json

[SONARSEC-6382](https://sonarsource.atlassian.net/browse/SONARSEC-6382)
[SONARSEC-6382]: https://sonarsource.atlassian.net/browse/SONARSEC-6382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARSEC-6382 Modify rules: kotlin taint rules have beta status

---

rules/S1699/csharp/rule.adoc

[NET-1371](https://sonarsource.atlassian.net/browse/NET-1371)
Part of NET-1370
[NET-1371]: https://sonarsource.atlassian.net/browse/NET-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NET-1371 Modify S1699: Fix bullet list issue

---

rules/S6857/java/rule.adoc

[SONARJAVA-4917](https://sonarsource.atlassian.net/browse/SONARJAVA-4917)
[SONARJAVA-4917]: https://sonarsource.atlassian.net/browse/SONARJAVA-4917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARJAVA-4917 Modify rule S6857: add information about property placeholder and new code samples

---

docs/header_names/allowed_framework_names.adoc

Add Python async libraries in allowed framework names

---

docs/header_names/allowed_framework_names.adoc
rules/S3649/go/how-to-fix-it/sqlx.adoc
rules/S3649/go/rule.adoc

[SONARSEC-6447](https://sonarsource.atlassian.net/browse/SONARSEC-6447)
Part of SONARSEC-6447
[SONARSEC-6447]: https://sonarsource.atlassian.net/browse/SONARSEC-6447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARSEC-6447: Modify Rule S3649: Add sqlx example

---

docs/header_names/allowed_framework_names.adoc
rules/S5344/go/how-to-fix-it/argon2.adoc
rules/S5344/go/how-to-fix-it/bcrypt.adoc
rules/S5344/go/how-to-fix-it/pbkdf2.adoc
rules/S5344/go/how-to-fix-it/scrypt.adoc
rules/S5344/go/rule.adoc

[SONARGO-465](https://sonarsource.atlassian.net/browse/SONARGO-465)
[SONARGO-465]: https://sonarsource.atlassian.net/browse/SONARGO-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARGO-465 Modify rule S5344: Add GO code samples

---

rules/S7019/docker/rule.adoc

[SONARIAC-1972](https://sonarsource.atlassian.net/browse/SONARIAC-1972)
[SONARIAC-1972]: https://sonarsource.atlassian.net/browse/SONARIAC-1972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARIAC-1972 Modify rule S7019: Fix list display

---

rules/S7027/csharp/metadata.json
rules/S7027/java/metadata.json
rules/S7091/csharp/metadata.json
rules/S7091/java/metadata.json
rules/S7134/metadata.json
rules/S7197/metadata.json

Update architecture rule status to "beta"

---

rules/S3016/java/rule.adoc

Modify rule S3016: Add comment about rule

---

rules/S3009/java/rule.adoc

SONARJAVA-5575 Add benchmark average-time results for rule S3009

---

rules/S2083/javascript/how-to-fix-it/node.adoc

Modify rule S2083 - Fix const redefinition in js compliant code sample

---

rules/S5334/javascript/how-to-fix-it/mongo.adoc

Modify rule S5334 - remove Noncompliant comment in compliant code

---

rules/S2076/go/metadata.json
rules/S2083/go/metadata.json
rules/S3649/go/metadata.json
rules/S5144/go/metadata.json
rules/S5145/go/metadata.json
rules/S5146/go/metadata.json
rules/S6096/go/metadata.json
rules/S6350/go/metadata.json

[SONARSEC-6500](https://sonarsource.atlassian.net/browse/SONARSEC-6500)
[SONARSEC-6500]: https://sonarsource.atlassian.net/browse/SONARSEC-6500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARSEC-6500 Add "Beta" tag to Go security rules

---

rules/S1871/csharp/exceptions.adoc

Modify S1871: Update Exception message

---

rules/S6418/java/metadata.json
rules/S6418/java/rule.adoc

Modify rule S6418 for Java: Add mobile metadata and link

---

rules/S3885/csharp/rule.adoc

[NET-2100](https://sonarsource.atlassian.net/browse/NET-2100)
[NET-2100]: https://sonarsource.atlassian.net/browse/NET-2100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NET-2100 Modify S3885: Add AssemblyResolve event exception

---

rules/S2260/ansible/rule.adoc
rules/S2260/azureresourcemanager/rule.adoc
rules/S2260/cloudformation/rule.adoc
rules/S2260/docker/rule.adoc
rules/S2260/go/rule.adoc
rules/S2260/json/metadata.json
rules/S2260/json/rule.adoc
rules/S2260/php/rule.adoc
rules/S2260/yaml/metadata.json
rules/S2260/yaml/rule.adoc

[SONARIAC-2085](https://sonarsource.atlassian.net/browse/SONARIAC-2085)
Also improved the consistency of S2260 formatting in our languages.
[SONARIAC-2085]: https://sonarsource.atlassian.net/browse/SONARIAC-2085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARIAC-2080 Modify rule S2260: add JSON and YAML

---

rules/S5899/python/rule.adoc

[SONARPY-3028](https://sonarsource.atlassian.net/browse/SONARPY-3028)
[SONARPY-3028]: https://sonarsource.atlassian.net/browse/SONARPY-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARPY-3028 update wording to include async test method

---

rules/S2068/json/metadata.json
rules/S2068/json/rule.adoc
rules/S2068/yaml/metadata.json
rules/S2068/yaml/rule.adoc

[SONARIAC-2099](https://sonarsource.atlassian.net/browse/SONARIAC-2099)
[SONARIAC-2099]: https://sonarsource.atlassian.net/browse/SONARIAC-2099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARIAC-2099 Modify rule S2068: add JSON/YAML languages

---

rules/S6781/csharp/rule.adoc

Modify S6781(C#): Align message with reality

---

rules/S6562/csharp/rule.adoc
rules/S6562/how-dotnet.adoc
rules/S6562/resources-dotnet.adoc
rules/S6562/vbnet/rule.adoc
rules/S6563/resources-dotnet.adoc

Modify S6562, S6563: Add DateOnly and fix formating issues

---

rules/S3649/vbnet/how-to-fix-it/entity-framework.adoc

Small change to have coherence between compliant and noncompliant example

Adjust S3649 non compliant example

---

rules/S2083/common/fix/code-rationale.adoc

A user thought that the point of the rule was partial path traversal, most probably by misreading the "pitfall" section. This tiny update aims to prevent this for future users.

Modify S2083(all): Add example user input for readability

---

rules/S1172/python/rule.adoc

S1172 fix non compliant example that wasn't raising

---

rules/S7630/githubactions/rule.adoc
rules/S7631/githubactions/rule.adoc
rules/S7633/githubactions/rule.adoc
rules/S7634/githubactions/rule.adoc
rules/S7635/githubactions/rule.adoc
rules/S7636/githubactions/rule.adoc
rules/S7637/githubactions/rule.adoc

[SONARIAC-2155](https://sonarsource.atlassian.net/browse/SONARIAC-2155)
[SONARIAC-2155]: https://sonarsource.atlassian.net/browse/SONARIAC-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARIAC-2155 Add implementation specification for githubactions

---

rules/S7315/secrets/rule.adoc

Modify rule S7315: use valid Palantir JWT

---

rules/S6096/go/how-to-fix-it/archive_zip.adoc

Modify S6096: Improve code examples for Go

---

rules/S7614/python/metadata.json

SONARPY-3313 Fix the metadata of S7614

---

.github/workflows/create_multiple_new_rspecs.yml
rspec-tools/rspec_tools/cli.py
rspec-tools/rspec_tools/create_rule.py
rspec-tools/rspec_tools/repo.py
rspec-tools/tests/test_create_rule.py
rspec-tools/tests/test_repo.py

[RIS-132](https://sonarsource.atlassian.net/browse/RIS-132)
[RIS-132]: https://sonarsource.atlassian.net/browse/RIS-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RIS-132 New github action to create multiple rules in one PR

---

rules/S6109/javascript/rule.adoc

Modify S6109(js): Make the rule LayC compliant

---

rules/S7674/shell/metadata.json
rules/S7679/shell/metadata.json
rules/S7688/shell/metadata.json
rules/S7689/shell/metadata.json

Update Shell rules with consistent severity

---

rules/S6383/terraform/rule.adoc

Modify rule S6383: update key vault argument

---

rules/S7794/ruby/metadata.json
rules/S7807/ruby/metadata.json
rules/S7809/ruby/metadata.json
rules/S7814/ruby/metadata.json
rules/S7815/ruby/metadata.json
rules/S7816/ruby/metadata.json
rules/S7817/ruby/metadata.json
rules/S7835/ruby/metadata.json
rules/S7836/ruby/metadata.json
rules/S7840/ruby/metadata.json
rules/S7841/ruby/metadata.json
rules/S7844/ruby/metadata.json
rules/S7849/ruby/metadata.json
rules/S7865/ruby/metadata.json
rules/S7867/ruby/metadata.json
rules/S7870/ruby/metadata.json
rules/S7872/ruby/metadata.json
rules/S7874/ruby/metadata.json
rules/S7875/ruby/metadata.json
rules/S7891/ruby/metadata.json
rules/S7895/ruby/metadata.json
rules/S7896/ruby/metadata.json
rules/S7897/ruby/metadata.json
rules/S7899/ruby/metadata.json
rules/S7904/ruby/metadata.json
rules/S7905/ruby/metadata.json
rules/S7907/ruby/metadata.json
rules/S7911/ruby/metadata.json
rules/S7916/ruby/metadata.json
rules/S7917/ruby/metadata.json

[SKUNK-613](https://sonarsource.atlassian.net/browse/SKUNK-613)
[SKUNK-613]: https://sonarsource.atlassian.net/browse/SKUNK-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SKUNK-613 Mark DRE Ruby rules as beta
