SonarSource/rspec

- Dockerfile
Tests require git and it was missing from the docker container.
> Fix tests by adding git in docker image

- README.adoc
Update of README following the update of Confluence (description of how to delete a rule was missing in the README)
> RULEAPI-623: Update README

- rspec-tools/tests/test_utils.py
I am sorry I forgot to add this test file in the previous PR. I understand your confusion regarding the tests now:)
> RULEAPI-640: missing file

- rules/S2259/javascript/rule.adoc
See https://github.com/SonarSource/SonarJS/issues/2670
> Update property used in S2259

- rules/S4604/java/metadata.json
> Deprecate rule S4604

- rules/S997/compliant.adoc
- rules/S997/description.adoc
- rules/S997/noncompliant.adoc
Associated implementation PR: https://github.com/SonarSource/sonar-cpp/pull/1434
> Modify rule S997: CPP-2396 Add exception for function definitions

- rules/S2201/java/rule.adoc
As implemented in SONARJAVA-3746
> Modify rule S1234: Amend list of supported methods for Java

- rules/S6290/description.adoc
- rules/S6290/recommended.adoc
- rules/S6290/secrets/metadata.json
- rules/S6290/secrets/rule.adoc
- rules/S6290/see.adoc
- rules/S6292/description.adoc
- rules/S6292/recommended.adoc
- rules/S6292/secrets/metadata.json
- rules/S6292/secrets/rule.adoc
- rules/S6292/see.adoc
Split rule description and fix OWASP category
> Update S6290 and S6292

- rules/S6342/php/metadata.json
See jira comment in https://jira.sonarsource.com/browse/SONARPHP-1207 for the why.
> Delete rule S6342

- rules/S3655/java/rule.adoc
Inspired from https://github.com/SonarSource/sonar-java/pull/3724.
> Modify rule S3655[java]: mention "isEmpty" and indirect access in code examples

- rules/S1235/cfamily/rule.adoc
No change in implementation, so the PR can be merge immediately.
> Modify rule S1235: The description was not describing C++ behavior (CPP-3236)

- rules/S1168/compliant.adoc
- rules/S1168/description.adoc
- rules/S1168/noncompliant.adoc
This PR has a sister PR here: https://github.com/SonarSource/sonar-java/pull/3791
> SONARJAVA-4000 Add suport of Maps in S1168

- rules/S6236/cfamily/rule.adoc
Following the explanation from @tomasz-kaminski-sonarsource, I tried to reformulate the rule description to be more understandable to me.
> Modify rule S6236: More accessible description

- rules/S4792/php/rule.adoc
Implementation ticket: [SONARPHP-1234](https://jira.sonarsource.com/browse/SONARPHP-1234)
> Modify rule S4792: Fix exceptions for error_reporting

- rules/S3260/csharp/message.adoc
- rules/S3260/csharp/metadata.json
- rules/S3260/csharp/rule.adoc
Modify rule S3260: Include also record types, since the rule is also valid for them.
> Modify rule S3260 

- rules/S5324/ask-yourself.adoc
- rules/S5324/description.adoc
- rules/S5324/java/rule.adoc
- rules/S5324/kotlin/rule.adoc
- rules/S5324/recommended.adoc
Implementation ticket: [SONARKT-68](https://jira.sonarsource.com/browse/SONARKT-68)
> Modify rule S5324: Add Kotlin support

- rules/S6291/java/rule.adoc
> Modify rule S6291[java]: Add Java examples

- frontend/src/deployment/pullRequestIndexing.ts
With the substantial increase of the number of new-rule PR, I couldn't `predeploy` the github page to be able to review #426 because github was throttling my anonymous API requests.
> Use GITHUB_TOKEN for PR crawler to escape GitHub API throttling

- frontend/package-lock.json
- frontend/package.json
- frontend/src/RulePage.tsx
- frontend/src/hljs-humanoid-light.css
Highlight the metadata displayed for the rule using highlight.js
> RULEAPI-700: Highlight the metadata JSON on the rule page

- rspec-tools/rspec_tools/create_rule.py
Fix the redirecting URL and raise an exception earlier to leave no unstaged changes when unwinding the stack during exception processing.
> Improve the failure experience of "add a language" GH Action

- rules/S1124/java/rule.adoc
This is already implemented, just docs were not updated.
Feedback from https://twitter.com/heinzkabutz/status/1443903763098521601?s=20
> Modify rule S1124: update docs to include default modifier

- frontend/src/utils/useRuleCoverage.ts
> Add comment for the rule coverage logic

- rules/S6300/java/rule.adoc
Related to ticket: https://jira.sonarsource.com/browse/SONARJAVA-4031
> Modify rule S6300[java]: Add Java examples

- rules/S2039/java/metadata.json
See https://jira.sonarsource.com/browse/SONARJAVA-4018
> Deprecate rule S2039 for java

- rules/S4507/ask-yourself.adoc
- rules/S4507/java/rule.adoc
- rules/S4507/kotlin/rule.adoc
- rules/S4507/recommended.adoc
Implementation tickets:
* https://jira.sonarsource.com/browse/SONARKT-165
* https://jira.sonarsource.com/browse/SONARJAVA-4034
> Modify rule S4507: Add Java/Kotlin examples for WebView

- rules/S5332/ask-yourself.adoc
- rules/S5332/java/rule.adoc
- rules/S5332/message.adoc
- rules/S5332/recommended.adoc
Ticket: [SONARJAVA-4039](https://jira.sonarsource.com/browse/SONARJAVA-4039)
> Modify rule S5332[java]: support Android WebView insecure mixed content policy

- rules/S1439/javascript/rule.adoc
Change Odd to Even based on community feedback: https://community.sonarsource.com/t/semantic-issue-in-javascript-sonarsource-explanation/51636
> Update S1439 Noncompliant Code

- rules/S1145/see.adoc
- rules/S1148/java/rule.adoc
- rules/S1279/cobol/rule.adoc
- rules/S1442/see.adoc
- rules/S1486/abap/rule.adoc
- rules/S1525/javascript/rule.adoc
- rules/S1628/rpg/rule.adoc
- rules/S1685/cobol/rule.adoc
- rules/S1951/flex/rule.adoc
- rules/S2653/java/rule.adoc
- rules/S4507/see.adoc
CWE entry name has change to "Active Debug Code"
https://cwe.mitre.org/data/definitions/489.html
> Update CWE-489 title

- rules/S5146/csharp/rule.adoc
- rules/S5146/java/rule.adoc
- rules/S5146/javascript/rule.adoc
- rules/S5146/php/rule.adoc
- rules/S5146/python/rule.adoc
Implementation ticket: [SONARSEC-2661](https://jira.sonarsource.com/browse/SONARSEC-2661)
> Modify rule S5146 - Support Location header

- rules/S6258/terraform/rule.adoc
Implementation Ticket : [SONARIAC-253](https://jira.sonarsource.com/browse/SONARIAC-253)
> Create rule S6258[terraform]: Add AWS Load Balancing

- rules/S6258/cloudformation/rule.adoc
Implementation ticket: [SONARIAC-255](https://jira.sonarsource.com/browse/SONARIAC-255)
> Create rule S6258[cloudformation]: Add AWS Load Balancing v2

- rules/S3923/javascript/metadata.json
- rules/S3923/metadata.json
- rules/S5693/javascript/metadata.json
- rules/S5693/metadata.json
Related to: https://github.com/SonarSource/rspec/pull/578
> Revert scope change for missed rules

- rules/S2665/cfamily/metadata.json
- rules/S2665/cfamily/rule.adoc
> S2665: CPP-1222 Align RSPEC with implementation

- README.adoc
- docs/testing.adoc
With the selected solution, there are no scripts to write; only the documentation needs to be updated.
I tried to keep only the relevant details. Hopefully, this is easily digestible and clear. Feedback welcome.
> RULEAPI-635: Document testing process

- rules/S5144/csharp/rule.adoc
- rules/S5144/java/rule.adoc
- rules/S5144/javascript/rule.adoc
- rules/S5144/php/rule.adoc
- rules/S5144/python/rule.adoc
Changed snippets of the samples for consistency between implementations and to avoid potential fix pitfalls.
Also, some readability changes for chunks of code (columns with the equal sign)
> Modify S5144: Improved code samples

- rules/S4423/metadata.json
- rules/S4423/terraform/metadata.json
Implementation ticket: https://jira.sonarsource.com/browse/SONARIAC-274
> Modify rule S4423: Add cloud tags

- rspec-tools/rspec_tools/validation/rule-metadata-schema.json
- rules/S1134/metadata.json
- rules/S1135/metadata.json
- rules/S1239/cfamily/metadata.json
- rules/S124/metadata.json
- rules/S1251/cfamily/metadata.json
- rules/S1256/cfamily/metadata.json
- rules/S1267/cfamily/metadata.json
- rules/S1272/cfamily/metadata.json
- rules/S1489/abap/metadata.json
- rules/S1490/abap/metadata.json
- rules/S1509/abap/metadata.json
- rules/S1681/cobol/metadata.json
- rules/S1914/cfamily/metadata.json
- rules/S2113/java/metadata.json
- rules/S2253/metadata.json
- rules/S2260/cfamily/metadata.json
- rules/S3417/xml/metadata.json
- rules/S3546/java/metadata.json
- rules/S3575/csharp/metadata.json
- rules/S3688/metadata.json
- rules/S3938/cobol/metadata.json
- rules/S4011/java/metadata.json
- rules/S4439/javascript/metadata.json
- rules/S5639/cfamily/metadata.json
- rules/S6212/java/metadata.json
This reverts commit ebfa8932d1bfbe10c4fde360a4ae9f367ff87d9a.
> Revert "RULEAPI-614: mark unpredictable remediation cost"

- frontend/src/SearchPage.style.ts
- frontend/src/SearchPage.tsx
- frontend/src/__tests__/__snapshots__/SearchPage.test.tsx.snap
> RULEAPI-731: Make the search bar more compact to leave room for the results

- frontend/src/deployment/index.ts
- rules/S5808/java/rule.adoc
This is something I've done a few days ago while testing SonarLint. Might as well share it.
To review it, ask GitHub to ignore whitespaces.
> Fix code smells in index.ts

- rules/S6323/php/rule.adoc
* You can preview this rule [here](https://sonarsource.github.io/rspec/#/rspec/S6323/php).
* Bugfix ticket: https://jira.sonarsource.com/browse/SONARPHP-1284
> Modify rule S6323: Fix exception for PHP

- LICENSE
A valid license is required for [compliance reasons](https://jira.sonarsource.com/browse/BUILD-1273).
Contact Release Engineering Team for more information.
> BUILD-1337: assign LGPL license

- rules/S1155/csharp/metadata.json
Already implemented https://github.com/SonarSource/sonar-dotnet/issues/4841
> Modify rule S1155: Add QuickFix C#

- rules/S4204/javascript/rule.adoc
Fixes https://github.com/SonarSource/SonarJS/issues/2940
> Modify rule S4204: Improve rule description

- rules/S1763/javascript/rule.adoc
Fixes https://github.com/SonarSource/SonarJS/issues/2919
> Modify rule S1763: Remove unsupported exceptions

- rules/S4328/javascript/rule.adoc
Fixes https://github.com/SonarSource/SonarJS/issues/2939
> Modify rule S4328: Clarify what kind of problems could arise

- rules/S4423/terraform/highlighting.adoc
- rules/S4423/terraform/message.adoc
- rules/S4423/terraform/metadata.json
- rules/S4423/terraform/rule.adoc
Ticket: [SONARIAC-345](https://jira.sonarsource.com/browse/SONARIAC-345)
Preview: [S4423](https://sonarsource.github.io/rspec/#/rspec/S4423/terraform)
> Modify rule S4423[terraform]:Add SSL policy for Google Cloud load balancers

- rules/S6385/highlighting.adoc
- rules/S6385/message.adoc
Ticket: [SONARIAC-378](https://jira.sonarsource.com/browse/SONARIAC-378)
> Modify rule S6383: Add secondary location

- rules/S3801/python/rule.adoc
Implementation ticket: [SONARPY-212](https://jira.sonarsource.com/browse/SONARPY-212)
> Modify rule S3801: adjust description for Python

- rules/S6385/message.adoc
[SONARIAC-378](https://jira.sonarsource.com/browse/SONARIAC-378)
> Modify rule S6385: update secondary location message

- rules/S3574/cfamily/highlighting.adoc
- rules/S3574/cfamily/message.adoc
- rules/S3574/cfamily/metadata.json
- rules/S3574/cfamily/rule.adoc
Relates to https://github.com/SonarSource/sonar-cpp/pull/1861
TODO:
> Modify rule S3574: Update rule and add Sonar Way quality profile

- rules/S6173/php/rule.adoc
Implementation ticket: https://jira.sonarsource.com/browse/SONARSEC-2866
> Modify Rule S6173: add php code samples

- rules/S6317/cloudformation/rule.adoc
- rules/S6317/description.adoc
- rules/S6317/highlighting.adoc
- rules/S6317/message.adoc
- rules/S6317/terraform/rule.adoc
Ticket: [SONARIAC-384](https://jira.sonarsource.com/browse/SONARIAC-384)
> Modify rule S6317: Add message, highlighting and the list of supported privilege escalation vector details

- rules/S3618/plsql/rule.adoc
- rules/S3641/plsql/rule.adoc
- rules/S3651/plsql/rule.adoc
> Fix PL/SQL broken links

- rules/S5131/common/pitfalls/content-types.adoc
- rules/S5131/php/laravel/rule.adoc
- rules/S5131/php/native/rule.adoc
- rules/S5131/php/symfony/rule.adoc
This is a draft for the Progressive Education Framework.
> Modify rule S5131: Add PHP text

- rules/S5131/python/dtl/rule.adoc
- rules/S5131/python/jinja/rule.adoc
I also experimented with putting the code examples in tables to better simulate diff views.
> Modify rule S5131: DTL autoescapeing globably disabled

- rules/S1158/java/message.adoc
- rules/S1158/java/metadata.json
- rules/S1158/java/rule.adoc
- rules/S2131/java/metadata.json
See https://jira.sonarsource.com/browse/SONARJAVA-4217.
> Deprecate S2131 and update S1158 description

- rules/S1121/java/rule.adoc
Note: I would not encourage this code, the purpose of this PR is to document the current behavior of the rule.
> Modify rule S1121: add example for relational expression

- rules/S3504/javascript/metadata.json
Implemented by https://github.com/SonarSource/rspec/pull/1008
> Modify rule S3504: Enable in SonarWay profile

- rules/S5852/see.adoc
> Modify rule S5852: replace the broken link

- rules/S6432/csharp/highlighting.adoc
- rules/S6432/csharp/message.adoc
- rules/S6432/csharp/rule.adoc
https://github.com/SonarSource/security-expected-issues/pull/717
> [APPSEC-25] Add CSharp specification to S6432

- rules/S1788/javascript/rule.adoc
add exception to rule S1788 (JS) rule for Redux reducers
> Modify rule S1788: Add exception for Redux reducers

- rules/S6263/java/message.adoc
- rules/S6263/java/metadata.json
- rules/S6263/java/rule.adoc
Add info about scope of rule and correct upper-case tag to be lower-case.
> Modify rule S6263: Add info about scope of rule and correct upper-case tag to be lower-case.

- rules/S6242/java/metadata.json
- rules/S6242/java/rule.adoc
Relates to SONARJAVA-4134.
* Set lower case aws tag
* Fix text formatting issue
> Modify rule S6242

- rules/S5838/java/rule.adoc
This PR polishes `rule.adoc` for S5838 a bit.
> Modify rule S5838: Polish the rule.adoc

- docs/allowed_framework_names.adoc
- rules/S2083/common/fix/code-rationale.adoc
- rules/S2083/common/fix/how-does-this-work.adoc
- rules/S2083/csharp/how-to-fix-it/dotnet.adoc
- rules/S2083/csharp/rule.adoc
- rules/S2083/java/how-to-fix-it/java-se.adoc
Specification ticket: [APPSEC-49](https://sonarsource.atlassian.net/browse/APPSEC-49)
> Modify rule S2083[C#]: Educational content (APPSEC-49)

- rules/S3358/javascript/rule.adoc
Modify rule S3358: Add an exception for JSX expressions.
> Modify rule S3358: Add an exception for JSX expressions.

- rules/S1116/javascript/message.adoc
- rules/S1116/javascript/rule.adoc
Modify rule S1116: Add exception paragraph
> Modify rule S1116: Add exception paragraph

- rules/S1172/javascript/metadata.json
Fixes SonarSource/SonarJS#3243
> Modify rule S1172: Remove rule from the profile "Sonar way".

- rules/S5146/csharp/how-to-fix-it/dotnet.adoc
Specification ticket: [APPSEC-58](https://sonarsource.atlassian.net/browse/APPSEC-58).
> [APPSEC-58] Modify rule S5146: Educational content (C#)

- rules/S3317/javascript/metadata.json
Fixes SonarSource/SonarJS#3291
> Modify rule s3317: Remove rule from the profile "Sonar way".

- rules/S5146/common/fix/code-rationale.adoc
- rules/S5146/common/fix/how-does-this-work.adoc
- rules/S5146/common/resources/standards.adoc
- rules/S5146/csharp/how-to-fix-it/dotnet.adoc
- rules/S5146/csharp/rule.adoc
- rules/S5146/java/how-to-fix-it/java-se.adoc
- rules/S5146/java/rule.adoc
Specification ticket: [APPSEC-59](https://sonarsource.atlassian.net/browse/APPSEC-59).
> [APPSEC-59] Modify rule S5146: Educational content (Java)

- rules/S5883/common/fix/introduction.adoc
- rules/S5883/common/fix/sanitize-meta-characters.adoc
- rules/S5883/csharp/how-to-fix-it/dotnet.adoc
- rules/S5883/csharp/rule.adoc
Specification ticket: [APPSEC-61](https://sonarsource.atlassian.net/browse/APPSEC-61).
> Modify Rule S5883(C#): Education Framework (APPSEC-61)

- docs/allowed_framework_names.adoc
- rules/S2076/common/fix/code-rationale.adoc
- rules/S2076/common/fix/how-does-this-work.adoc
- rules/S2076/csharp/how-to-fix-it/dotnet.adoc
- rules/S2076/csharp/rule.adoc
- rules/S2076/java/how-to-fix-it/apache-commons.adoc
- rules/S2076/java/how-to-fix-it/java-se.adoc
- rules/S2076/java/rule.adoc
Specification ticket: [APPSEC-56](https://sonarsource.atlassian.net/browse/APPSEC-56).
> [APPSEC-56] Modify rule S2076: Educational content (Java)

- rules/S5899/python/highlighting.adoc
- rules/S5899/python/message.adoc
- rules/S5899/python/metadata.json
- rules/S5899/python/rule.adoc
Related to [JIRA ticket](https://sonarsource.atlassian.net/browse/SONARPY-758) and [RSPEC](https://sonarsource.atlassian.net/browse/RSPEC-5899)
> Modify rule S5899: Add python as covered language

- rules/S2076/common/fix/sanitize-meta-characters.adoc
- rules/S2076/csharp/how-to-fix-it/dotnet.adoc
- rules/S2076/java/how-to-fix-it/apache-commons.adoc
- rules/S2076/java/how-to-fix-it/java-se.adoc
The "sanitize" guideline has been wrongfully deleted from this folder.
> Modify S2076(education): Add common text

- rules/S6096/common/fix/code-rationale.adoc
- rules/S6096/common/fix/how-does-this-work.adoc
- rules/S6096/csharp/how-to-fix-it/dotnet.adoc
- rules/S6096/csharp/rule.adoc
Specification ticket: [APPSEC-73](https://sonarsource.atlassian.net/browse/APPSEC-73).
> [APPSEC-73] Modify rule S6096: Educational content (C#)

- rules/S5145/common/fix/code-rationale.adoc
- rules/S5145/common/fix/how-does-this-work.adoc
- rules/S5145/csharp/how-to-fix-it/dotnet.adoc
- rules/S5145/csharp/rule.adoc
- rules/S5145/java/how-to-fix-it/java-se.adoc
- rules/S5145/java/rule.adoc
- rules/S6096/common/fix/code-rationale.adoc
- rules/S6096/common/fix/how-does-this-work.adoc
- rules/S6096/csharp/how-to-fix-it/dotnet.adoc
- rules/S6096/csharp/rule.adoc
Specification ticket: [APPSEC-85](https://sonarsource.atlassian.net/browse/APPSEC-85).
> [APPSEC-85] Modify rule S5145: Educational content (Java)

- rules/S5147/common/fix/dangerous-operators.adoc
- rules/S5147/common/fix/pre-approved-list.adoc
- rules/S5147/common/fix/validation.adoc
- rules/S5147/common/resources/articles.adoc
- rules/S5147/common/resources/standards.adoc
- rules/S5147/impact.adoc
- rules/S5147/rationale.adoc
Related to [**APPSEC-94**](https://sonarsource.atlassian.net/browse/APPSEC-94).
> Modify S5147(Common text): Update to the education framework (APPSEC-94)

- rules/S2091/common/fix/validation.adoc
- rules/S2091/common/resources/articles.adoc
- rules/S2091/common/resources/standards.adoc
- rules/S2091/impact.adoc
- rules/S2091/rationale.adoc
Related to [APPSEC-98](https://sonarsource.atlassian.net/browse/APPSEC-98).
> Modify S2091(Common text): Update to the education framework (APPSEC-98)

- rules/S2091/java/how-to-fix-it/java-se.adoc
- rules/S2091/java/rule.adoc
Related to [APPSEC-99](https://sonarsource.atlassian.net/browse/APPSEC-99).
> Modify rule S2091(Java): Add Educational content (APPSEC-99)

- rules/S2259/csharp/rule.adoc
- rules/S2259/vbnet/rule.adoc
Related to https://github.com/SonarSource/sonar-dotnet/issues/5861
> Rule S2259: Add VB.NET, improve C#

- rules/S3353/csharp/rule.adoc
Part of SonarSource/sonar-dotnet/issues/5868
> Modify rule S3353: Add sample with "var" and interpolated string replacements

- rules/S6287/java/how-to-fix-it/java-se.adoc
- rules/S6287/java/rule.adoc
Specification ticket: [APPSEC-119](https://sonarsource.atlassian.net/browse/APPSEC-119).
> [APPSEC-119] Modify rule S6287: Educational content (Java)

- rules/S6287/csharp/how-to-fix-it/dotnet.adoc
- rules/S6287/csharp/rule.adoc
Specification ticket: [APPSEC-120](https://sonarsource.atlassian.net/browse/APPSEC-120).
> [APPSEC-120] Modify rule S6287: Educational content (C#)

- rules/S6096/java/how-to-fix-it/java-se.adoc
- rules/S6096/java/rule.adoc
[APPSEC-72](https://sonarsource.atlassian.net/browse/APPSEC-72)
> Modify rule S6096: Educational content (Java) (APPSEC-72)

- rules/S2076/metadata.json
- rules/S2078/metadata.json
- rules/S2083/metadata.json
- rules/S2091/metadata.json
- rules/S2631/metadata.json
- rules/S3649/metadata.json
- rules/S5135/metadata.json
- rules/S5144/metadata.json
- rules/S5145/metadata.json
- rules/S5146/metadata.json
- rules/S5147/metadata.json
- rules/S5334/metadata.json
- rules/S5883/metadata.json
- rules/S6096/metadata.json
- rules/S6287/metadata.json
Related to [**APPSEC-129**](https://sonarsource.atlassian.net/browse/APPSEC-129).
> Modify All Current Education Rules: Add Security Principles

- rules/S4423/cloudformation/rule.adoc
- rules/S4423/terraform/rule.adoc
Updated rules description for [CloudFormation](https://sonarsource.github.io/rspec/#/rspec/S4423/cloudformation) and [Terraform](https://sonarsource.github.io/rspec/#/rspec/S4423/terraform) to avoid duplicated See section.
> Modify S4423: Fix See section for CF and TF

- rules/S2083/common/fix/how-does-this-work.adoc
- rules/S2083/common/pitfalls/partial-path-traversal.adoc
- rules/S2083/csharp/how-to-fix-it/dotnet.adoc
- rules/S2083/java/how-to-fix-it/java-se.adoc
- rules/S6096/common/pitfalls/partial-path-traversal.adoc
- rules/S6096/csharp/how-to-fix-it/dotnet.adoc
- rules/S6096/java/how-to-fix-it/java-se.adoc
- rules/S6252/terraform/rule.adoc
Related to [**APPSEC-68**](https://sonarsource.atlassian.net/browse/APPSEC-68).
> Modify S2083&S6096(Education): Add Partial Path Traversal to pitfalls

- rules/S6287/metadata.json
Related to [**APPSEC-132**](https://sonarsource.atlassian.net/browse/APPSEC-123).
> Modify S6287: Severity and Title (APPSEC-123)

- rules/S6258/terraform/rule.adoc
[APPSEC-35](https://sonarsource.atlassian.net/browse/APPSEC-35).
> Modify Rule S6258(IAC): Remove azurerm_storage_account mentions

- rules/S2068/java/rule.adoc
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARJAVA-4278
> Modify rule S2068: Adjust samples to new rule behavior

- rules/S5332/python/highlighting.adoc
- rules/S5332/python/message.adoc
- rules/S5332/python/rule.adoc
- rules/S5332/recommended.adoc
- rules/S5332/see.adoc
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARPY-1119
> Modify rule S5332: Adding AWS CDK support for the Python language

- rules/S4423/python/message.adoc
- rules/S4423/python/rule.adoc
Specification ticket: [APPSEC-103](https://sonarsource.atlassian.net/browse/APPSEC-103)
Implementation ticket: [SONARPY-1127](https://sonarsource.atlassian.net/browse/SONARPY-1127)
Preview: [S4423](https://sonarsource.github.io/rspec/#/rspec/S4423/python)
> Modify S4423[Python]: Support of AWS CDK code (APPSEC-103)

- rules/S4828/ask-yourself.adoc
- rules/S4828/description.adoc
- rules/S4828/metadata.json
- rules/S4828/php/rule.adoc
- rules/S4828/python/rule.adoc
- rules/S4828/recommended.adoc
- rules/S4828/see.adoc
Related to [**APPSEC-131**](https://sonarsource.atlassian.net/browse/APPSEC-131).
> Modify S4828: Clarify recommendations

- rules/S1192/php/rule.adoc
> Modify rule S1192: Remove artifact

- rules/S103/javascript/metadata.json
- rules/S105/javascript/metadata.json
- rules/S1105/javascript/metadata.json
- rules/S1110/javascript/metadata.json
- rules/S1116/javascript/metadata.json
- rules/S113/javascript/metadata.json
- rules/S1131/javascript/metadata.json
- rules/S122/javascript/metadata.json
- rules/S139/javascript/metadata.json
- rules/S1438/javascript/metadata.json
- rules/S1441/javascript/metadata.json
- rules/S1537/javascript/metadata.json
- rules/S3723/javascript/metadata.json
- rules/S3972/javascript/metadata.json
- rules/S3973/javascript/metadata.json
Fixes https://github.com/SonarSource/SonarJS/issues/3441
> Deprecate Formatting rules for JavaScript

- rules/S2222/csharp/description.adoc
- rules/S2222/csharp/metadata.json
- rules/S2222/metadata.json
- rules/S2222/vbnet/description.adoc
Changes based on the discussion in
https://discuss.sonarsource.com/t/10639
> Modify rule S2222:  Improve rule description

- rules/S2225/vbnet/metadata.json
- rules/S2225/vbnet/rule.adoc
See https://github.com/SonarSource/sonar-dotnet/pull/5741
> Modify rule S2225: Add VB.NET

- rules/S5332/javascript/highlighting.adoc
- rules/S5332/javascript/message.adoc
- rules/S5332/javascript/rule.adoc
Implementation: [Kinesis](https://github.com/SonarSource/SonarJS/issues/3456), [ECache](https://github.com/SonarSource/SonarJS/issues/3457), [ELB](https://github.com/SonarSource/SonarJS/issues/3458), [ELBv2](https://github.com/SonarSource/SonarJS/issues/3459)
RSPEC: https://github.com/SonarSource/rspec/pull/1317
Specification ticket: [APPSEC-159](https://sonarsource.atlassian.net/browse/APPSEC-159)
> Modify rule S5332[javascript]: Using clear-text protocols is security-sensitive

- rules/S3972/javascript/metadata.json
Fixes https://github.com/SonarSource/SonarJS/issues/3488
> Undeprecate rule S3972

- rules/S5348/pli/highlighting.adoc
- rules/S5348/pli/message.adoc
- rules/S5348/pli/rule.adoc
[SONARPLI-236](https://sonarsource.atlassian.net/browse/SONARPLI-236)
> Modify S5348: Update description, message and highlighting to match the rule implementation

- rules/S6304/javascript/metadata.json
Fixes https://github.com/SonarSource/SonarJS/pull/3524
S6304 has some FP identified that will be fixed as part of [APPSEC-219](https://sonarsource.atlassian.net/browse/APPSEC-219)
> Modify rule S6304: Remove from the Sonar way profile

- rules/S6252/terraform/rule.adoc
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARIAC-419
> Modify rule S6252: Add new Terraform code sample

- rules/S6255/terraform/rule.adoc
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARIAC-416
> Modify rule S6255: Add new Terraform code sample

- rules/S6304/exceptions.adoc
Specification ticket: [APPSEC-219](https://sonarsource.atlassian.net/browse/APPSEC-219)
Implementation tickets: [SONARPY-1193](https://sonarsource.atlassian.net/browse/SONARPY-1193), [SonarJS#3543](https://github.com/SonarSource/SonarJS/issues/3543), [SONARIAC-440](https://sonarsource.atlassian.net/browse/SONARIAC-440)
> Modify rule S6304: update exceptions

- rules/S1100/html/metadata.json
Related to [SONARHTML-157](https://sonarsource.atlassian.net/browse/SONARHTML-157)
> Deprecate rule S1100

- rules/S1155/cfamily/rule.adoc
Related to CPP-3330 & https://github.com/SonarSource/sonar-cpp/pull/2267.
> Modify rule C1155: Cover usages of length()

- rules/S5542/kotlin/highlighting.adoc
- rules/S5542/kotlin/message.adoc
- rules/S5542/kotlin/rule.adoc
Specification ticket: [APPSEC-30](https://jira.sonarsource.com/browse/APPSEC-30)
Implementation ticket: [SONARKT-208](https://jira.sonarsource.com/browse/SONARKT-208)
Preview: [S5542](https://sonarsource.github.io/rspec/#/rspec/S5542)
> Modify rule S5542[kotlin]: Detect CBC mode when used with padding (APPSEC-30)

- rules/S5270/cfamily/metadata.json
- rules/S5270/cfamily/rule.adoc
Related to CPP-3733 & SonarSource/sonar-cpp#2284.
> Modify rule S5270: Improve rule precision

- rules/S6480/javascript/metadata.json
Fixes https://github.com/SonarSource/SonarJS/issues/3614
> Modify rule S6480: Remove it from the "Sonar way" default profile

- rules/S1527/description.adoc
Relates to https://github.com/SonarSource/SonarJS/issues/2990
> Modify rule S1527: Add mention about why we keep adopted future reserved words

- rules/S6472/docker/rule.adoc
Relevant APPSEC ticket: [APPSEC-346](https://sonarsource.atlassian.net/browse/APPSEC-346)
[APPSEC-346]: https://sonarsource.atlassian.net/browse/APPSEC-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify S6472: update code example to be more descriptive

- docs/allowed_framework_names.adoc
- rules/S6398/common/fix/casting.adoc
- rules/S6398/common/fix/code-rationale.adoc
- rules/S6398/common/fix/introduction.adoc
- rules/S6398/common/fix/object.adoc
- rules/S6398/common/resources/docs.adoc
- rules/S6398/common/resources/standards.adoc
- rules/S6398/description.adoc
- rules/S6398/impact.adoc
- rules/S6398/java/how-to-fix-it/fasterxml.adoc
- rules/S6398/java/how-to-fix-it/gson.adoc
- rules/S6398/java/how-to-fix-it/java-se.adoc
- rules/S6398/java/rule.adoc
- rules/S6398/rationale.adoc
- rules/S6398/see.adoc
Specification ticket: [APPSEC-426](https://sonarsource.atlassian.net/browse/APPSEC-426)
[APPSEC-426]: https://sonarsource.atlassian.net/browse/APPSEC-426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S6398: Switch text to progressive education format (APPSEC-426)

- rules/S6477/javascript/metadata.json
- rules/S6478/javascript/metadata.json
- rules/S6479/javascript/metadata.json
- rules/S6480/javascript/metadata.json
- rules/S6481/javascript/metadata.json
- rules/S6486/javascript/metadata.json
Fixes SonarSource/SonarJS#3677
> Modify rules MMF-2854: Update scopes from All to Main

- rules/S1699/cfamily/metadata.json
- rules/S1699/cfamily/rule.adoc
Remove some lies   from the description
Add advice about factory, and link to C++ core guidelines
CPP-4071
> Modify rule S1699 Rewrite the RSPEC to use C++ vocabulary

- rules/S3937/noncompliant.adoc
Related to https://github.com/SonarSource/sonar-dotnet/pull/6762
> Modify rule S3937: Add missing semicolon

- rules/S4433/description.adoc
- rules/S4433/see.adoc
Point it to an internet archive version
> Modify S4433: fix the broken link

- rules/S6437/docker/description.adoc
- rules/S6437/docker/rule.adoc
Specification Ticket: [APPSEC-458](https://sonarsource.atlassian.net/browse/APPSEC-458)
Implementation Ticket: [SONARIAC-610](https://sonarsource.atlassian.net/browse/SONARIAC-610)
[APPSEC-458]: https://sonarsource.atlassian.net/browse/APPSEC-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARIAC-610]: https://sonarsource.atlassian.net/browse/SONARIAC-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S6437: Add Docker (APPSEC-458)

- docs/asciidoc_dos_and_donts.adoc
- docs/asciidoc_faq.adoc
As discussed with @arseniy-sonar, this initiates a document for AsciiDoc format "gotchas".
> AsciiDoc Dos & Don'ts

- rules/S6470/implementation.adoc
https://sonarsource.atlassian.net/browse/SONARIAC-516
> Modify rule S6470(Docker): Improve message

- rules/S4275/javascript/rule.adoc
Fixes SonarSource/SonarJS#3759
> Modify rule S4275: Update code samples

- rules/S2222/csharp/rule.adoc
- rules/S2222/description-dotnet.adoc
- rules/S2222/vbnet/description.adoc
- rules/S2222/vbnet/rule.adoc
Update description as proposed here by @ganncamp :
https://discuss.sonarsource.com/t/c-lock-release-rule-description-seems-to-skip-some-steps/10639/14
> Modify rule S2222: Update description

- rules/S2245/metadata.json
- rules/S3329/metadata.json
- rules/S4423/metadata.json
- rules/S4426/metadata.json
- rules/S4507/xml/metadata.json
- rules/S4790/metadata.json
- rules/S4830/metadata.json
- rules/S5320/metadata.json
- rules/S5322/metadata.json
- rules/S5324/metadata.json
- rules/S5332/metadata.json
- rules/S5527/metadata.json
- rules/S5542/metadata.json
- rules/S5547/metadata.json
- rules/S5604/xml/metadata.json
- rules/S6288/metadata.json
- rules/S6291/metadata.json
- rules/S6293/metadata.json
- rules/S6300/metadata.json
- rules/S6301/metadata.json
- rules/S6358/xml/metadata.json
- rules/S6359/metadata.json
- rules/S6361/xml/metadata.json
https://sonarsource.atlassian.net/browse/APPSEC-513
> Modify rules: Remove `owasp-mX` tags

- rspec-tools/rspec_template/multi_language/language_specific/rule.adoc
- rspec-tools/rspec_template/single_language/language_specific/rule.adoc
See https://github.com/SonarSource/rspec/blob/master/docs/description.adoc#diff-view
> Add diff view properties to new rule templates

- rules/S3900/csharp/highlighting.adoc
- rules/S3900/csharp/message.adoc
- rules/S3900/csharp/rule.adoc
https://github.com/SonarSource/sonar-dotnet/issues/2643
> S3900: Update rule description and message

- rules/S6500/description.adoc
- rules/S6500/implementation.adoc
- rules/S6500/metadata.json
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARIAC-731
AppSec ticket: https://sonarsource.atlassian.net/browse/APPSEC-624
> Modify rule S6500: Adjust title and wording

- rules/S2612/docker/ask-yourself.adoc
- rules/S2612/docker/message.adoc
- rules/S2612/docker/rule.adoc
Implementation ticket: [SONARIAC-734](https://sonarsource.atlassian.net/browse/SONARIAC-734)
AppSec ticket: [APPSEC-621](https://sonarsource.atlassian.net/jira/software/c/projects/APPSEC/boards/2?modal=detail&selectedIssue=APPSEC-621)
[APPSEC-621]: https://sonarsource.atlassian.net/browse/APPSEC-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARIAC-734]: https://sonarsource.atlassian.net/browse/SONARIAC-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S2612: Change the message for docker related permission issues. (APPSEC-621)

- rules/S6570/docker/rule.adoc
Preview: [S6570](https://sonarsource.github.io/rspec/#/rspec/S6570/docker)
> Modify rule S6570: Change description to avoid duplication

- rules/S1135/docker/rule.adoc
- rules/S6437/docker/rule.adoc
- rules/S6472/docker/rule.adoc
- rules/S6570/docker/rule.adoc
- rules/S6573/docker/rule.adoc
- rules/S6584/docker/rule.adoc
- rules/S6589/docker/rule.adoc
Add RUN prefix in case of shell execution
Improve code highlighting
> Small fixes in Docker rules

- rules/S6437/docker/rule.adoc
Implementation ticket: [SONARIAC-743](https://sonarsource.atlassian.net/browse/SONARIAC-743)
AppSec ticket: [APPSEC-628](https://sonarsource.atlassian.net/browse/APPSEC-628)
[APPSEC-628]: https://sonarsource.atlassian.net/browse/APPSEC-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARIAC-743]: https://sonarsource.atlassian.net/browse/SONARIAC-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S6437: Change the issue message for Docker and secret generation (APPSEC-628)

- rules/S6506/docker/highlighting.adoc
- rules/S6506/docker/rule.adoc
- rules/S6506/message.adoc
- rules/S6506/recommended.adoc
- rules/S6506/see.adoc
Implementation ticket: [SONARIAC-750](https://sonarsource.atlassian.net/browse/SONARIAC-750)
[SONARIAC-750]: https://sonarsource.atlassian.net/browse/SONARIAC-750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S6506: Add examples for wget

- rules/S2871/javascript/metadata.json
- rules/S2871/javascript/rule.adoc
This goes with https://github.com/SonarSource/SonarJS/pull/3873. `toSorted()` is a new, copying method for arrays that otherwise behaves the same as `sort()`.
> Modify rule S2871: Add Array.toSorted()

- rules/S4423/azureresourcemanager/highlighting.adoc
- rules/S4423/azureresourcemanager/message.adoc
- rules/S4423/azureresourcemanager/metadata.json
- rules/S4423/azureresourcemanager/rule.adoc
[Specification ticket](https://sonarsource.atlassian.net/browse/SONARIAC-755)
[Implementation ticket](https://sonarsource.atlassian.net/browse/SONARIAC-781)
[RSPEC Preview](https://sonarsource.github.io/rspec/#/rspec/S4423/azureresourcemanager)
Bicep PR for S4423: #1879
> Create rule S4423: add language AzureResourceManager

- rules/S4043/javascript/rule.adoc
Also updates `var` to `const`.
> Modify rule S4043: suggest ES2023 `Array.toReversed()` and `Array.toSorted()` functions

- frontend/src/deployment/pullRequestIndexing.ts
The result is automatically paginated if the number is greater than the maximum per_page count, which is 100.
> Propery handle situation when there is more than 100 PRs

- rules/S6329/azureresourcemanager/highlight.adoc
- rules/S6329/azureresourcemanager/message.adoc
- rules/S6329/azureresourcemanager/metadata.json
- rules/S6329/azureresourcemanager/rule.adoc
Research ticket: https://sonarsource.atlassian.net/browse/SONARIAC-754
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARIAC-790
> Modify rule S6329: Add language AzureResourceManager (JSON)

- rules/S1155/php/rule.adoc
Related discuss thread https://community.sonarsource.com/t/unclear-scope-of-rspec-1155/90909
> Modify rule S1155: Migrate to new educational format

- .cirrus.yml
This was forgotten in e6ca2653ca7145ee71ddd37bac3ff6def7f69e81
> Remove unused gcp_credentials

- rules/S3949/csharp/metadata.json
- rules/S3949/csharp/rule.adoc
- rules/S3949/description.adoc
- rules/S3949/java/rule.adoc
- rules/S3949/rspecator.adoc
- rules/S3949/rule.adoc
- rules/S3949/swift/rule.adoc
- rules/S3949/vbnet/rule.adoc
Fixes https://github.com/SonarSource/sonar-dotnet/issues/7139
> Modify rule S3949: Remove CBDE from C#, add VB.NET

- rules/S6613/csharp/metadata.json
https://github.com/SonarSource/sonar-dotnet/pull/7250
> Modify rule S6613: quickfix covered

- rules/S3464/csharp/rule.adoc
- rules/S3464/description.adoc
- rules/S3464/metadata.json
- rules/S3464/resources.adoc
- rules/S3464/vbnet/rule.adoc
RSpec: https://sonarsource.github.io/rspec/#/rspec/S3464
> Modify rule S3464: LaYC format

- rules/S3060/csharp/metadata.json
- rules/S3060/csharp/rule.adoc
Adapts the [rule](https://sonarsource.github.io/rspec/#/rspec/S3060) to LaYC format level 2, for csharp.
> Modify rule S3060: LaYC format

- .github/pull_request_template.md
- README.adoc
- rspec-tools/rspec_tools/create_rule.py
This PR adds a small checklist for new PRs that will make it more visible what parts of the RSPEC were reviewed.
> Add review checklist

- rules/S6232/cfamily/metadata.json
- rules/S6232/cfamily/rule.adoc
Also using LaYC format for specialized examples
> Modify rule S6232: CPP-3254 Well defined alternatives to union type-punning

- rules/S3600/csharp/rule.adoc
> Modify S3600: Migrate it to the Learn-As-You-Code

- rules/S2068/java/rule.adoc
> Modify S2068: Fix Typo

- rules/S3904/csharp/metadata.json
- rules/S3904/csharp/rule.adoc
- rules/S3904/description.adoc
- rules/S3904/highlighting.adoc
- rules/S3904/message.adoc
- rules/S3904/metadata.json
- rules/S3904/resources.adoc
- rules/S3904/rspecator.adoc
- rules/S3904/see.adoc
- rules/S3904/vbnet/metadata.json
- rules/S3904/vbnet/rule.adoc
- rules/S3904/why.adoc
https://sonarsource.github.io/rspec/#/rspec/S3904/csharp
> S3904: Migrate to layc level 2

- rules/S3451/csharp/rule.adoc
- rules/S3451/rspecator.adoc
Description:
Adapts the [rule](https://sonarsource.github.io/rspec/#/rspec/S3451) to LaYC format level 2, for csharp.
> Modify rule S3451: LaYC format

- rules/S2187/csharp/rule.adoc
> Modify rule S2187: Improve title format

- rules/S2060/java/metadata.json
- rules/S2060/java/rule.adoc
> Modify rule S2060(Java): Update rule according to the LayC

- rules/S2222/csharp/rule.adoc
- rules/S2222/vbnet/rule.adoc
> Modify rule S2222: Update code examples diff type

- rules/S2055/java/metadata.json
- rules/S2055/java/rule.adoc
> Modify rule S2055(Java): Update rule according to the LayC

- rules/S3871/csharp/rule.adoc
- rules/S3871/exceptions.adoc
- rules/S3871/metadata.json
- rules/S3871/resources-dotnet.adoc
- rules/S3871/see.adoc
- rules/S3871/vbnet/rule.adoc
- rules/S3871/why-dotnet.adoc
> Modify rule S3871: Update to LaYC 

- rules/S2437/csharp/rule.adoc
- rules/S2437/java/rule.adoc
- rules/S2437/rspecator.adoc
- rules/S2437/vbnet/rule.adoc
> Modify rule S2437: fix VB.NET links and rspecator

- rules/S3451/csharp/rule.adoc
> Modify rule S3451: fix non-compliant block

- rules/S2692/csharp/rule.adoc
- rules/S2692/vbnet/rule.adoc
> Modify rule S2692: fix non-compliant code example

- rules/S3217/csharp/rule.adoc
Minor cleanup after validation
> Modify rule S3217: Adapt to LaYC

- rules/S1144/csharp/rspecator.adoc
- rules/S1144/csharp/rule.adoc
> Modify rule S1144: LaYC format

- rules/S4277/csharp/rule.adoc
- rules/S4277/description.adoc
- rules/S4277/highlighting.adoc
- rules/S4277/message.adoc
- rules/S4277/metadata.json
- rules/S4277/resources-dotnet.adoc
- rules/S4277/rspecator.adoc
- rules/S4277/vbnet/rule.adoc
- rules/S4277/why-dotnet.adoc
> Modify rule S4277: Update to LaYC

- rules/S4583/csharp/rule.adoc
- rules/S4583/description.adoc
- rules/S4583/highlighting.adoc
- rules/S4583/message.adoc
- rules/S4583/metadata.json
- rules/S4583/resources-dotnet.adoc
- rules/S4583/rspecator.adoc
- rules/S4583/see.adoc
- rules/S4583/vbnet/rule.adoc
- rules/S4583/why-dotnet.adoc
> Modify rule S4583: Update to LaYC

- rules/S2290/csharp/rule.adoc
- rules/S2290/rspecator.adoc
> Modify rule S2290: Update to LaYC

- rules/S3464/csharp/rule.adoc
- rules/S3464/vbnet/rule.adoc
> Modify rule S3464: fix code example

- rules/S3655/csharp/rule.adoc
- rules/S3655/rspecator-dotnet.adoc
- rules/S3655/vbnet/rule.adoc
> Modify rule S3655: LaYC format

- rules/S2114/csharp/rule.adoc
- rules/S2114/metadata.json
https://sonarsource.github.io/rspec/#/rspec/S2114/csharp
> Modify rule S2114: LaYC format

- rules/S1117/cfamily/rule.adoc
- rules/S1117/csharp/metadata.json
- rules/S1117/csharp/rule.adoc
- rules/S1117/description.adoc
- rules/S1117/flex/rule.adoc
- rules/S1117/highlighting.adoc
- rules/S1117/java/rule.adoc
- rules/S1117/javascript/rule.adoc
- rules/S1117/message.adoc
- rules/S1117/php/rule.adoc
- rules/S1117/plsql/rule.adoc
- rules/S1117/rspecator.adoc
- rules/S1117/swift/rule.adoc
- rules/S1117/why.adoc
> Modify rule S1117: Update to LaYC

- rules/S3464/vbnet/rule.adoc
> Modify rule S3464: fix VB.NET code example

- rules/S1110/abap/rule.adoc
- rules/S1110/apex/rule.adoc
- rules/S1110/cfamily/rule.adoc
- rules/S1110/cobol/rule.adoc
- rules/S1110/csharp/rule.adoc
- rules/S1110/go/rule.adoc
- rules/S1110/java/rule.adoc
- rules/S1110/javascript/rule.adoc
- rules/S1110/kotlin/rule.adoc
- rules/S1110/php/rule.adoc
- rules/S1110/plsql/rule.adoc
- rules/S1110/python/rule.adoc
- rules/S1110/rspecator.adoc
- rules/S1110/ruby/rule.adoc
- rules/S1110/scala/rule.adoc
- rules/S1110/swift/rule.adoc
- rules/S1110/tsql/rule.adoc
- rules/S1110/vbnet/metadata.json
- rules/S1110/vbnet/rule.adoc
> Modify rule S1110: fix Update dotnet part of the rule to LayC

- rules/S2583/csharp/metadata.json
- rules/S2583/csharp/rule.adoc
- rules/S2583/description.adoc
- rules/S2583/metadata.json
- rules/S2583/see.adoc
[S2583](https://sonarsource.github.io/rspec/#/rspec/S2583/csharp)
> Modify rule S2583: LaYC format

- rules/S4158/vbnet/rule.adoc
> Modify rule S4158: Fix vb.net compliant solution formatting

- rules/S2445/java/rule.adoc
> Modify rule S2445: Fix java diff tag

- rules/S4487/csharp/rule.adoc
> Modify rule S4487: fix missing space in code example

- rules/S3966/csharp/rule.adoc
- rules/S3966/vbnet/rule.adoc
> Modify rule S3966: Separate examples

- rules/S4635/csharp/metadata.json
- rules/S4635/csharp/rule.adoc
- rules/S4635/rspecator-dotnet.adoc
> Modify rule S4635: Update title

- rules/S4487/csharp/rule.adoc
> Modify rule S4487: fix code example

- rules/S122/csharp/rule.adoc
> Modify rule S122: Add resources section

- rules/S6325/javascript/rule.adoc
> layc-s6325-js

- rules/S3735/javascript/rule.adoc
> layc-s3735-js

- rules/S2925/csharp/rule.adoc
- rules/S2925/vbnet/rule.adoc
> S2925: Fix typos

- rules/S6640/csharp/rule.adoc
Modify rule S6640: Make code samples follow code conventions
> S6640 - Make code samples follow code conventions

- rules/S6640/csharp/metadata.json
Modify rule S6640: Set quickfix field to infeasible
> S6640: Set quickfix to infeasible

- rules/S1475/cobol/rule.adoc
> Modify rule S1475: Fixed typo in implementation message

- rules/S6325/javascript/rule.adoc
- rules/S6477/javascript/metadata.json
- rules/S6477/javascript/rule.adoc
> Modify rule S6477: Adapt to LaYC

- rules/S2761/python/rule.adoc
> Modify rule S2761: fix typo

- rules/S4830/php/how-to-fix-it/curl.adoc
> Modify S4830(php): Fix code sample

- rules/S1527/javascript/rule.adoc
- rules/S1527/metadata.json
> Modify rule S1527: Adapt to LaYC

- rules/S2201/csharp/metadata.json
- rules/S2201/csharp/rule.adoc
> Modify rule S2201: LaYC format 

- rules/S3346/csharp/metadata.json
- rules/S3346/csharp/rule.adoc
https://sonarsource.github.io/rspec/#/rspec/S3346/csharp
> Modify S3346: LaYC format

- rules/S5332/azureresourcemanager/rule.adoc
> Modify rule S5332: Add additional implementation message

- rules/S3735/javascript/rule.adoc
> Modify rule S3735: LaYC format 

- rules/S1716/python/rule.adoc
> Modify rule S1716: LaYC format

- rules/S3862/python/rule.adoc
> Modify rule S3862: LaYC format

- rules/S5549/python/rule.adoc
> Modify rule S5549: LaYC format

- rules/S6468/python/metadata.json
- rules/S6468/python/rule.adoc
> Modify rule S6468: LaYC format

- rules/S5756/python/rule.adoc
> Modify S5756: LaYC format

- rules/S5632/python/rule.adoc
> Modify S5632: LaYC format

- rules/S5644/python/rule.adoc
> Modify S5644: LaYC format

- rules/S5905/python/rule.adoc
> Modify S5905: LaYC format

- rules/S5828/python/rule.adoc
> Modify rule S5828: LaYC format

- rules/S2734/python/rule.adoc
> Modify S2734: LaYC format

- rules/S5719/python/rule.adoc
> Modify Rule S5719: LaYC format

- rules/S5724/python/rule.adoc
> Modify rule S5724: LaYC format

- rules/S5722/python/rule.adoc
> Modify rule S5722: LaYC format

- rules/S5796/python/rule.adoc
> Modify S5796: LaYC format

- rules/S5553/cfamily/metadata.json
- rules/S5553/cfamily/rule.adoc
> Modify rule S5553: CPP-4409 new cases + LayC

- rules/S6442/javascript/rule.adoc
> Modify rule S6442: Adapt to LaYC

- rules/S4125/javascript/rule.adoc
> Modify rule S4125: Adapt to LaYC

- rules/S6388/azureresourcemanager/rule.adoc
> SONARIAC-915 Fix formatting and fields names

- rules/S3453/comments-and-links.adoc
- rules/S3453/csharp/compliant-code.adoc
- rules/S3453/csharp/noncompliant-code.adoc
- rules/S3453/csharp/rule.adoc
- rules/S3453/description.adoc
- rules/S3453/exceptions.adoc
- rules/S3453/highlighting.adoc
- rules/S3453/how-dotnet.adoc
- rules/S3453/message.adoc
- rules/S3453/metadata.json
- rules/S3453/resources-dotnet.adoc
- rules/S3453/rspecator.adoc
- rules/S3453/vbnet/compliant-code.adoc
- rules/S3453/vbnet/noncompliant-code.adoc
- rules/S3453/vbnet/rule.adoc
- rules/S3453/why-dotnet.adoc
> Modify rule S3453: LaYC format

- rules/S5713/python/rule.adoc
> Modify rule S5713: LaYC format

- rules/S5708/python/rule.adoc
> Modify rule S5708: LaYC format

- rules/S5807/python/rule.adoc
> Modify S5807: LaYC format

- rules/S5747/python/rule.adoc
> Modify S5747: LaYC format

- rules/S2823/python/rule.adoc
> Modify S2823: LaYC format

- rules/S6080/javascript/metadata.json
- rules/S6080/javascript/rule.adoc
> Modify rule S6080: Adapt to LaYC

- rules/S6079/javascript/rule.adoc
> Modify rule S6079: Adapt to LaYC

- rules/S2995/csharp/metadata.json
- rules/S2995/csharp/rule.adoc
> Modify rule S2995: LaYC format

- rules/S5607/python/rule.adoc
> Modify rule S5607: LaYC format

- rules/S2711/python/rule.adoc
> Modify rule S2711: LaYC format

- rules/S2319/python/rule.adoc
> Modify rule S2319: LaYC format

- rules/S5714/python/rule.adoc
> Modify rule S5714: LaYC format

- rules/S3453/resources-dotnet.adoc
> Modify rule S3453: Update rule link format

- rules/S5712/python/rule.adoc
> Modify rule S5712: LaYC format

- rules/S6556/python/rule.adoc
> Modify S6556: Add diff highlighting

- rules/S3610/csharp/metadata.json
> S3610: Set quickfix field to targeted

- rules/S3168/csharp/metadata.json
- rules/S3168/csharp/rule.adoc
> Modify rule S3168: LaYC format

- rules/S3984/csharp/metadata.json
- rules/S3984/csharp/rule.adoc
> Modify rule S3984: LaYC format

- rules/S4507/xml/rule.adoc
Implementation ticket: [SONARXML-172](https://sonarsource.atlassian.net/browse/SONARXML-172)
AppSec ticket: [APPSEC-700](https://sonarsource.atlassian.net/browse/APPSEC-700)
[APPSEC-700]: https://sonarsource.atlassian.net/browse/APPSEC-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARXML-172]: https://sonarsource.atlassian.net/browse/SONARXML-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S4507: Adding support for web.config error handling parameters (XML)(APPSEC-700)

- rules/S6435/javascript/metadata.json
- rules/S6435/javascript/rule.adoc
> Modify rule S6435: Adapt to LaYC

- rules/S6092/javascript/rule.adoc
> Modify rule S6092: Adapt to LaYC

- rules/S3616/javascript/rule.adoc
> Modify rule S3616: Adapt to LaYC

- rules/S1848/csharp/metadata.json
- rules/S1848/csharp/rule.adoc
- rules/S1848/description.adoc
> Modify rule S1848: LaYC format

- rules/S6610/csharp/metadata.json
See code-fix implementation here: https://github.com/SonarSource/sonar-dotnet/pull/7507
> Modify rule S6610: Update quickfix field to covered

- rules/S3363/csharp/rule.adoc
- rules/S3363/introduction-dotnet.adoc
- rules/S3363/vbnet/metadata.json
- rules/S3363/vbnet/rule.adoc
- rules/S3363/why-dotnet.adoc
> Modify Rule S3363: Add VB.NET description

- rules/S3696/javascript/rule.adoc
> Modify rule S3696: Adapt to LaYC

- rules/S3531/javascript/metadata.json
- rules/S3531/javascript/rule.adoc
> Modify rule S3531: Adapt to LaYC

- rules/S3603/csharp/rule.adoc
- rules/S3603/vbnet/rule.adoc
- rules/S3887/rule.adoc
- rules/S3927/csharp/rule.adoc
- rules/S3927/description.adoc
- rules/S3927/vbnet/rule.adoc
> Fix S3887+S3603+S3927 minor issues after validation

- rules/S4624/javascript/rule.adoc
> Modify rule S4624: Adapt to LaYC

- rules/S3785/javascript/rule.adoc
> Modify rule S3785: Adapt to LaYC

- rules/S6443/javascript/rule.adoc
> Modify rule S6443: Adapt to LaYC

- rules/S4275/javascript/rule.adoc
> Modify rule S4275: Fix compliant tag

- rules/S3834/javascript/metadata.json
- rules/S3834/javascript/rule.adoc
https://sonarsource.github.io/rspec/#/rspec/S3834/javascript
https://github.com/SonarSource/SonarJS/issues/3917
> Modify rule S3834: add BigInt, rewrite the description

- rules/S3504/javascript/rule.adoc
> Modify rule S3504: Adapt to LaYC

- rules/S6440/javascript/rule.adoc
> Modify rule S6440: Adapt to LaYC

- rules/S6441/javascript/rule.adoc
> Modify rule S6441: Adapt to LaYC

- rules/S1536/javascript/rule.adoc
> Modify rule S1536: Adapt to LaYC

- rules/S4123/javascript/rule.adoc
> Modify rule S4123: Adapt to LaYC

- rules/S2870/javascript/rule.adoc
> Modify rule S2870: Adapt to LaYC

- rules/S935/cfamily/rule.adoc
> Modify rule S935: LaYC format

- rules/S3834/javascript/rule.adoc
> Modify rule S3834: Adapt to LaYC

- rules/S4140/javascript/metadata.json
- rules/S4140/javascript/rule.adoc
> Modify rule S4140: Adapt to LaYC

- rules/S4634/javascript/rule.adoc
> Modify rule S4634: Adapt to LaYC

- rules/S3579/javascript/rule.adoc
> Modify rule S3579: Adapt to LaYC

- rules/S2432/javascript/rule.adoc
> Modify rule S2432: Adapt to LaYC

- rules/S6641/csharp/how-to-fix-it/dotnet-core.adoc
> Modify rule S6641: Add missing comma to code example

- rules/S3984/javascript/rule.adoc
> Modify rule S3984: Adapt to LaYC

- rules/S2310/javascript/rule.adoc
> Modify rule S2310: Adapt to LaYC

- rules/S2703/javascript/rule.adoc
> Modify rule S2703: Adapt to LaYC

- rules/S6351/javascript/rule.adoc
> Modify rule S6351: Adapt to LaYC

- rules/S2176/java/metadata.json
- rules/S2176/java/rule.adoc
Before:
https://next.sonarqube.com/sonarqube/coding_rules?q=s2176&open=java%3AS2176
After:
> Modify rule S2176(Java): Update rule according to the LayC

- rules/S2097/java/metadata.json
- rules/S2097/java/rule.adoc
- rules/S2097/kotlin/metadata.json
- rules/S2097/kotlin/rule.adoc
- rules/S2097/metadata.json
Before:
https://next.sonarqube.com/sonarqube/coding_rules?q=s2097&open=java%3AS2097
After:
Before:
https://next.sonarqube.com/sonarqube/coding_rules?q=s2097&open=kotlin%3AS2097
After:
> Modify rule S2097: Update rule according to the LayC

- rules/S3686/javascript/metadata.json
- rules/S3686/javascript/rule.adoc
> Modify rule S3686: Adapt to LaYC

- rules/S2814/rule.adoc
> Modify rule S2814: Adapt to LaYC

- rules/S955/cfamily/rule.adoc
> Modify rule S955: LaYC format

- rules/S1516/javascript/rule.adoc
> Modify rule S1516: Adapt to LaYC

- rules/S1529/javascript/rule.adoc
> Modify rule S1529: Adapt to LaYC

- rules/S1321/javascript/rule.adoc
> Modify rule S1321: Adapt to LaYC

- rules/S6317/terraform/rule.adoc
> Modify S6317: Compliant-ized the text

- rules/S6329/terraform/rule.adoc
> Modify S6329: Make GCP sample safer

- rules/S6414/terraform/rule.adoc
> Modify S6414: Fix Ask-yourself

- rules/S6333/ask-yourself.adoc
- rules/S6333/description.adoc
- rules/S6333/metadata.json
- rules/S6333/recommended.adoc
- rules/S6333/see.adoc
> Modify S6333: Improve the general text

- rules/S5267/cfamily/rule.adoc
> Modify rule S5267: LaYC format

- rules/S6491/cfamily/rule.adoc
Keep the whole description in "Why is this an issue" because reading it once should be enough and fix is trivial. Also, aimed for conciseness.
> Modify rule S6491: LaYC format

- rules/S956/cfamily/rule.adoc
> Modify rule S956: LaYC format

- rules/S6325/javascript/rule.adoc
> Modify rule S6325: Adapt to LaYC

- rules/S6431/kubernetes/rule.adoc
> Modify S6431(k8s): Improve sample

- rules/S1135/kubernetes/rule.adoc
> Modify S1135(k8s): Improve the code sample

- rules/S6502/docker/rule.adoc
> Modify S6502: Improve description

- rules/S1439/javascript/rule.adoc
> Modify rule S1439: Adapt to LaYC

- rules/S6426/javascript/rule.adoc
> Modify rule S6426: Adapt to LaYC

- README.adoc
- ci/validate_asciidoc.sh
- docs/description.adoc
- rules/S5553/cfamily/rule.adoc
- rules/S6655/cfamily/rule.adoc
- shared_content/cfamily/dangling_reference_impact.adoc
> Create a shared_content folder at root

- rules/S4143/description.adoc
> Modify-S4131-layc

- rules/S1128/javascript/rule.adoc
> Modify rule S1128: Adapt to LaYC

- rules/S6500/docker/rule.adoc
> Modify S6500(docker): Improve samples

- rules/S6505/docker/rule.adoc
> Modify S6505(docker): Improve samples

- rules/S6303/description.adoc
> Modify S6303: Add more risks

- docs/header_names/allowed_framework_names.adoc
- rules/S4423/terraform/how-to-fix-it/azure-mssql.adoc
- rules/S4423/terraform/rule.adoc
> Modify S4423(Azure): Add MSSQL sample

- rules/S6333/cloudformation/rule.adoc
> Modify S6333(Cfn): Improve samples

- rules/S4524/description.adoc
> modify-S4524-minor-edit

- rules/S3403/javascript/rule.adoc
> Modify rule S3403: Adapt to LaYC

- rules/S6471/docker/rule.adoc
> Modify S6471(docker): Improve overall rule

- rules/S6329/cloudformation/rule.adoc
> Modify S6329(Cfn): Improve samples

- rules/S6302/cloudformation/rule.adoc
> Modify S6302(Cfn): Improve samples

- rules/S6294/cloudformation/rule.adoc
> Modify S6294(Cfn): Improve samples

- rules/S6321/cloudformation/rule.adoc
> Modify S6321(Cfn): Improve samples

- rules/S6413/terraform/rule.adoc
> Modify S6413(tf): Add AWS Cloudwatch

- rules/S3400/cfamily/metadata.json
> Modify rule S3400: CPP-3455 Delete this rule for CFamily

- rules/S2272/java/rule.adoc
Reviewed for typos, and added a link to Javadoc.
> Modify rule S2272: LaYC review [SONARJAVA-4490]

- rules/S5863/javascript/rule.adoc
> Modify rule S5863: Adapt to LaYC

- rules/S2699/javascript/rule.adoc
> Modify rule S2699: Adapt to LaYC

- rules/S3516/javascript/rule.adoc
> Modify rule S3516: Adapt to LaYC

- rules/S3329/csharp/metadata.json
- rules/S3329/vbnet/metadata.json
> Update S3329: Change quickfix field

- rules/S1046/cfamily/rule.adoc
- rules/S3516/javascript/rule.adoc
> Modify rule S1046: LaYC format

- rules/S1039/cfamily/rule.adoc
> Modify rule S1039: LaYC format

- rules/S6328/javascript/rule.adoc
> Modify rule S6328: Adapt to LaYC

- rules/S2970/javascript/rule.adoc
> Modify rule S2970: Adapt to LaYC

- rules/S1523/javascript/rule.adoc
https://github.com/SonarSource/SonarJS/issues/3920
> Modify rule S1523: Raise issue for `javascript:` URLs

- rules/S1143/javascript/rule.adoc
> Modify rule S1143: Adapt to LaYC

- rules/S1301/javascript/rule.adoc
> Modify rule S1301: Adapt to LaYC

- rules/S6223/cfamily/rule.adoc
> Modify rule S6223: LaYC format

- rules/S2251/javascript/rule.adoc
> Modify rule S2251: Adapt to LaYC

- rules/S5850/javascript/rule.adoc
> Modify rule S5850: Adapt to LaYC

- rules/S1862/javascript/metadata.json
- rules/S1862/javascript/rule.adoc
> Modify rule S1862: Adapt to LaYC

- rules/S4621/javascript/metadata.json
- rules/S4621/javascript/rule.adoc
> Modify rule S4621: Adapt to LaYC

- rules/S4323/javascript/rule.adoc
> Modify rule S4323: Adapt to LaYC

- rules/S4623/javascript/rule.adoc
> Modify rule S4623: Adapt to LaYC

- rules/S6380/azureresourcemanager/rule.adoc
> Modify rule S6380: Fix message inconsistencies (ARM)

- rules/S4325/javascript/rule.adoc
> Modify rule S4325: Adapt to LaYC

- rules/S1710/java/rule.adoc
> Modify S1710: fix a typo

- rules/S3981/javascript/metadata.json
> Modify rule S3981: Improve rule's title

- rules/S4030/metadata.json
> Modify rule S4030: Improve rule's title

- rules/S2310/javascript/metadata.json
> Modify rule S2310: Improve rule's title

- rules/S4822/javascript/metadata.json
> Modify rule S4822: Improve rule's title

- rules/S2999/javascript/metadata.json
> Modify rule S2999: Improve rule's title

- rules/S5650/python/metadata.json
- rules/S5650/python/rule.adoc
> Modify S5650: LaYC format

- rules/S6656/azureresourcemanager/rule.adoc
> Modify rule S6656: Add missing message and highlighting info

- rules/S6273/cloudformation/rule.adoc
- rules/S6273/description.adoc
- rules/S6273/see.adoc
- rules/S6273/summary.adoc
- rules/S6273/terraform/rule.adoc
> Modify rule S6273: LaYC format

- rules/S5642/python/metadata.json
- rules/S5642/python/rule.adoc
> Modify S5642: LaYC format

- rules/S2876/python/rule.adoc
> Modify S2876: LaYC format

- ci/validate_asciidoc.sh
This reverts commit 09a2902fe3b8688ca6bc818c7c6055e2307e6235. It introduced some regressions.
> Revert "Clean ci/validate_asciidoc.sh (#2684)"

- rules/S4524/javascript/rule.adoc
> Modify rule S4524: Add link to documentation

- rules/S2692/javascript/rule.adoc
> Modify rule S2692: Fix snippet and documentation section

- rules/S6594/javascript/rule.adoc
> Modify rule S6594: Fix link and remove extra section

- rules/S6654/javascript/rule.adoc
> Modify rule S6654: Add diff-tag and fix noncompliant comments

- rules/S4043/javascript/rule.adoc
> Modify rule S4043: Delimite consecutive snippets with a description

- rules/S4143/javascript/rule.adoc
> Modify rule S4143: Remove leading space in code snippets

- rules/S6092/javascript/rule.adoc
> Modify rule S6092: Prefix documentation links with bullet points

- rules/S6509/javascript/rule.adoc
> Modify rule S6509: Fix links' titles

- rules/S1481/javascript/rule.adoc
- rules/S6535/javascript/rule.adoc
- rules/S6544/javascript/rule.adoc
- rules/S6551/javascript/rule.adoc
- rules/S6565/javascript/rule.adoc
- rules/S6568/javascript/rule.adoc
- rules/S6569/javascript/rule.adoc
- rules/S6571/javascript/rule.adoc
- rules/S6572/javascript/rule.adoc
- rules/S6578/javascript/rule.adoc
- rules/S6582/javascript/rule.adoc
- rules/S6583/javascript/rule.adoc
- rules/S6598/javascript/rule.adoc
- rules/S6606/javascript/rule.adoc
- rules/S6637/javascript/rule.adoc
- rules/S6643/javascript/rule.adoc
- rules/S6657/javascript/rule.adoc
- rules/S6661/javascript/rule.adoc
> Modify JS/TS rules: Uniform links to TypeScript and MDN references

- rules/S6657/javascript/rule.adoc
> Modify rule S6657: Replace 'var' with 'let' in snippets and fix case

- rules/S6551/javascript/rule.adoc
> Modify rule S6551: Fix documentation section

- rules/S6671/javascript/rule.adoc
> Modify rule S6671: Fix related rules section

- rules/S1128/javascript/rule.adoc
> Modify rule S1128: Fix related rules section

- rules/S6635/javascript/rule.adoc
> Modify rule S6635: Fix link title

- rules/S1763/javascript/rule.adoc
> Modify rule S1763: Fix compliant diff-tag

- rules/S6650/javascript/rule.adoc
> Modify rule S6650: Add diff-tag

- .cirrus.yml
Save about 20s of CPU time on each commit/PR.
> Do not clone the repo in all_required_checks_task

- rules/S6379/azureresourcemanager/rule.adoc
> Modify rule S6379: Add language AzureResourceManager (Bicep)

- rules/S6413/azureresourcemanager/rule.adoc
> Modify rule S6413: Defining a short log retention duration is security-sensitive, add Bicep format

- rules/S5727/python/rule.adoc
> Modify S5727: LaYC format

- rules/S5781/rule.adoc
> Modify rule S5781: LaYC format

- rules/S5332/azureresourcemanager/ask-yourself.adoc
- rules/S5332/azureresourcemanager/metadata.json
- rules/S5332/azureresourcemanager/recommended.adoc
- rules/S5332/azureresourcemanager/rule.adoc
- rules/S5332/azureresourcemanager/see.adoc
PR #1839 added the JSON format for Azure Resource Manager. This PR adds BICEP. Since BICEP support will follow later, it can not be merged yet.
> Create rule S5332: Add BICEP for AzureResourceManager

- rules/S5886/python/rule.adoc
> Modify S5886: LaYC format

- rules/S5704/python/rule.adoc
> Modify rule S5704: LaYC format

- rules/S6329/azureresourcemanager/highlight.adoc
- rules/S6329/azureresourcemanager/message.adoc
- rules/S6329/azureresourcemanager/metadata.json
- rules/S6329/azureresourcemanager/rule.adoc
Research ticket: https://sonarsource.atlassian.net/browse/SONARIAC-754
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARIAC-790
PR #1872 Added support for AzureResourceManager (JSON). This PR extends that work to add Bicep support. This PR cannot be merged until we support the Bicep language.
> Modify rule S6329: Add language AzureResourceManager (Bicep)

- rules/S1913/cfamily/rule.adoc
> Modify rule S1913: LaYC format

- rules/S1135/description.adoc
> Modify rule S1135: LaYC format

- rules/S5795/python/metadata.json
- rules/S5795/python/rule.adoc
> Modify Rule S5795: LaYC Format

- rules/S6661/python/metadata.json
The rule was too noisy and opinionated.
See also
* https://sonarsource.atlassian.net/browse/SONARPY-1412?focusedCommentId=512412
> Modify rule S6661: Python: Remove from Sonar Way

- rules/S1128/python/metadata.json
See also https://sonarsource.atlassian.net/browse/SONARPY-427?focusedCommentId=512670
> Modify rule S1128: Python: Remove rule from Sonar way

- rules/S6476/docker/rule.adoc
> Modify rule S6476: LaYC format

- rules/S3519/cfamily/rule.adoc
Adding very useful LaYC migration notes from Balazs.
> S3519: Add notes for migration to LaYC

- rules/S6382/azureresourcemanager/docs.adoc
- rules/S6382/azureresourcemanager/highlighting.adoc
- rules/S6382/azureresourcemanager/message.adoc
- rules/S6382/azureresourcemanager/remarks.adoc
- rules/S6382/azureresourcemanager/rule.adoc
- rules/S6382/terraform/highlighting.adoc
- rules/S6382/terraform/message.adoc
- rules/S6382/terraform/rule.adoc
Specification ticket: https://sonarsource.atlassian.net/browse/SONARIAC-762
Implementation ticket: TBC
This PR builds on top of #1920 to add examples using the Bicep language.
> Modify rule S6382: Add language AzureResourceManager (Bicep)

- rules/S3749/java/metadata.json
- rules/S3749/java/rule.adoc
> Modify rule S3749: update issue type to Code-Smell (APPSEC-523)

- rules/S5272/cfamily/metadata.json
- rules/S5272/cfamily/rule.adoc
> Modify rule S5272: Expand and adjust for LaYC

- rules/S100/csharp/metadata.json
Revert an accidental change introduced in #2713.
> Modify rule S100: Revert accidental change

- rules/S5486/cfamily/metadata.json
- rules/S5486/cfamily/rule.adoc
> Modify rule S5486: Adapt to LaYC

- rules/S6464/python/rule.adoc
> Modify rule S6464: LaYC format

- rules/S3699/javascript/rule.adoc
- rules/S3699/php/rule.adoc
- rules/S3699/python/rule.adoc
> Modify rule S3699: LaYC format

- rules/S6465/python/rule.adoc
> Modify rule S6465: LaYC format

- rules/S6383/azureresourcemanager/rule.adoc
> SONARIAC-761 Rule S6383 Disable RBAC on AKS ad Bicept

- rules/S3985/python/rule.adoc
- rules/S3985/rule.adoc
- rules/S3985/summary.adoc
> Modify rule S3985: LaYC format

- rules/S1542/python/rule.adoc
> Modify rule S1542: LaYC format

- rules/S5283/cfamily/metadata.json
- rules/S5283/cfamily/rule.adoc
> Modify rule S5283: Adapt to LaYC

- rules/S5799/python/rule.adoc
> Modify rule S5799: LaYC format

- rules/S5633/python/rule.adoc
> Modify rule S5633: LaYC format

- rules/S2836/python/rule.adoc
> Modify rule S2836: LaYC format

- rules/S2710/python/rule.adoc
> Modify rule S2710: LaYC format

- rules/S5797/rule.adoc
> Modify rule S5797: LaYC format

- rules/S5709/python/rule.adoc
> Modify rule S5709: LaYC format

- rules/S3403/javascript/rule.adoc
- rules/S3403/python/rule.adoc
> Modify rule S3403: LaYC format

- rules/S6417/java/rule.adoc
- rules/S6417/python/rule.adoc
> Modify S6417: LaYC format

- rules/S1845/python/rule.adoc
- rules/S1845/rule.adoc
- rules/S1845/swift/rule.adoc
> Modify rule S1845: LaYC format

- rules/S5754/python/rule.adoc
> Modify rule S5754: LaYC format

- rules/S6294/cloudformation/rule.adoc
> Modify rule S6294: LaYC format

- rules/S6466/python/rule.adoc
> Modify rule S6466: LaYC format

- rules/S2320/python/rule.adoc
> Modify rule S2320: LaYC format

- rules/S5890/python/rule.adoc
> Modify rule S5890: LaYC format

- rules/S6385/azureresourcemanager/how_to_fix_it.adoc
- rules/S6385/azureresourcemanager/rule.adoc
Research ticket: https://sonarsource.atlassian.net/browse/SONARIAC-757
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARIAC-772
PR https://github.com/SonarSource/rspec/pull/1829 Added support for AzureResourceManager (JSON). This PR extends that work to add Bicep support. This PR cannot be merged until we support the Bicep language.
> Modify rule S6385: Add language AzureResourceManager (Bicep)

- rules/S4004/rule.adoc
> Modify rule S4004: Fix code samples 

- rules/S5806/python/rule.adoc
> Modify rule S5806: LaYC format

- rules/S5914/python/rule.adoc
> Modify rule S5914: LaYC format

- rules/S2318/python/rule.adoc
> Modify rule S2318: LaYC format

- rules/S2083/javascript/how-to-fix-it/express.adoc
- rules/S2083/javascript/how-to-fix-it/node.adoc
> Modify S2083(js): Fix code samples

- rules/S5717/python/rule.adoc
> Modify rule S5717: LaYC format

- rules/S5780/rule.adoc
> Modify rule S5780: LaYC format

- rules/S5655/python/rule.adoc
> Modify rule S5655: LaYC format

- rspec-tools/rspec_tools/utils.py
> Added secrets language to LANG_TO_SOURCE dict

- rules/S5720/python/rule.adoc
> Modify rule S5720: LaYC format

- rules/S5706/python/rule.adoc
> Modify rule S5706: LaYC format

- rules/S2317/python/rule.adoc
> Modify rule S2317: LaYC format

- rules/S5496/python/metadata.json
- rules/S5496/python/rule.adoc
> Modify S5496(Python): Migrate to LayC

- rules/S2168/java/rule.adoc
> SONARJAVA-4495 Update S2168 in line with LayC.

- rules/S2175/java/rule.adoc
> SONARJAVA-4495 Update S2175 in line with LayC.

- rules/S5335/php/metadata.json
- rules/S5335/php/rule.adoc
> Modify S5335(PHP):  Migrate to LayC

- rules/S2276/java/rule.adoc
> Modify rule S2276: Update in line with LaYC (SONARJAVA-4495)

- rules/S2293/java/rule.adoc
> Modify rule S2293: Update in line with LayC (SONARJAVA-4495)
