- .cirrus.yml
- rspec-tools/rspec_tools/checklinks.py
- validate_links.sh
The validation fails because of a local link we have in the project's README.adoc.
> Accept local links without checking them.

- .cirrus.yml
- generate_html.sh
- rspec-tools/rspec_tools/cli.py
- rspec-tools/rspec_tools/rules.py
- rspec-tools/rspec_tools/validation/description.py
- rspec-tools/tests/resources/rules/S100/cfamily/rule.html
- rspec-tools/tests/validation/test_description_validation.py
- validate_asciidoc.sh
- validate_links.sh
The hard-coded `ACCEPTED_SECTION_NAMES` includes all the sections found in the imported RSPECs from Jira.
The list could be shrunk by automatically renaming sections with a canonical name, but I think that belongs to another PR.
> RULEAPI-574 Validate RSPEC description structure

- rspec-tools/rspec_tools/checklinks.py
These two links consistently pass when probed from my machine, and timeout when probed from CirrusCI.
The only explanation I see is throttling on the side of the Oracle servers
> Skip the validation of "blogs.oracle.com" links that work locally but timeout in CI

- frontend/src/deployment/index.ts
- frontend/src/deployment/pullRequestIndexing.ts
1. Force the deployment to fail for any unexpected failure in the indexing of the un-merged open PRs (for the non implemented rules).
2. Ignore the PRs that promise to create a certain rule (i.e. "Create rule S1234") and fail to deliver on that promise: have no folder `rules/S1234`.
> RULEAPI-624 Fix the RSPEC index in the presense of PRs with noncompliant file structure.

- .cirrus.yml
- Dockerfile
- ci/cirrus-cache.sh
- rspec-tools/rspec_tools/checklinks.py
- validate_links.sh
two fluentcpp links (in S5402 and S5419) that are down now are injected into the url-probing history, so they will not fail the link validation for the following 7 days. If fluentcpp.com is still down by then, I suppose, we will have to remove or replace them.
> RULEAPI-616: Stabilize the link validation CI check by preserving the probing results between runs

- rspec-tools/rspec_tools/validation/rule-metadata-schema.json
New security standard "OWASP Mobile": https://owasp.org/www-project-mobile-top-10/
Always starts with a `M`, eg: `M1`, `M2` ... `M10`
Is was used in Jira for some current RSPECs: https://jira.sonarsource.com/browse/RSPEC-5605
but metadata standards on subtask/languages [were not migrated](https://github.com/SonarSource/rspec/blob/master/rules/S5604/xml/metadata.json)
> add owasp mobile security standard to schema validation

- rspec-tools/rspec_tools/validation/rule-metadata-schema.json
* PCI DSS:  https://en.wikipedia.org/wiki/Payment_Card_Industry_Data_Security_Standard, three numbers maximum separated by dots: `4.1.2`, `6.1.2`
* CIS: https://www.cisecurity.org/controls/cis-controls-list/, three numbers maximum separated by dots: `4.1.2`, `6.1.2`
* HIPAA: https://hipaaone.com/wp-content/uploads/2019/06/HIPAA-Security-Checklist.pdf, two numbers maximum separated by a dot, examples: `164.312`, `164.314`
* CERT: https://resources.sei.cmu.edu/downloads/secure-coding/assets/sei-cert-c-coding-standard-2016-v01.pdf, two alphanumerical strings separated by a dash and ending by a dot, examples: `PRE30-C.`, `FIO30-C.`
* MASVS: https://mobile-security.gitbook.io/masvs/security-requirements/0x06-v1-architecture_design_and_threat_modelling_requireme, `MSTG` followed  by a dash then …
> add missing and future security standards

- rules/S5402/cfamily/rule.adoc
- rules/S5419/cfamily/rule.adoc
These links are dead for a long time now, and there are already links to C++ Core Guidelines
> Remove fluentcpp dead links

- rules/S1451/csharp/rule.adoc
- rules/S1451/vbnet/rule.adoc
See https://github.com/asciidoctor/asciidoctor/issues/724 for the details on the empty-line stripping in the end of code blocks,
and the [long-standing issue](https://github.com/asciidoctor/asciidoctor/issues/754) about disabling this behavior.
> S1451 Remove the <br> tags from inside <pre>

- rules/S6032/cfamily/rule.adoc
The text mentioned `&auto a = f()` instead of `auto &a = f()`
> Correct typo

- rules/S3551/java/metadata.json
The reference to MET04-J has been removed from the metadata and replaced with TSM00-J which is more specific and thus relevant to the issue.
> Modify rule S3551: Fix mismatch in CERT references between text documentation and metadata

- rules/S2057/java/rule.adoc
Add an exception to the rule as the constraint of validation on the serialUID is waived for Records.
SONARJAVA-3755
> Modify rule S2057: Add an exception for Records

- rules/S5854/java/rule.adoc
The comment showing the output used the wrong accent.
> Modify rule S5854: Fix noncompliant example

- rules/S1034/cfamily/metadata.json
- rules/S1034/metadata.json
- rules/S1181/java/metadata.json
- rules/S1181/metadata.json
- rules/S1238/cfamily/metadata.json
- rules/S1238/metadata.json
- rules/S1270/cfamily/metadata.json
- rules/S1270/metadata.json
- rules/S1987/java/metadata.json
- rules/S1987/metadata.json
- rules/S3630/cfamily/metadata.json
- rules/S3630/metadata.json
- rules/S3949/java/metadata.json
- rules/S3949/metadata.json
- rules/S787/cfamily/metadata.json
- rules/S787/metadata.json
- rules/S800/java/metadata.json
- rules/S800/metadata.json
- rules/S867/metadata.json
- rules/S930/metadata.json
- rules/S979/java/metadata.json
- rules/S979/metadata.json
I got confirmation from the bubbles (other than CFamily) that used "based-on-misra" and "cppcoreguidelines" tags that it was not intentional.
> Clean-up C++ tags

- rules/S2479/java/rule.adoc
The tabs exception is now configurable is now using a parameter and disabled by default.
> Modify rule S2479: Remove tabs exception for Java text blocks

- rules/S6221/cfamily/rule.adoc
> CPP-2968: Rule S6221: Concept names should comply with a naming convention

- rules/S6004/cfamily/rule.adoc
- Small typos introduced when adding range-based for loops
- The rule no longer triggers if there is no code for the variable to leak into
> Modify rule S6004 : Update after changes provided by CPP-2843

- frontend/src/RulePage.tsx
This PR also changes the behaviour of the Edit on Github link. Before if there was a PR in progress for any language it always opened the folder in the branch from which the PR was created. Now the behaviour remains the same for not implemented languages, however it targets the master branch for languages that already have an implementation.
> RULEAPI-673: Stop displaying "Not implemented" for languages that do implement the rule

- rules/S6045/cfamily/metadata.json
- rules/S6045/cfamily/rule.adoc
> Modify rule S6045: Cover heterogenous lookup for unordered containers in C++20

- frontend/src/RulePage.tsx
Implementation based on 
> Special characters aren’t stored in the index, which means you can’t search for them. The index only keeps text and numbers, so searching for "\\[Jira Software\\]" and "Jira Software" will have the same effect — escaped special characters ([]) won’t be included in the search. `
from https://confluence.atlassian.com/jirasoftwareserver0813/search-syntax-for-text-fields-1027135330.html
> RULEAPI-678: Escape """ in search strings embedded into the rule pages rendered in frontend

- rule_coverage/coverage.py
I hope you don't mind the first two commits that do just some refactoring without changing the functionality of the script (it does sort the fields in json now: for the ease of comparison later).
I validated that the script output did not change using `diff <(jq --sort-keys . ../covered_rules.json) <(jq --sort-keys . covered_rules.json)`.
The functional changes are in the last commit:
- adding `sonar-security` into the list of scanned repositories; 
- prefixing versions displayed in the coverage information with the repository name, since now the language rule can be implemented in multiple repositories.
> RULEAPI-668: Take the sonar-security analyzer into account when collecting rule coverage in the coverage script

- rules/S6288/java/rule.adoc
https://jira.sonarsource.com/browse/SONARJAVA-3868
> Create rule S6288[java]: Authorizing non-authenticated users to use keys in the Android KeyStore is security-sensitive

- frontend/src/hljs-humanoid-light.css
Before the fix:
after the fix:
> RULEAPI-700: fix odd highlighting for selected segment of metadata

- .github/workflows/update_coverage.yml
This is a rebase artefact: forgotten to use the `rspec-tools` directory where the coverage script was moved to.
> Fix coverage update: the phantom of the old rule_coverage directory

- rules/S4784/vbnet/metadata.json
this entry overrides the entry in the parent metadata.json (rules/S4784/metadata.json), and sets the replacement rules to an empty list thereby unconditionally deprecating the rule.
> Fix the erroneous undeprecation of a deprecated rule without replacement rules

- rules/S1134/rule.adoc
- rules/S1135/rule.adoc
- rules/S1493/rule.adoc
- rules/S1523/rule.adoc
- rules/S2070/rule.adoc
- rules/S2076/rule.adoc
- rules/S2087/rule.adoc
- rules/S2222/rule.adoc
- rules/S2631/rule.adoc
- rules/S2647/rule.adoc
- rules/S3904/rule.adoc
- rules/S4274/rule.adoc
- rules/S4830/rule.adoc
- rules/S5147/rule.adoc
- rules/S5344/rule.adoc
- rules/S5659/rule.adoc
- rules/S5691/rule.adoc
- rules/S5730/rule.adoc
- rules/S5732/rule.adoc
- rules/S5734/rule.adoc
- rules/S5736/rule.adoc
- rules/S5742/rule.adoc
- rules/S5743/rule.adoc
- rules/S5753/rule.adoc
- rules/S5757/rule.adoc
- rules/S5773/rule.adoc
- rules/S5804/rule.adoc
- rules/S5852/rule.adoc
- rules/S5883/rule.adoc
- rules/S6273/rule.adoc
committed the squased commit f6331f7fdca7fe36e52439b927312fd5d5a455c0 of the PR #362 
The mistake was caused by the uninitialized variable "hasSeeSection" in the
automatic removal script. Fixed here:
https://github.com/SonarSource/languages-experimental-tooling/commit/f6331f7fdca7fe36e52439b927312fd5d5a455c0
> Fix the mistakingly deleted 'See' sections in #362

- rules/S6287/csharp/rule.adoc
- rules/S6287/java/rule.adoc
- rules/S6287/javascript/rule.adoc
- rules/S6287/php/rule.adoc
- rules/S6287/python/rule.adoc
The specification of the rule changed after the RSPEC was created and I forgot to update the code samples in RSPEC.
For now an issue is only raised if the header is explicitly "Set-Cookie" but not if it is tainted. In the future this should change but for now we will not detect an issue if the key is tainted. Thus, it does not make sense to show it in the code samples.
> Modify rule S6287: Remove tainted key from samples

- .cirrus.yml
- .github/workflows/add_language.yml
- .github/workflows/create_new_rspec.yml
- ci/validate_links.sh
When python scripts executing on Cirrus Ci run`pipenv install -e .`, it triggers an update of `Pipfile.lock` which then fails to resolve dependency.
As `pipenv install` doesn't trigger an update of `Pipfile.lock` I removed the `-e` argument from install commands.
> Fix "pipenv install" invocation to avoid update of Pipfile.lock

- rules/S1121/javascript/rule.adoc
This change is motivated by a feedback from the community (see [thread](https://community.sonarsource.com/t/typescript-s1121-should-ignore-chained-assignments/27392/3?u=yassin_kammoun)).
> Modify rule S1121: Describe unexpected creation of global variables

- rules/S6178/cfamily/metadata.json
partial because no quick fixes are generated when char types mismatch.
> Modify rule S6178[cfamily]: add quick fix

- rules/S6193/cfamily/metadata.json
- rules/S6193/cfamily/rule.adoc
I've removed part of the metadata as it felt incorrect for a new rule to have a legacy key. Let me know if there is something I'm missing though.
> Modify rule S6193: Fix typo & update metadata

- rules/S1238/cfamily/rule.adoc
Implementation ticket: CPP-3317
> Modify rule S1238[cfamily]: exception for coroutines (CPP-3317)

- rules/S6193/cfamily/metadata.json
Since the rule is based on a regex, it won't be possible to implement quick fixes.
> Modify rule S6193: mark quick fix as infeasible

- rules/S1763/cfamily/rule.adoc
This effectively takes the content of `../description.adoc` and adds mentions to `co_return` and `[[noreturn]]` functions (`abort`, `std::terminate`).
---
No implementation changes are required.
> Modify rule S1763[cfamily]: cover co_return and [[noreturn]]

- rules/S5843/java/rule.adoc
- rules/S5843/php/rule.adoc
- rules/S5843/python/rule.adoc
FYI @johann-beleites-sonarsource and @nils-werner-sonarsource:
Funny/confusing problem: you both modified the rule almost at the same time (#416 and #537), and git did not manage to catch that the description is now broken for PHP, Java and Python.
> Modify rule S5843: Fix duplicate description parts

- rules/S1226/cfamily/rule.adoc
The RSPEC was changed, but not the implementation. This PR re-establishes the previous RSPEC. The change will be available in another RSPEC that will only be merged together with the implementation.
> S1226: CPP-2006 Align RSPEC description with current rule implementation

- rules/S1768/cfamily/rule.adoc
* One change was wrong: Enums can have negative values
* The other one is of little value, especially for a deprecated rule.
> S1768 Revert changes to the RSPEC that are not in sync with the code

- rules/S1001/cfamily/metadata.json
- rules/S1001/cfamily/rule.adoc
The changes in the RSPEC were never implemented. They will be put in another PR.
Also rewrite the examples.
> Modify Rule S1001: Revert changes introduced by CPP-1307

- rules/S5131/message.adoc
This RSpec message has been misunderstood by multiple Sonar* users claiming that "reflecting user-controlled data" was exactly their goal. This message aims to clarify our point when we detect XSS in code and advise users to make a fix.
> Modify Rule S5131: Message clarity

- README.adoc
- rspec-tools/rspec_tools/create_rule.py
- rspec-tools/tests/test_create_rule.py
Update documentation and script.
---
FWIW, the doc already contains (~L260):
> == Untriaged Pull Requests
Untriaged PRs are the ones without any label. You can easily see all of them with the filter Label > Unlabeled.
All triaged PRs should have at least one label that corresponds to the bubble(s) the PR is related to. This allows bubbles to easily filter out the PRs they are interested in.
So the requirement to have labels is already there. Let me know if this should be reworded to have more visibility.
---
I also didn't document how to use `git` commands to extract the history for a given language. _If_ it should be included, I'm not exactly sure where this should go. It also feels out of scope somehow, but I don't have a strong opinion on this point.
> RULEAPI-680: Remove the mention of [label]

- frontend/src/SearchHit.tsx
- frontend/src/SearchPage.tsx
Fix the two warnings observed when testing the SearchPage component:
- Each child in an array should have a unique "key" prop.
-> add a key prop to list items
- `<div>` cannot be nested in `<p>` (or sth to that effect)
-> change the relevant Typography components from "p" to "div"
> Fix UI warnings: <div> nested in <p> and list items lacking keys

- .github/workflows/update_coverage.yml
Unless `always()` or `failure()` is configured `step.if` behave as if `success() &&` was included.
> RULEAPI-722: Always cleanup temprary branch for coverage

- frontend/src/RulePage.tsx
- frontend/src/deployment/__tests__/description.test.ts
- frontend/src/deployment/description.ts
Follow up from #702.
Parse custom string instead of file and explicitly introduce level-1 section so that asciidoctor sees it.
Preview at: https://marco-antognini-sonarsource.github.io/rspec/#/rspec/S100
Does it look reasonable?
> RULEAPI-703: Fix warnings emitted during `npm run predeploy`

- frontend/src/RulePage.tsx
- frontend/src/__tests__/App.test.tsx
- frontend/src/__tests__/RulePage.test.tsx
- frontend/src/__tests__/SearchPage.test.tsx
- frontend/src/__tests__/__snapshots__/RulePage.test.tsx.snap
- frontend/src/__tests__/__snapshots__/SearchPage.test.tsx.snap
- frontend/src/deployment/__tests__/resources/plugin_rules/S3457/csharp-metadata.json
- frontend/src/testutils.ts
- frontend/src/utils/__tests__/useRuleCoverage.test.ts
- frontend/src/utils/useRuleCoverage.ts
Mostly snapshot testing, with quite big snapshots. I think they will need to be broken down in the future if they break too often.
Also no interaction testing for the moment.
Not sure what to do with these warnings caused by the `react-highlight` (it uses `highlightBlock` inside. our code doesn't use `highlightBlock` directly). Maybe they will go away if we upgrade it?
```
console.log
Deprecated as of 10.7.0. highlightBlock will be removed entirely in v12.0
at deprecated (node_modules/highlight.js/lib/core.js:1490:11)
console.log
Deprecated as of 10.7.0. Please use highlightElement now.
at deprecated (node_modules/highlight.js/lib/core.js:1490:11)
```
> RULEAPI-571: test the UI components

- frontend/src/__tests__/__snapshots__/RulePage.test.tsx.snap
The broken UI test on master is the result of a temporary relaxation of the policy of "merge only PRs that are up-to-date with master": a snapshot-based test was introduced in one PR (#709) and was passing, and a UI change was introduced in another PR(#715) that changed the snapshot (but was not covered by the test at the time the second PR diverged from master)
> Fix the snapshot-test failure resulted from the merge

- ci/validate_asciidoc.sh
It can be hard to spot actual issues in the log with so much debug output. This PR removes most of it.
> Reduce amount of debug output in validate_asciidoc.sh

- .cirrus.yml
- frontend/sonar-project.properties
~Excluding the file from coverage analysis for now to avoid SQ blocking PRs that do not touch the code at all. (for some reason, since this file was merged despite the failing QG on SQ, other PRs that target master are assumed to have changed this file and therefore also fail QG)~
> Use full clone for tests to enable proper new-code detection on SonarQube

- .cirrus.yml
1G is not enough for pipenv to install all the dependencies (at least the deps for #771)
> Bump memory limit for metadata validation task

- ci/validate_asciidoc.sh
Run asciidoctor on all files at once instead of one by one. That allows us to considerably reduce the time it takes. On the current CI, we go from ~25 minutes to ~5 minutes to analyze all adocs.
There are two visible downsides:
* It is no longer clear which file is failing. This is mitigated by the fact that I renamed each `tmp.adoc` to contain the name of the rule and the language `tmp_S1234_cfamily.adoc`. The real problem should be handled by asciidoctor, but so far, the Issue on their side is stuck: https://github.com/asciidoctor/asciidoctor/issues/3414
* The analysis fails after the first error.
These downsides were considered reasonable because:
* For small changelists they are transparent (if you modify one rule, you know which file is touched and you probably don't have a lot of …
> Test to accelerate validation

- rules/S6403/message.adoc
To follow the message standard we have set up, I would suggest formulating a second message for this rule as well, highlighting the absence of an attribute/block.
> Add message for omitted attributes.

- .github/workflows/update_quickfix_status.yml
- docs/metadata.adoc
- rspec-tools/rspec_tools/cli.py
- rspec-tools/rspec_tools/create_rule.py
- rspec-tools/rspec_tools/errors.py
- rspec-tools/rspec_tools/modify_rule.py
- rspec-tools/rspec_tools/repo.py
- rspec-tools/rspec_tools/utils.py
- rspec-tools/tests/conftest.py
- rspec-tools/tests/resources/rules/S100/java/metadata.json
- rspec-tools/tests/test_cli.py
- rspec-tools/tests/test_coverage.py
- rspec-tools/tests/test_create_rule.py
- rspec-tools/tests/test_modify_rule.py
- rspec-tools/tests/test_repo.py
- rspec-tools/tests/test_rules_repository.py
- rspec-tools/tests/test_utils.py
This can be tested at https://github.com/marco-antognini-sonarsource/rspec/actions/workflows/update_quickfix_status.yml
When testing, the generated PRs will be on my fork as well.
For examples:
* https://github.com/marco-antognini-sonarsource/rspec/pull/2
* https://github.com/marco-antognini-sonarsource/rspec/pull/3
Mind you, the formatting of the metadata file is slightly altered (empty arrays are one-liners and `\/` is replaced by a simple `/`, which is equivalent AFAICT according to [JSON's spec](https://www.json.org/json-en.html)).
```diff
diff --git a/rules/S5954/cfamily/metadata.json b/rules/S5954/cfamily/metadata.json
index ea5c6c070e..2a9528357f 100644
--- a/rules/S5954/cfamily/metadata.json
+++ b/rules/S5954/cfamily/metadata.json
@@ -3,7 +3,7 @@
"type": "CODE_SMELL",
"status": …
```
> RULEAPI-748: Introduce GitHub Action to update quickfix status

- rules/S3776/see.adoc
- rules/S5871/rule.adoc
- rules/S6194/rule.adoc
Use the direct link to the pdf instead. Currently, both links are equivalent, but the redirection might not work in the future.
> Remove redirecting link to cognitive complexity white-paper

- rspec-tools/rspec_tools/coverage.py
- rspec-tools/rspec_tools/utils.py
- rspec-tools/tests/test_coverage.py
This removes the dependency on online repositories (on GitHub),
and speeds up the test by stripping the number of versions and files in them to a minimum.
Prepare ground for RULEAPI-753
> Mock analyzer repos for the coverage test

- docs/styling_guide.adoc
This PR adds a styling guide as discussed in the ["Language styling guide for RSPEC"](https://discuss.sonarsource.com/t/language-styling-guide-for-rspec/9640) circle.
This document aims to specify the most common use cases that we encounter, similar to the ["Associated Press Style Quick Reference Guide"](https://www.codot.gov/business/grants/safetygrants/assets/APStyleGuideCheatSheet.pdf). It is not and does not aim to be a full reference for every possible case.
> Add styling guide to docs

- rules/S5131/csharp/razor/rule.adoc
- rules/S5131/csharp/system.web/rule.adoc
- rules/S5131/java/javax.servlet.http/rule.adoc
- rules/S5131/java/jsp/rule.adoc
- rules/S5131/java/thymeleaf/rule.adoc
- rules/S5131/javascript/rule.adoc
- rules/S5131/php/laravel/rule.adoc
- rules/S5131/php/native/rule.adoc
- rules/S5131/php/symfony/rule.adoc
- rules/S5131/python/django/rule.adoc
- rules/S5131/python/dtl/rule.adoc
- rules/S5131/python/flask/rule.adoc
- rules/S5131/python/jinja/rule.adoc
I noticed some minor issues with the new skeleton:
- the name change on `threats.adoc` was not reflected in the files mentioning it
- The subsection "How does this work?" was not reflected as a subsection of "How to fix it?"
> Modify rule S5131(Education Framework): Fix typos

- docs/styling_guide.adoc
As discussed [here](https://discuss.sonarsource.com/t/styling-guide-use-of-backticks/10331), the consent in the Languages Team seems to be that inline literals should not be as strictly limited as it was done in the first version of the styling guide. Additionally, there is already a definition of this topic in the [SonarCloud Design System](https://zeroheight.com/3f9bf5b5a/p/375241-snippets).
To avoid having a guideline that conflicts with SonarCloud and that does not match the expectations of the people writing the rules, the conditions of inline literals were changed to be looser.
Additionally, a link to the description document was added.
> Adjust literals in styling guide to SC Design System

- rules/S6018/cfamily/rule.adoc
This is leftover from CPP-3035.
> Modify rule S6018: Clarify that constexpr variables are not inline.

- rules/S4524/cfamily/metadata.json
- rules/S4524/compliant.adoc
- rules/S4524/noncompliant.adoc
As part of the rule implementation - CPP-2004
Ticket for the quickfix: CPP-3690
> Modify rule S4524: highlight src and set quickfix to targeted

- rules/S1913/cfamily/metadata.json
- rules/S3135/cfamily/metadata.json
- rules/S3135/cfamily/rule.adoc
> CPP-220 S3135 "sizeof" should not be called on pointer parameters

- rules/S1199/cfamily/rule.adoc
Make the description more C++-oriented
Change the example (the previous one is now going to be compliant)
> CPP-2907 S1199: Rule is too strict for variables in case blocks

- rules/S5768/abap/rule.adoc
The link to the document is no longer available on SAP. The document linked was probably this one:
https://fdocuments.in/document/best-practice-guidecustom-abap-code-transition-to-sap-hana.html?page=1
The document gives only high-level performance advice. The rule violation is not part of the document. The link can be removed.
> Modify rule S5768: Remove broken link

- rules/S6423/csharp/rule.adoc
The LogError call in the compliant section is compiling, but it picks the wrong overload:
`LogError(ILogger, Exception, String, Object[])` should be called, but 
`LogError(ILogger, String, Object[])` is called instead.
Fixes https://community.sonarsource.com/t/67647/2
> Modify rule S6423: Swap arguments in LogError call in compliant solution

- rules/S1488/javascript/metadata.json
Remove S1488 for Javascript/Typescript from the Sonar way profile
> Modify rule S1488: Remove Javascript/Typescript from the Sonar way profile

- rules/S1117/javascript/metadata.json
Modify rule S1117: Remove rule for JavaScript/TypeScript from profile Sonar way
> Modify rule S1117: Remove rule for JavaScript/TypeScript from profile Sonar way

- rules/S6420/csharp/metadata.json
- rules/S6424/csharp/metadata.json
Some new rules for Azure Functions don't follow the *X shou [not] Y* naming scheme.
> Modify rules S6424 and S6420: Change titles

- rules/S1186/javascript/rule.adoc
Fixes SonarSource/SonarJS#3241
> Modify rule S1186: Add exception for empty functions.

- rules/S3358/javascript/rule.adoc
Fixes SonarSource/SonarJS#3244
> Modify rule S3358: Add exception for JSX expressions.

- rules/S4144/javascript/rule.adoc
Fixes SonarSource/SonarJS#3288
> Modify rule s4144: Add exception for identical functions.

- rules/S5334/common/fix/introduction.adoc
- rules/S5334/csharp/how-to-fix-it/dotnet.adoc
- rules/S5334/csharp/rule.adoc
I decided against using the "pre-approved" fix because it is not realistic. Instead I tried to come up with a way to get user input into dynamic code without making it part of the code. I will rework the Java code sample and do the same there.
> [APPSEC-80] Modify rule S5334: Educational content (C#)

- rspec-tools/rspec_tools/checklinks.py
- rules/S6336/recommended.adoc
There is a typo in the accept header of the script. Most servers seem to be fine with it, but https://www.alibabacloud.com/help/en/key-management-service/latest/secrets-manager-overview returned
`HTTP Error 406: Not Acceptable`
with the broken accept-header. I updated the header using the F12 tools from google chrome.
The status code and Accept header can be checked via curl:
```sh
curl --insecure -H "Accept:text/html" -sSL -D - https://www.alibabacloud.com/help/en/key-management-service/latest/secrets-manager-overview -o /dev/null
curl --insecure -H "Accept:broken" -sSL -D - https://www.alibabacloud.com/help/en/key-management-service/latest/secrets-manager-overview -o /dev/null
```
> checklinks.py Fix broken Accept header

- rules/S1313/python/rule.adoc
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARPY-1073
This change is separated by language because the different languages will not implement the exception at the same time.
> Modify rule S1313: Add exceptions for ranges used for documentation purposes

- rules/S5764/java/rule.adoc
The original link talking about the rationale of the rule is no longer active. Following the discussion [here](https://sonarsource.atlassian.net/browse/RSPEC-5764) I have replaced the link.
> Modify rule S5764: Remove and replace broken link

- rules/S1117/php/metadata.json
We decided to drop the rule for PHP based on discussion triggered by https://community.sonarsource.com/t/whats-the-logic-behind-php-s1117/68963
> Modify S1117: Deprecate rule for PHP

- rules/S6419/csharp/metadata.json
- rules/S6420/csharp/metadata.json
- rules/S6421/csharp/metadata.json
- rules/S6422/csharp/metadata.json
- rules/S6423/csharp/metadata.json
- rules/S6424/csharp/metadata.json
The PR adds the missing "azure" tag to the rules for "Azure Functions". The list of rules is taken from
https://sonarsource.atlassian.net/browse/MMF-2699
See also https://sonarsource.slack.com/archives/C012KBFFYD6/p1661180705206739
> Modify rules: Add "azure" tag to "Azure Functions" rules

- rules/S4138/javascript/rule.adoc
Fixes https://github.com/SonarSource/SonarJS/issues/3385
> Modify rule S4138: Include warning about browser array-like collections in TypeScript

- rules/S4421/plsql/rule.adoc
EXTRACT was removed from the rule for now, as it was creating false positives.
> Modify rule S4421: Remove EXTRACT from the list of deprecated functions.

- rules/S1313/swift/rule.adoc
Fixes https://sonarsource.atlassian.net/browse/SONARSWIFT-527
> Modify rule S1313: Add exceptions for IPv6 ranges used for documentation purposes

- rules/S5362/css/metadata.json
Fixes https://github.com/SonarSource/SonarJS/issues/3470
> Deprecate Rule css:S5362 (`function-calc-no-invalid`)

- rules/S1694/csharp/rule.adoc
The comment is misleading as a private constructor is too restrictive.
> Modify rule S1694 (CS): correct code comment in sample

- rules/S3871/csharp/rule.adoc
- rules/S3871/exceptions.adoc
- rules/S3871/see.adoc
- rules/S3871/vbnet/rule.adoc
Rule API has some inconsistent whitespace handling. 
Bug filed here: https://sonarsource.atlassian.net/jira/software/c/projects/RULEAPI/issues/RULEAPI-772
This workaround demonstrates itself like this in VB file: https://github.com/SonarSource/sonar-dotnet/pull/5822/commits/af6634cc3593c861a2bf1f2a26828533839526e5
> Update S3871: Fix whitespace

- rules/S6258/terraform/rule.adoc
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARIAC-418
The new implementation does not raise an issue for AWS provider >= 4, so the issues reported for this rule will slowly dry out. Since there are already a lot of code samples for this rule, I decided to combine the compliant solution for both versions.
> Modify rule S6258: Add new Terraform code sample

- rules/S6245/terraform/rule.adoc
Implementation ticket: https://sonarsource.atlassian.net/browse/SONARIAC-417
The new implementation does not raise an issue for AWS provider >= 4, so the issues reported for this rule will slowly dry out. At some point, we can deprecate and remove this rule unless the detection logic gets improved.
> Modify rule S6245: Add new Terraform code sample

- rules/S5334/csharp/how-to-fix-it/dotnet.adoc
Gets rid of [unnecessary diffing colors in SQ](https://next.sonarqube.com/sonarqube/coding_rules?q=S5334&open=roslyn.sonaranalyzer.security.cs%3AS5334).
> Modify Rule S5334(Csharp): Fix sample typo

- rules/S3456/csharp/highlighting.adoc
- rules/S3456/csharp/message.adoc
- rules/S3456/csharp/metadata.json
- rules/S3456/csharp/rule.adoc
Added the necessary changes to support `utf8_string.ToArray()`, as can be seen on [this PR](https://github.com/SonarSource/sonar-dotnet/issues/6392).
> Modify rule S3456: Raise on ReadOnlySpan.ToArray() 

- README.adoc
The replacementRule part isn't specifying the rule id format:
```json
"extra": {
"replacementRules": [
"RSPEC-4200" // or "S4200" or "RSPEC-S4200"? 😕 
],
"legacyKeys": [
]
},
```
Also, a link to an existing example helps with cross-checking.
> Readme: Clarify rule deprecation

- rules/S3353/csharp/metadata.json
Marks the quick fix implemented by https://github.com/SonarSource/sonar-dotnet/pull/6043 as partially implemented. Some edge cases with e.g. multiple declarators are not supported. See also https://github.com/SonarSource/rspec/blob/master/docs/metadata.adoc
> Modify rule S3353: Mark quickfix for CSharp as partially covered

- rules/S1612/java/rule.adoc
When a lambda function is shorter than its equivalent method reference, the code is considered compliant and no issue is raised.
> Modify rule S1612 (Java): Short lambdas are considered compliant

- rules/S3654/cfamily/rule.adoc
Adjust rule description: throwing an exception in a destructor is not necessarily undefined behavior. However, it is highly dangerous to throw in a destructor. This PR also adds an example on why that is.
> Modify rule S3654: Improve on rule description (CPP-3734)

- rules/S1168/csharp/description.adoc
- rules/S1168/csharp/rule.adoc
Added the necessary changes to support the following cases:
```csharp
return default;
return default(T);
return condition ? null : someResult;
```
More can be found on [this PR](https://github.com/SonarSource/sonar-dotnet/pull/6457).
> Modify rule S1168: Raise on default and ternaries

- rules/S4018/message.adoc
- rules/S4018/metadata.json
- rules/S4018/rule.adoc
The rule's message and description were too vague. They didn't make it clear that the type parameters need to be used in the argument list in order to enable type inference when the method is called. Those texts in the rule were updated to reflect that.
Implementation ticket: SonarSource/sonar-dotnet/issues/6636
> Modify rule S4018: modify message to make it clear the rule is about type inference

- rules/S6493/cfamily/rule.adoc
I don't think "non-user-defined type" is what was intended here. If you consider any class or enum type to be "user-defined" then `std::string` *is* user-defined. If the term is being used to mean "not defined by the implementation" then that's not relevant here, because that isn't what determines whether it dangles in this code or not.
> Fix comment in S6493 code example

- rules/S4457/comments-and-links.adoc
- rules/S4457/csharp/metadata.json
- rules/S4457/csharp/rule.adoc
- rules/S4457/metadata.json
- rules/S4457/vbnet/rule.adoc
After [this discussion](https://github.com/SonarSource/sonar-dotnet/issues/6132) and internal talk with the .NET Bubble, we decided to disable this rule by default.
https://sonarsource.github.io/rspec/#/rspec/S4457/csharp
> Modify Rule S4457(C#): Remove from Sonar way Profile

- rspec-tools/rspec_tools/checklinks.py
- rules/S5935/php/rule.adoc
Some of the rules contain dead links, which causes the PR checks to fail.
> Modify rule S5935: Fix dead link

- rules/S1181/cfamily/rule.adoc
- rules/S1181/see.adoc
* Split "See" section between C++&Java, therefore removing a C++ specific link that appeared for Java
* Restore the removed link in the Java version
> Modify rule S1181: Correct the "See" section

- rules/S3400/java/rule.adoc
refined exceptions for the rule
> Modify rule S3400: Methods should not return constants

- rules/S5860/javascript/rule.adoc
This change follows a feedback from a user (See thread [side note](https://community.sonarsource.com/t/typescript-s5860-not-considering-access-via-index-syntax/82684)).
> Modify rule S5860: Improve documentation

- rules/S2166/csharp/rule.adoc
- rules/S2166/vbnet/rule.adoc
https://github.com/SonarSource/sonar-dotnet/issues/6705
> S2166: Add C# and VB.NET

- rules/S2166/csharp/message.adoc
- rules/S2166/csharp/rule.adoc
- rules/S2166/vbnet/message.adoc
- rules/S2166/vbnet/rule.adoc
https://github.com/SonarSource/sonar-dotnet/issues/6705
> Improve S2166: update message and sample code

- rules/S2198/csharp/comments-and-links.adoc
- rules/S2198/csharp/rule.adoc
- rules/S2198/rule.adoc
Rule implementation: https://github.com/SonarSource/sonar-dotnet/issues/6658
> S2198: Add C#

- rules/S2970/csharp/rule.adoc
- rules/S2970/description.adoc
Implementation: https://github.com/SonarSource/sonar-dotnet/issues/6662
[S2970](https://sonarsource.github.io/rspec/#/rspec/S2970/)
> Modify rule S2970: Improve description of supported test library functions

- rules/S131/plsql/metadata.json
- rules/S131/plsql/rule.adoc
- rules/S5663/java/rule.adoc
- rules/S5664/java/rule.adoc
- rules/S5665/java/rule.adoc
- rules/S6126/java/rule.adoc
- rules/S6203/java/rule.adoc
Someone opened [this thread](https://community.sonarsource.com/t/case-expressions-should-end-with-else-clauses-plsql-s131/83156) in community asking to replace the word `expression` with the word `statements`.
Based on [SONARPLSQL-757](https://sonarsource.atlassian.net/browse/SONARPLSQL-757) it's indeed the case.
[SONARPLSQL-757]: https://sonarsource.atlassian.net/browse/SONARPLSQL-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S131(PLSQL): Change title to fit implementation

- rules/S2094/csharp/rule.adoc
- rules/S2094/vbnet/rule.adoc
https://github.com/SonarSource/sonar-dotnet/issues/6704
> Improve S2094: Add exceptions

- rules/S2137/javascript/rule.adoc
The rule now checks for JavaScript standard built-in identifiers instead of the list previously defined in the rule. The code samples have been updated to use `const`/`let` instead of `var`. The rule actually doesn't check function constructor calls, so the corresponding code examples have been removed: `new Function("arguments", "return 17;")`.
Fixes SonarSource/SonarJS#3708
> Modify rule S2137: Change text to include JavaScript standard builtins

- rules/S1472/javascript/rule.adoc
The change adds a paragraph about tagged template literals.
Fixes SonarSource/SonarJS#3705
> Modify rule S1472: Add tagged template literals

- docs/metadata.adoc
Add a link to the **Coding rule guidelines** article on [docs.sonarqube](https://docs.sonarqube.org/latest/extension-guide/adding-coding-rules/#coding-rule-guidelines).
> metadata.adoc: add link to the Coding rule guidelines on SonarQube

- rules/S2198/cfamily/metadata.json
- rules/S2198/metadata.json
Make MISRA-related information CFamily-specific
> Modify rule S2198

- rules/S2492/plsql/rule.adoc
This is a fix for [this issue](https://discuss.sonarsource.com/t/parse-error-on-noncompliant-example-of-plsql-namingtypescheck/12627)
> Modify rule S2492: Fix the noncompliant example (PLSQL-S2492)

- rules/S5659/java/metadata.json
Remove CERT tag as no link to the CERT is present in the documentation.
> Modify rule S5659: Remove CERT tag

- rules/S2326/java/metadata.json
Remove tag as no link to the CERT documentation can be found in the description
> Modify rule S2326: Remove CERT tag

- rules/S2589/java/metadata.json
Remove CERT tag as no link to the CERT is present in the documentation.
> Modify rule S2589: Remove CERT tag

- rules/S6544/javascript/rule.adoc
Fixes [#3891](https://github.com/SonarSource/SonarJS/issues/3891)
> Modify rule S6544: remove mention of error handling, which we will not cover anymore

- .github/workflows/update_coverage.yml
* Replace usage of set-output 
That way it will still work[ after 31st of May](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
> BUILD-2950 Adapt rspec replace set-output (deprecated)

- rules/S2430/javascript/metadata.json
The rule was not part of the default quality profile (Sonar way), so we want to fix that
> Modify rule S2430: add to default profile, change quickfix to infeasible

- rules/S6493/cfamily/rule.adoc
Note: Given what the [introduction](https://xtranet-sonarsource.atlassian.net/wiki/spaces/PM/pages/2715320326/LaYC+Rule+Content+Specification#Introduction.1) should be, I don't think it is a good fit here...
> Modify rule S6493: LaYC format

- rules/S5384/apex/rule.adoc
This PR fixes a broken URL in S5384 by replacing it with an Internet Archive link to the same page.
[Preview](https://sonarsource.github.io/rspec/#/rspec/S5384/apex)
> Modify rule S5384: fix broken URL

- rules/S4159/csharp/metadata.json
- rules/S4159/csharp/rule.adoc
- rules/S4159/description.adoc
- rules/S4159/metadata.json
- rules/S4159/resources.adoc
- rules/S4159/vbnet/metadata.json
- rules/S4159/vbnet/rule.adoc
- rules/S4159/why.adoc
Adapts the rule to LaYC format level 2, for dotnet languages (csharp, vbnet).
> Modify rule S4159: LaYC format

- rules/S1909/comments-and-links.adoc
- rules/S1909/csharp/metadata.json
See [this conversation](https://github.com/SonarSource/sonar-dotnet/issues/6661) for more details.
> S1909: Remove C# since the rule is not applicable 

- rules/S2157/java/rule.adoc
- rules/S2165/java/metadata.json
> Modify rule S2157: Reworked into new educational format

- rules/S1215/csharp/metadata.json
- rules/S1215/csharp/rspecator.adoc
- rules/S1215/csharp/rule.adoc
Adapts the rule to LaYC format level 2, for csharp.
> Modify rule S1215: LaYC format

- rules/S3265/csharp/rule.adoc
- rules/S3265/rspecator.adoc
Update rule content and descriptions to LaYC format.
https://sonarsource.github.io/rspec/#/rspec/S3265
> Modify rule S3265: LaYC format

- rules/S3464/csharp/rule.adoc
- rules/S3464/rspecator.adoc
- rules/S3464/vbnet/rule.adoc
> Modify rule S3464: fix grammar, links, resources, rspecator

- rules/S2234/csharp/compliantCode.adoc
- rules/S2234/csharp/metadata.json
- rules/S2234/csharp/noncompliantCode.adoc
- rules/S2234/csharp/rule.adoc
- rules/S2234/rspectator.adoc
- rules/S2234/vbnet/compliantCode.adoc
- rules/S2234/vbnet/metadata.json
- rules/S2234/vbnet/noncompliantCode.adoc
- rules/S2234/vbnet/rule.adoc
- rules/S2234/why-dotnet.adoc
Update [S2234](https://sonarsource.github.io/rspec/#/rspec/S2234) to LaYC format
> Modify rule S2234: LaYC format

- rules/S4275/csharp/rule.adoc
- rules/S4275/metadata.json
- rules/S4275/vbnet/metadata.json
- rules/S4275/vbnet/rule.adoc
Update rule content and descriptions to LaYC format.
[S4275: Getters and setters should access the expected fields](https://sonarsource.github.io/rspec/#/rspec/S4275)
> Modify rule S4275: LaYC format

- rules/S3445/csharp/rule.adoc
- rules/S3445/rspecator.adoc
> Modify rule S3445: LaYC format

- rules/S2692/vbnet/rule.adoc
> Modify rule S2692: align C# and VB.NET examples

- rules/S4277/vbnet/rule.adoc
> Modify rule S4277: Fix vbnet diff tag 

- rules/S3451/csharp/rule.adoc
> Modify rule S3451: fix wrong link

- ci/replace_variables_in_path.sh
- ci/validate_asciidoc.sh
The point of this branch is the second commit that changes validate_asciidoc.sh. The first one is taken from another PR and should not be reviewed.
The previous version of the validation could handle the following case:
```asciidoc
:path: path/to/file.adoc
include::{path}[]
```
This new validation also adds support for the case of a variable inside a path:
```asciidoc
:language: csharp
include::rules/S1000/{language}/file.adoc[]
```
> Handle variables *inside* an include

- rules/S5146/python/how-to-fix-it/flask.adoc
I couldn't get Sonarcloud to trigger this issue using the provided noncompliant code example. 
I think the code examples as written end up being circular because the local function 'redirect()' will call itself rather than the imported 'redirect()' function of the same name. The fix is to change the local function name to be redirecting(). I changed the API endpoint name as well so that it matched. Once I had made this change, the noncompliant code example did lead to Sonarcloud spotting the issue.
> Modify rule S5146: Fix invalid Python sample

- rules/S6385/azureresourcemanager/rule.adoc
- rules/S6385/highlighting.adoc
While working on SONARIAC-772 I've found a couple of issues with the RSPEC for S6385 for ARM. This PR fixes them:
* Change resource type name from the one copied from Terraform to the one applicable in ARM
* Fix formatting in bullet point list
Implementation ticket: SONARIAC-772, PR using this fix https://github.com/SonarSource/sonar-iac/pull/767
> Modify rule S6385: Change resource type, fix formatting

- rules/S5707/python/rule.adoc
> Modify rule S5707: LaYC format

- docs/link_formatting.adoc
Rule IDs are [automatically transformed](https://github.com/SonarSource/sonar-rule-api/blob/master/src/main/java/com/sonarsource/ruleapi/asciidoctor/AsciiDoctorConverter.java#L111) into link placeholders by rule-api. These placeholders are translated into autolinks by the products.
If these IDs appear within other links, it might [break some products](https://discuss.sonarsource.com/t/cross-rule-references-inside-a-tags-in-html-rule-descriptions/14971/4).
Moreover, the generated autolinks are product-specific, and cannot be encoded statically in the rule description.
> Fix the rule-id link format

- docs/description.adoc
Indent sections in the rule description guide to improve readability.
Cross-reference the link standard in the rule description guide.
> Cross reference guides and cosmetics improvements

- rules/S6487/cfamily/rule.adoc
> Modify rule S6487: LaYC format

- rules/S961/cfamily/rule.adoc
> Modify rule S961: LaYC format

- rules/S2109/java/metadata.json
- rules/S2109/java/rule.adoc
Before:
https://next.sonarqube.com/sonarqube/coding_rules?q=s2109&open=java%3AS2109
After:
> Modify rule S2109(Java): Update rule according to the LayC

- rules/S5972/cfamily/rule.adoc
> Modify rule S5972: LaYC format

- rules/S3923/exceptions.adoc
> modify-rule-layc-S3923

- rules/S6459/cfamily/rule.adoc
> Modify rule S6459: LaYC format

- rules/S2990/javascript/rule.adoc
> Modify rule S2990: Fix typo

- rules/S836/cfamily/rule.adoc
> Modify rule S836: Adapt to LaYC

- rules/S6490/cfamily/rule.adoc
> Modify rule S6490: LaYC format

- rules/S1679/cfamily/rule.adoc
> Modify rule S1679: LaYC format

- rules/S6328/javascript/rule.adoc
> Modify rule S6328: Remove Noncompliant section

- rules/S125/csharp/metadata.json
Fix I forgot to do when merging [the PR](https://github.com/SonarSource/sonar-dotnet/pull/6966) that implemented the codefix.
> Modify S125: Set quickfix field for C#

- rules/S2190/csharp/rule.adoc
> Modify rule S2190: fix typo

- rules/S1232/cfamily/metadata.json
- rules/S1232/cfamily/rule.adoc
> Modify rule S1232: Expand and comply with LaYC format

- rules/S2323/cfamily/rule.adoc
I felt the "how to fix it" section was unnecessary given how trivial this is. Let me know if you disagree.
> Modify rule S2323: LaYC format

- rules/S1186/csharp/notimplemented-code.adoc
Related to [this community PR](https://github.com/SonarSource/sonar-dotnet/pull/7587).
> Modify rule S1186: Fix exception type

- ci/validate_asciidoc.sh
This PR is a prerequisite for:
* #2685
---
* Regroup readonly variable declaration. `declare -xr` is used for exported readonly variable.
* Use more accurate log messages.
* Use consistent indentation of 2 spaces.
* Fail fast if dependencies cannot be installed.
* Regroup HTML generation & its validation.
* Document the main validation points.
* Simplify some commands and address some ShellCheck warnings.
> Clean ci/validate_asciidoc.sh

- rules/S6666/javascript/metadata.json
> Modify rule S6666: Quote method's name in rule title

- rules/S108/javascript/code-example.adoc
- rules/S108/javascript/rule.adoc
> Modify rule S108: Fix exceptions section and replace 'var' with 'let'

- rules/S6647/javascript/rule.adoc
> Modify rule S6647: Add diff-tag and fix noncompliant comment

- rules/S6676/javascript/metadata.json
> Modify rule S6676: Quote methods' names in rule title

- rules/S6645/javascript/rule.adoc
> Modify rule S6645: Fix noncompliant comments and links' titles

- rules/S3799/javascript/rule.adoc
> Modify rule S3799: Use let instead of var in noncompliant snippet

- rules/S1916/cfamily/rule.adoc
- rules/S2323/cfamily/rule.adoc
- shared_content/cfamily/line_splicing.adoc
> Modify rule S1916: LaYC format

- rules/S2107/cfamily/metadata.json
- rules/S2107/cfamily/rule.adoc
- rules/S2107/java/metadata.json
- rules/S2107/java/rule.adoc
- rules/S2107/metadata.json
- rules/S836/cfamily/rule.adoc
- shared_content/cfamily/garbage_value_impact.adoc
I moved and closed the Java rule description because they do not plan to implement it, but it is nice to preserve the description for posterity.
> Modify rule S2107: Expand and adjust for LaYC

- rules/S5314/cfamily/metadata.json
- rules/S5314/cfamily/rule.adoc
I was thinking of these words as "glossary":
* blocking
* critical-section
* data race
* mutual exclusion
> Modify rule S5314: Expand and adjust for LaYC

- .vscode/settings.json
Adds json schema support for VS Code (especially [IntelliSense and validation](https://code.visualstudio.com/docs/languages/json#_intellisense-and-validation)):
> Add VS code schema support for manifest.json

- rules/S2734/python/metadata.json
S935 has been merged with S6658.
As part of that merge, S935 has been restricted to a specific set of special functions for now, not including `__init__`.
Hence, we keep S2734 at the moment, until S935 is extended to cover more functions.
See also
* https://github.com/SonarSource/sonar-python/pull/1529#discussion_r1282759218
* https://github.com/SonarSource/sonar-python/pull/1528
* https://sonarsource.slack.com/archives/CFUS31LRE/p1690534750237959
> Modify rule S2734: Python: Don't replace with S935

- rules/S3807/cfamily/metadata.json
- rules/S3807/cfamily/rule.adoc
Few updates I have missed during review, and just realized when saw sonar-cpp PR:
* we should check quickfix, and mark if infeasible if we think that one could be provided
* metadata now contains links to security standards, so I updated it
* pre https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc, CWE should start with CWE
* I think that CWE and CERT are put under standard, external conding guidelines are use for MISRA and CoreGuidlines.
> S3870 Update metadata

- rules/S3520/cfamily/rule.adoc
- rules/S6214/cfamily/metadata.json
- rules/S6214/cfamily/rule.adoc
> Modify rule S6214: Convert to LaYC format

- rules/S5485/cfamily/metadata.json
- rules/S5485/cfamily/rule.adoc
> Modify rule S5485: Expand and adjust for LaYC

- rules/S2638/java/rule.adoc
- rules/S2638/python/rule.adoc
> Modify rule S2638: LaYC format

- rules/S3871/why-dotnet.adoc
> Modify rule S3871: fix orthography

- rules/S3466/vbnet/rule.adoc
- rules/S3598/vbnet/rule.adoc
- rules/S3927/vbnet/rule.adoc
> Modify S3466,S3598,S3927(vbnet): Fix diff typos

- shared_content/secrets/resources/standards.adoc
To comply with https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc.
> Use new link format for secret resources

- rules/S3034/java/rule.adoc
> Modify rule S3034: added some missing backticks

- rules/S4423/cloudformation/how-to-fix-it/opensearch.adoc
> Diff blocks: fix incorrect use for cloudformation

- rules/S4423/docker/how-to-fix-it/wget.adoc
- rules/S6579/docker/rule.adoc
>  A single and unique diff-id should be used only once for each type of code example as shown in the description of a rule. 
Obvious typos around `diff-id` were fixed.
---
> Diff blocks: fix some incorrect use for docker

- rules/S2076/php/how-to-fix-it/symfony.adoc
- rules/S2078/php/how-to-fix-it/symfony.adoc
- rules/S3649/php/how-to-fix-it/laravel.adoc
- rules/S4830/php/how-to-fix-it/curl.adoc
- rules/S5131/php/how-to-fix-it/laravel.adoc
- rules/S5131/php/how-to-fix-it/symfony.adoc
- rules/S5135/php/how-to-fix-it/laminas.adoc
- rules/S5144/php/how-to-fix-it/guzzle.adoc
- rules/S5146/php/how-to-fix-it/laravel.adoc
- rules/S5146/php/how-to-fix-it/symfony.adoc
- rules/S5542/php/how-to-fix-it/openssl.adoc
- rules/S5547/php/how-to-fix-it/openssl.adoc
- rules/S6287/php/how-to-fix-it/laravel.adoc
- rules/S6287/php/how-to-fix-it/symfony.adoc
Obvious typos around `diff-type` were fixed. 
---
> Diff blocks: fix some incorrect use for php

- rules/S4423/terraform/how-to-fix-it/aws-opensearch.adoc
- rules/S4423/terraform/how-to-fix-it/azure-mssql.adoc
- rules/S4423/terraform/how-to-fix-it/gcp-lb.adoc
>  A single and unique diff-id should be used only once for each type of code example as shown in the description of a rule. 
---
> Diff blocks: fix some incorrect use for terraform

- rules/S1214/java/rule.adoc
- rules/S1602/java/rule.adoc
- rules/S2076/java/how-to-fix-it/java-se.adoc
- rules/S2157/java/rule.adoc
- rules/S2186/java/rule.adoc
- rules/S2230/java/rule.adoc
- rules/S2254/java/rule.adoc
- rules/S2272/java/rule.adoc
- rules/S2755/java/how-to-fix-it/jdom2.adoc
- rules/S3649/java/how-to-fix-it/java-se.adoc
- rules/S3649/java/how-to-fix-it/spring-jdbc.adoc
- rules/S4423/java/how-to-fix-it/okhttp.adoc
- rules/S5131/java/how-to-fix-it/servlet.adoc
- rules/S5131/java/how-to-fix-it/spring.adoc
- rules/S5131/java/how-to-fix-it/thymeleaf.adoc
- rules/S5527/java/how-to-fix-it/java-ee.adoc
- rules/S5527/java/how-to-fix-it/java-se.adoc
- rules/S5659/java/how-to-fix-it/jjwt.adoc
- rules/S5883/java/how-to-fix-it/java-se.adoc
- rules/S6398/java/how-to-fix-it/gson.adoc
- rules/S6398/java/how-to-fix-it/java-se.adoc
Obvious typos around `diff-type` and `diff-id` were fixed. 
---
> Diff blocks: fix some incorrect use for java

- rules/S5912/cfamily/rule.adoc
Given the nature of the bug is easy to understand, I didn't feel it was worth explicitly mentioning this is makes the application unreliable. Let me know if you disagree.
> Modify rule S5912: LaYC format

- rules/S1314/javascript/rule.adoc
- rules/S2076/javascript/how-to-fix-it/ssh2.adoc
- rules/S2083/javascript/how-to-fix-it/node.adoc
- rules/S2999/javascript/rule.adoc
- rules/S3649/javascript/how-to-fix-it/sequelize.adoc
- rules/S4423/javascript/how-to-fix-it/node-js.adoc
- rules/S4830/javascript/how-to-fix-it/request.adoc
- rules/S5147/javascript/how-to-fix-it/mongoose.adoc
- rules/S5334/javascript/how-to-fix-it/node.adoc
- rules/S6439/javascript/rule.adoc
Obvious typos around `diff-type` were fixed. 
---
> Diff blocks: fix some incorrect use for javascript

- rules/S2755/cfamily/how-to-fix-it/xerces.adoc
- rules/S4423/cfamily/how-to-fix-it/curl.adoc
- rules/S4423/cfamily/how-to-fix-it/openssl.adoc
- rules/S4426/cfamily/how-to-fix-it/cryptopp.adoc
- rules/S4426/cfamily/how-to-fix-it/openssl.adoc
- rules/S4830/cfamily/how-to-fix-it/curl.adoc
- rules/S4830/cfamily/how-to-fix-it/openssl.adoc
- rules/S5527/cfamily/how-to-fix-it/curl.adoc
- rules/S5527/cfamily/how-to-fix-it/openssl.adoc
- rules/S5542/cfamily/how-to-fix-it/cryptopp.adoc
- rules/S5542/cfamily/how-to-fix-it/openssl.adoc
- rules/S5547/cfamily/how-to-fix-it/cryptopp.adoc
- rules/S5547/cfamily/how-to-fix-it/openssl.adoc
- rules/S5553/cfamily/rule.adoc
Obvious typos around `diff-type` were fixed.
> Diff blocks: fix incorrect use for cfamily

- rules/S5547/swift/how-to-fix-it/cryptoswift.adoc
- rules/S5547/swift/how-to-fix-it/idzswiftcommoncrypto.adoc
> Diff blocks: fix incorrect use for swift

- rules/S2187/csharp/how-nunit.adoc
- rules/S3649/csharp/how-to-fix-it/entity-framework.adoc
- rules/S3877/csharp/rule.adoc
- rules/S5131/csharp/how-to-fix-it/razor.adoc
- rules/S5547/csharp/how-to-fix-it/dot-net.adoc
Remove an obviously unused diff block.
---
> Diff blocks: fix some incorrect use for csharp

- rules/S3904/vbnet/rule.adoc
- rules/S5547/vbnet/how-to-fix-it/dot-net.adoc
Obvious typos around `diff-type` were fixed.
> Diff blocks: fix incorrect use for vbnet

- rules/S6632/kotlin/rule.adoc
> Diff blocks: fix incorrect use for kotlin

- rules/S935/python/metadata.json
There was an "S" in front of the rule number in the "ruleSpecification" value for the python version of the rule. I.e. "RSPEC-S935" -> "RSPEC-935".
This caused problems with the deployment of the rules marketing website: http://rules.sonarsource.com/
> Modify rule S935: Fix ruleSpecification value in metadata

- rules/S107/javascript/rule.adoc
> Modify rule S107: Do not count TypeScript parameter properties

- frontend/src/deployment/__tests__/metadata.test.ts
- frontend/src/deployment/metadata.ts
For some rules, rule-specific metadata.json overridden the `sqKey` for all languages, so when the predeployment script collected all keys, it did not list the actual, most canonical key "S****".
This leads to the incorrect display of coverage information on a rule page that relies on the `allKeys` precomputed property to retrieve the version of the analyzer that implements the rule.
The fix includes the generic rule metadata.json file into the aggregator that computes `allKeys`, thus propagating it to every language-specific metadata.
> Fix rule coverage on a rule page: include all rule keys to metadata

- rules/S3329/common/fix/fix.adoc
> APPSEC-843 Modify S3329: Mention FIPS-compliant PRNG

- rules/S2931/rule.adoc
Fixing tabs on Compliant solution snippet (it was showing `$nbsp;`)
> S2931: fix spacing

- rules/S2076/python/how-to-fix-it/python.adoc
- rules/S2091/python/how-to-fix-it/python.adoc
- rules/S2755/python/how-to-fix-it/std.adoc
- rules/S3329/python/how-to-fix-it/pycryptodome.adoc
- rules/S3649/python/how-to-fix-it/sqlite3.adoc
- rules/S4423/python/how-to-fix-it/openssl.adoc
- rules/S4423/python/how-to-fix-it/ssl.adoc
- rules/S4830/python/how-to-fix-it/openssl.adoc
- rules/S4830/python/how-to-fix-it/requests.adoc
- rules/S4830/python/how-to-fix-it/std.adoc
- rules/S5131/python/how-to-fix-it/dtl.adoc
- rules/S5131/python/how-to-fix-it/flask.adoc
- rules/S5131/python/how-to-fix-it/jinja.adoc
- rules/S5135/python/how-to-fix-it/yaml.adoc
- rules/S5144/python/how-to-fix-it/requests.adoc
- rules/S5145/python/how-to-fix-it/python.adoc
- rules/S5146/python/how-to-fix-it/flask.adoc
- rules/S5542/python/how-to-fix-it/pycrypto.adoc
- rules/S5542/python/how-to-fix-it/pycryptodome.adoc
- rules/S5542/python/how-to-fix-it/pydes.adoc
- rules/S5547/python/how-to-fix-it/pyca.adoc
- rules/S5547/python/how-to-fix-it/pycrypto.adoc
- rules/S5547/python/how-to-fix-it/pydes.adoc
- rules/S5659/python/how-to-fix-it/python-jwt.adoc
Obvious typos around `diff-type` were fixed.
An obvious extra use of diff blocks was removed.
> Diff blocks: fix incorrect use for python

- rules/S5488/cfamily/metadata.json
- rules/S5488/cfamily/rule.adoc
> Modify rule S5488: Expand and adjust for LaYC

- rules/S3588/cfamily/metadata.json
- rules/S3588/cfamily/rule.adoc
> Modify rule S3588: Expand and adjust for LaYC

- rules/S2589/vbnet/rule.adoc
Related to [this discuss post](https://discuss.sonarsource.com/t/layc-diff-view-validation/15392/2?u=antonio.aversa).
> Modify rule S2589: fix missing diff-id

- rules/S6416/java/metadata.json
- rules/S6416/java/rule.adoc
`IllegalStateException`s are thrown in situations very similar to `IllegalArgumentException`, except that they usually depend on conditions regarding the fields of an object instead of a method's parameters.
This PR adjusts the rule to include `IllegalStateException` as DBD is currently working on an implementation of said extension. 
> Modify rule S6416: Also check for IllegalStateException

- rules/S2255/csharp/metadata.json
- rules/S2255/vbnet/metadata.json
Deleting S2255 as it has been deprecated.
-  sonar-dotnet 8.9.0.19135, released on Jun 26, 2020
- SQ 8.4.0.35506 on Jul 3, 2020.
> Modify S2255: Delete

- rules/S2259/cfamily/metadata.json
- rules/S2259/cfamily/rule.adoc
- rules/S2259/description.adoc
- rules/S3807/cfamily/rule.adoc
> Modify rule S2259: Expand and adjust for LaYC

- rules/S3776/csharp/metadata.json
- rules/S3776/vbnet/metadata.json
Use default remediation, similar to the other rules.
Current default remediation is:
```
"remediation": {
"func": "Linear with offset",
"linearDesc": "per complexity point over the threshold",
"linearOffset": "5min",
"linearFactor": "1min"
},
```
> Modify rule S3776: use default remediation

- rules/S6326/javascript/metadata.json
Forgot to update the RSPEC while introducing quick fix support for S6326 in https://github.com/SonarSource/SonarJS/pull/4096
> Modify rule S6326: Add support for quick fixes

- rules/S2095/cfamily/rule.adoc
- rules/S2095/metadata.json
- rules/S3588/cfamily/rule.adoc
- shared_content/cfamily/c_file_io_raii_extra_mile.adoc
> Modify rule S2095: Expand and adjust for LaYC

- rules/S2091/common/resources/articles.adoc
- rules/S6700/secrets/rule.adoc
The ambionics link started to work again and I still kept the fix because the wayback machine is still always more reliable
> Modify S7000&S2091: Fix resource links

- rules/S6661/python/metadata.json
> Modify rule S6661(Python): Fixing typo in title

- rules/S3884/metadata.json
> Deprecate rule S3884

- rules/S4787/csharp/metadata.json
- rules/S4787/vbnet/metadata.json
Deleting S4787 as it has been deprecated.
sonar-dotnet 8.9.0.19135, released on Jun 26, 2020
SQ 8.4.0.35506 on Jul 3, 2020.
> Modify S4787: Delete

- rules/S4818/csharp/metadata.json
- rules/S4818/vbnet/metadata.json
Deleting S4818 as it has been deprecated.
sonar-dotnet 8.9.0.19135, released on Jun 26, 2020
SQ 8.4.0.35506 on Jul 3, 2020.
> Pull requests list  Modify S4818: Delete 

- rules/S6597/docker/metadata.json
- rules/S6597/docker/rule.adoc
> Modify rule S6597: "WORKDIR" instruction should be used instead of "cd" commands

- rules/S6382/azureresourcemanager/rule.adoc
> APPSEC-1049 Validate S6382 for ARM

- rules/S6648/azureresourcemanager/how-to-fix-it/bicep.adoc
> APPSEC-1053 Validate S6648 ARM default value for secret

- rules/S1048/cfamily/how_to_fix_it.adoc
Broken link is fixed in https://github.com/SonarSource/rspec/pull/3033.
> Modify rule S1048: remove extra space in code snippet

- rules/S6600/php/rule.adoc
> Modify rule S6600: remove extra diff-view

- rules/S4423/azureresourcemanager/how-to-fix-it/azure-mysql.adoc
- rules/S4423/azureresourcemanager/how-to-fix-it/azure-storage-account.adoc
ARM JSON PR for S4423: #1835 
[RSPEC Preview](https://sonarsource.github.io/rspec/#/rspec/S4423/azureresourcemanager)
> Modify rule S4423: Add language AzureResourceManager (Bicep)

- rules/S6387/azureresourcemanager/highlighting.adoc
- rules/S6387/azureresourcemanager/rule.adoc
[Specification ticket](https://sonarsource.atlassian.net/browse/SONARIAC-760)
[Implementation ticket](https://sonarsource.atlassian.net/browse/SONARIAC-797)
[RSPEC Preview](https://sonarsource.github.io/rspec/#/rspec/S6387/azureresourcemanager)
JSON PR for S6387: #1842
> Modify rule S6387: Add language AzureResourceManager (Bicep)

- rules/S6378/azureresourcemanager/rule.adoc
ARM JSON PR for S6378: #2237 
[RSPEC Preview](https://sonarsource.github.io/rspec/#/rspec/S6378/azureresourcemanager)
> Modify rule S6378: Add language AzureResourceManager (Bicep)

- rules/S6380/azureresourcemanager/rule.adoc
Specification ticket: [APPSEC-775](https://sonarsource.atlassian.net/browse/APPSEC-775)
Implementation ticket: [SONARIAC-899](https://sonarsource.atlassian.net/browse/SONARIAC-899)
[RSPEC Preview](https://sonarsource.github.io/rspec/#/rspec/S6378/azureresourcemanager)
JSON PR for S6380: #2274  
[APPSEC-775]: https://sonarsource.atlassian.net/browse/APPSEC-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARIAC-899]: https://sonarsource.atlassian.net/browse/SONARIAC-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S6380: Add language AzureResourceManager (Bicep) 

- rules/S1774/java/rule.adoc
- rules/S6411/java/rule.adoc
A user reported the typo in the community: https://community.sonarsource.com/t/typo-in-description-of-rule-java-s1774/99071
> Fix typo in S1774 rule.adoc

- rules/S6329/azureresourcemanager/rule.adoc
This PR fixes the code examples for ARM for rule S6329 so that they can be scanned with Sonarqube.
The schema URL for the JSON examples has to be https and for the bicep examples, the correct quotes need to be used.
> APPSEC-1077: S6329 Improve examples fso that they can be scanned with sonar-iac

- rules/S6364/azureresourcemanager/rule.adoc
This PR adjusts the retention period from the compliant examples so that they do not raise security hotspots when scanned with the Sonarway profile.
> APPSEC-1080: S6364 Adjust the retention period of the compliant examples

- rules/S6381/azureresourcemanager/rule.adoc
This PR adjusts the JSON code examples and adds a name field that is needed for the files to be recognized by sonar-iac-plugin.
> APPSEC-1082: S6381 Adjust code examples so that they can be scanned by Sonarqube

- rules/S5523/cfamily/metadata.json
- rules/S5523/cfamily/rule.adoc
- Metadata is updated so that it is consistent with the metadata of the new MISRA rule M23_321. See SonarSource/sonar-cpp#3006.
- Correct the spec since the implementation has been updated later so that it raises only on built-in and pointer types. See SonarSource/sonar-cpp#684.
I considered updating the rule to LaYC format, but I wanted to keep this PR simple for now because the rule is not in "Sonar Way"...
> Modify rule S5523: Correct spec and update metadata

- rules/S6584/docker/rule.adoc
> Modify rule S6584: Add message and highlighting, remove `apk` in favor of `apt`

- rules/S5827/cfamily/rule.adoc
> Modify rule S5827: LaYC - auto on redundant type

- rules/S1871/rule.adoc
> Modify rule S1871: LaYC on identical if branches

- rules/S4823/csharp/metadata.json
- rules/S4823/vbnet/metadata.json
Deleting S4823 as it has been deprecated.
sonar-dotnet 8.9.0.19135, released on Jun 26, 2020
SQ 8.4.0.35506 on Jul 3, 2020.
> Modify S4823: Delete 

- rules/S4829/csharp/metadata.json
- rules/S4829/vbnet/metadata.json
Deleting S4829 as it has been deprecated.
sonar-dotnet 8.9.0.19135, released on Jun 26, 2020
SQ 8.4.0.35506 on Jul 3, 2020.
> Modify S4829: Delete

- rules/S5276/cfamily/rule.adoc
> Modify rule S5276: LaYC - narrowing conversions

- rules/S1659/cfamily/metadata.json
- rules/S1659/cfamily/rule.adoc
> Modify rule S1659: LaYC - one decl per line

- rules/S3457/cfamily/rule.adoc
> Modify rule S3457: LaYC on printf errors

- rules/S5899/php/rule.adoc
> Modify rule S5899: Add exception on public static method that return data

- rules/S6579/docker/rule.adoc
> Modify rule S6579: apply LaYC format

- rules/S4784/csharp/metadata.json
- rules/S4784/vbnet/metadata.json
Delete S4784 as it has been deprecated.
sonar-dotnet [8.15.0.24505](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.15.0.24505).
SQ [8.6.0.39681](https://github.com/SonarSource/sonar-enterprise/releases/tag/8.6.0.39681)
> Modify rule: Delete S4784

- rules/S2228/csharp/metadata.json
Deleting S2228 as it has been deprecated.
sonar-dotnet [8.15.0.24505](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.15.0.24505).
SQ [8.6.0.39681](https://github.com/SonarSource/sonar-enterprise/releases/tag/8.6.0.39681)
> Modify rule: Delete S2228

- rules/S4564/csharp/metadata.json
Delete S4564 as it has been deprecated.
sonar-dotnet [8.17.0.26580](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.17.0.26580).
SQ [8.7.0.41497](https://github.com/SonarSource/sonar-enterprise/releases/tag/8.7.0.41497)
> Modify rule: Delete S4564

- rules/S4834/csharp/metadata.json
- rules/S4834/vbnet/metadata.json
Delete S4834 as it has been deprecated.
sonar-dotnet [8.18.0.27296](https://github.com/SonarSource/sonar-dotnet/releases/tag/8.18.0.27296).
SonarQube [8.7.0.41497](https://github.com/SonarSource/sonar-enterprise/releases/tag/8.7.0.41497)
> Modify rule: Delete S4834

- rules/S6466/impact.adoc
- rules/S6466/java/rule.adoc
- rules/S6466/python/metadata.json
- rules/S6466/python/rule.adoc
> Modify rule S6466: Extend LaYC content

- rules/S6322/java/rule.adoc
> Modify rule S6322: Migrate to LaYC format

- rules/S3471/cfamily/rule.adoc
> Modify rule S3471: LaYC - virtual / override

- rules/S5344/description.adoc
- rules/S5344/java/rule.adoc
- rules/S5344/message.adoc
- rules/S5344/rule.adoc
- rules/S5344/see.adoc
> Modify rule S5344: Change text to education framework format (APPSEC-1106)

- rules/S2259/python/rule.adoc
> Modify rule S2259: Extend LaYC content for Python

- rules/S4601/java/metadata.json
- rules/S4601/java/rule.adoc
> Modify S4601: Change text to LaYC format (APPSEC-1150)

- rules/S3776/resources.adoc
Added the cognitive complexity blog post link so that it shows up in the 'more info' tab for all languages.
> Modify rule S3776: Add cog complexity blog post link

- .cirrus.yml
- ci/validate_file_extensions.sh
The dotnet squad would like to improve the rule specification sprint process requiring some UTs to be temporarily added under the rule folder on RSPEC repository. These test case files (`.cs` and `.vb`) will be copied to the sonar-dotnet repository during the initial phases of implementation and will serve as an initial test bed. 
However, before merging the PR on the RSPEC side we need to make sure that these test case files are deleted and they don't end up on master. 
The goal of this PR would be to add a check on the pipeline that will fail if `.cs` or `.vb` files are detected (it's acceptable if it's red until the implementation is done).
> Add CI task to validate file extension

- rules/S1854/cfamily/metadata.json
- rules/S1854/csharp/metadata.json
- rules/S1854/metadata.json
Partially reverts `quickfix` changes done in https://github.com/SonarSource/rspec/pull/3150:
- C# and CFamily keep `targeted`
- all other languages go back to `unknown`
> Modify rule S1854: Update 'quickfix' field

- rules/S1068/cfamily/rule.adoc
- rules/S1068/description.adoc
- rules/S1068/flex/rule.adoc
- rules/S1068/java/rule.adoc
- rules/S1068/php/rule.adoc
- rules/S1068/rpg/rule.adoc
- rules/S1068/rule.adoc
- rules/S1068/vb6/rule.adoc
> Modify S1068: Migrate to LayC - unused private fields

- rules/S1135/description.adoc
> Modify S1135: Fix typo

- rules/S1121/cfamily/metadata.json
- rules/S1121/cfamily/rule.adoc
- rules/S1121/compliant.adoc
- rules/S1121/csharp/rule.adoc
- rules/S1121/description.adoc
- rules/S1121/how-to-fix-it.adoc
- rules/S1121/java/rule.adoc
- rules/S1121/javascript/rule.adoc
- rules/S1121/noncompliant.adoc
- rules/S1121/php/rule.adoc
- rules/S1121/rule.adoc
> Modify S1121: Migrate to LayC - Assignments should not be made from within sub-expressions

- rules/S1117/cfamily/metadata.json
- rules/S1117/cfamily/rule.adoc
- rules/S1117/csharp/rule.adoc
- rules/S1117/flex/rule.adoc
- rules/S1117/java/metadata.json
- rules/S1117/java/rule.adoc
- rules/S1117/javascript/metadata.json
- rules/S1117/javascript/rule.adoc
- rules/S1117/metadata.json
- rules/S1117/php/rule.adoc
- rules/S1117/plsql/metadata.json
- rules/S1117/plsql/rule.adoc
- rules/S1117/problems.adoc
- rules/S1117/rspecator.adoc
- rules/S1117/swift/rule.adoc
- rules/S1117/why-fields.adoc
- rules/S1117/why-general.adoc
- rules/S1117/why.adoc
The languages for this rule fall into two categories:
* CFamily, JS, and PLSQL: "Variables should not be shadowed" (general case of shadowing)
* C#, Flex, Java, PHP, Swift: "Local variables should not shadow field/property/enum case/..." (narrow case of shadowing)
For CFamily, these tickets are also handled: CPP-2785 CPP-3589
> Modify S1117: Migrate To LayC - shadow variables

- rules/S5738/java/rule.adoc
> Modify S5738: Migrate to LayC - `@Deprecated` code marked for removal should never be used

- docs/link_formatting.adoc
- rules/S1039/cfamily/rule.adoc
- rules/S1232/cfamily/rule.adoc
- rules/S3457/cfamily/rule.adoc
- rules/S3529/cfamily/rule.adoc
- rules/S3584/cfamily/rule.adoc
- rules/S5272/cfamily/rule.adoc
- rules/S5403/cfamily/rule.adoc
- rules/S5417/cfamily/rule.adoc
- rules/S5524/cfamily/rule.adoc
- rules/S5553/cfamily/rule.adoc
- rules/S5558/cfamily/rule.adoc
- rules/S5570/cfamily/rule.adoc
- rules/S5972/cfamily/rule.adoc
- rules/S6197/cfamily/rule.adoc
- rules/S6427/cfamily/rule.adoc
- rules/S6458/cfamily/rule.adoc
- rules/S6459/cfamily/rule.adoc
- rules/S6490/cfamily/rule.adoc
- rules/S6655/cfamily/rule.adoc
- rules/S836/cfamily/rule.adoc
- rules/S878/cfamily/rule.adoc
- rules/S961/cfamily/rule.adoc
This is done gradually over a few commits, each increasing the length of the common prefix. This should be squashed.
> Normalize links to C++ reference

- rules/S3457/cfamily/rule.adoc
- rules/S3457/csharp/rule.adoc
- rules/S3457/java/rule.adoc
- rules/S3457/message.adoc
- rules/S3457/metadata.json
- rules/S3457/python/rule.adoc
> Modify S3457: Migrate to LayC - `printf`-style format string are misused

- rules/S905/cfamily/rule.adoc
- rules/S905/description.adoc
- rules/S905/javascript/rule.adoc
- rules/S905/php/rule.adoc
- rules/S905/python/rule.adoc
- rules/S905/see.adoc
> Modify S905: Migrate to LaYC - Non-empty statements should change control flow or have at least one side-effect

- rules/S1774/cfamily/rule.adoc
- rules/S1774/description.adoc
- rules/S1774/java/rule.adoc
- rules/S1774/javascript/rule.adoc
> Modify S1774: Migrate to LayC - remove ternary expression

- rules/S2259/how-dotnet.adoc
- rules/S2259/java/compliant-code.adoc
- rules/S2259/java/noncompliant-code.adoc
- rules/S2259/java/rule.adoc
- rules/S2259/javascript/rule.adoc
> Modify S2259: Migrate to LaYC - null dereference

- rules/S1079/cfamily/rule.adoc
> Modify rule S1079: Change text to education framework format (APPSEC-1209)

- rules/S2819/common/resources/docs.adoc
- rules/S2819/common/resources/standards.adoc
- rules/S2819/impact.adoc
- rules/S2819/javascript/how-to-fix-it/origin.adoc
- rules/S2819/javascript/rule.adoc
- rules/S2819/rationale.adoc
- rules/S2819/summary.adoc
> Modify rule S2819: Change text to education framework format (APPSEC-1208)

- rules/S4211/csharp/rule.adoc
> Modify rule S4211: Change text to education framework format (APPSEC-1206)

- rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
- rules/S1081/cfamily/rule.adoc
- rules/S1081/common/resources/standards.adoc
- rules/S1081/impact.adoc
- rules/S1081/rationale.adoc
- rules/S1081/summary.adoc
> Modify rule S1081: Change text to education framework format (APPSEC-1210)

- rules/S6410/terraform/rule.adoc
> Modify rule S6410: Change text to education format (APPSEC-1235)

- rules/S5832/cfamily/rule.adoc
> Modify rule S5832: Change text to education framework format (APPSEC-1213)

- docs/header_names/allowed_framework_names.adoc
- rules/S5144/python/how-to-fix-it/httpx.adoc
- rules/S5144/python/rule.adoc
> Modify rule S5144: Add HTTPX support (APPSEC-1247)

- rules/S5594/xml/rule.adoc
> Modify rule S5594: Change text to education framework format (APPSEC-1238)

- rules/S6359/xml/rule.adoc
> Modify rule S6359: Change text to education framework format (APPSEC-1239)

- docs/header_names/allowed_framework_names.adoc
- rules/S4830/python/how-to-fix-it/httpx.adoc
- rules/S4830/python/rule.adoc
> Modify rule S4830: Add HTTPX support (APPSEC-1259)

- rules/S5869/javascript/rule.adoc
> Modify rule S5869: Mention character class escapes

- rules/S2092/python/rule.adoc
> Modify rule S2092: Add FastAPI (APPSEC-1260)

- rules/S6012/cfamily/rule.adoc
The intent here is only to fix critical typos, not to rewrite the rule.
> Modify rule S6012: fix some typos

- rules/S6790/javascript/rule.adoc
> Fix S6790: Use method definition in code snippets

- rules/S3394/cobol/rule.adoc
https://github.com/SonarSource/rspec/commit/b4812424ee5b9cd210f926252566ac6c3bb291dd#r131831666
This code sample will raise, as the COBOL logic is pretty simple. The idea is to make this rule a "review" rule instead of a vulnerability. We do not have the bandwidth to convert it to a hotspot but that's ok.
> Modify S3394(COBOL): Remove compliant samples

- rules/S5906/python/metadata.json
> Modify S5906 (Python): Add to default quality profile

- ci/Dockerfile
- ci/frontend-tests-dockerfile
A fix for
> ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Error while running Node.js. A supported version of Node.js is required for running the analysis of JS in HTML files. Please make sure a supported version of Node.js is available in the PATH. Alternatively, you can exclude JS in HTML files from your analysis using the 'sonar.exclusions' configuration property. See the docs for configuring the analysis environment: https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/languages/javascript-typescript-css/
> Use NodeJS 16 to run Sonar analysis

- rules/S3630/cfamily/rule.adoc
See also the message change in https://github.com/SonarSource/sonar-cpp/pull/3219
> Modify rule S3630: Clarify in RSPEC what is expected from users before C++20 (CPP-4803)

- rules/S4792/metadata.json
This rule is noisy and was planned to be deprecated [for a long time](https://discuss.sonarsource.com/t/are-we-doing-right-the-security-hotspots-review-on-sonarqube/5706/6).
As we are currently looking to remove unwanted hotspots as part of our ongoing sprint, we are now deprecating this rule.
> Deprecate rule S4792 (APPSEC-1407)

- rules/S5743/javascript/metadata.json
- rules/S5743/metadata.json
This rule checks for the [X-DNS-Prefetch-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control) header, which is non-standard and not on a standards track. It is recommended to not be used on production sites facing the Web, so we should also not recommend it.
As we are currently looking to remove unwanted hotspots as part of our ongoing sprint, we are now deprecating this rule.
> Deprecate rule S5743 (APPSEC-1410)

- rules/S5750/javascript/metadata.json
- rules/S5750/metadata.json
This rule was decided not to be implemented back in 2020: SonarSource/SonarJS#1962.
As we are currently looking to remove unwanted hotspots as part of our ongoing sprint, we are deleting this rule.
> Delete rule S5750 (APPSEC-1411)

- rules/S6245/metadata.json
S3 now encrypts by default. As we are currently looking to remove unwanted hotspots as part of our ongoing sprint, we are now deprecating this rule.
> Deprecate rule S6245

- rules/S1068/java/rule.adoc
From community: https://community.sonarsource.com/t/sonarqube-doesnt-report-unused-fields-with-lombok/106265
> Update java:S1068 exceptions to mention classes with Lombok annotations

- rules/S1079/cfamily/rule.adoc
- rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
- rules/S1081/rationale.adoc
- rules/S2259/cfamily/rule.adoc
- rules/S3574/cfamily/rule.adoc
- rules/S5270/cfamily/rule.adoc
- rules/S5272/cfamily/rule.adoc
- rules/S5487/cfamily/rule.adoc
- rules/S5847/cfamily/rule.adoc
- rules/S6191/cfamily/rule.adoc
- rules/S6391/cfamily/rule.adoc
- rules/S6494/cfamily/rule.adoc
- rules/S6655/cfamily/rule.adoc
- rules/S874/cfamily/rule.adoc
- rules/S954/cfamily/rule.adoc
"C++" spelled as-is can result in unexpected rendering, such as
C++20 was released before C++17
renders as
C20 was released before C17
Make consistent use of `[source,cpp]`.
> Fix asciidoc w.r.t. C++

- rules/S1125/apex/rule.adoc
- rules/S1125/csharp/rule.adoc
- rules/S1125/description.adoc
- rules/S1125/go/rule.adoc
- rules/S1125/how-to-fix-it.adoc
- rules/S1125/javascript/rule.adoc
- rules/S1125/kotlin/rule.adoc
- rules/S1125/php/rule.adoc
- rules/S1125/plsql/rule.adoc
- rules/S1125/rule.adoc
- rules/S1125/scala/rule.adoc
- rules/S1125/vb6/rule.adoc
- rules/S1125/vbnet/rule.adoc
> Fix typo in S1125 description

- docs/benchmarks.adoc
I am not sure links on table headers will work across all variants of rspec (SL, SQ, SC, rules.sonarsource...), so instead I suggest we use a glossary (which was also suggested as a solution in discussions with the documentation team).
> Benchmarks Guide: Update statistical term links

- rules/S4027/csharp/rspecator.adoc
- rules/S4027/csharp/rule.adoc
Description
In .Net 8 "All externally visible (public or protected) serialization ctors: .ctor(SerializationInfo, StreamingContext)." are marked as obsolete ([Source](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#new-obsoletions-in-net-8)).
We need to remove the serialization constructor from the list of required constructors for exceptions.
> Fix S4027 C#: BinaryFormatter. Serialization constructors are obsolete and should not be required

- rules/S6865/kubernetes/rule.adoc
Removed the example for **service account's configuration** part, as this is not yet supported
> Modify rule S6865: Updated example, message and removed configuration part for now

- rules/S2871/javascript/rule.adoc
> Modify rule S2871: Emphasize the necessity of using String.localeCompare to sort arrays of strings

- rules/S4123/javascript/rule.adoc
@yassin-kammoun-sonarsource 
The diff might be confusing. In that case, have a look at the result: https://github.com/SonarSource/rspec/blob/modify-S4123-jsdoc-exception/rules/S4123/javascript/rule.adoc
> Modify rule S4123: remove hint about JSdoc and add it to exception

- rules/S927/why-dotnet.adoc
Suggested changes by the Docs Squad:
- specify pronoun to clarify what "it" is
- fix plural possessives
> Modify rule S927: Update rule description

- rules/S6910/secrets/rule.adoc
> APPSEC-1479: S6910 Adjustment to make RSPEC consistent with Sonar Text

- rules/S796/cfamily/rule.adoc
> CPP-4968 S796 List all escape sequence from C99, C++11 and C++23

- docs/header_names/allowed_framework_names.adoc
- rules/S4426/common/fix/ec.adoc
- rules/S4426/common/fix/fix.adoc
- rules/S4426/common/resources/docs.adoc
- rules/S4426/python/how-to-fix-it/pyOpenSSL.adoc
- rules/S4426/python/how-to-fix-it/pyca.adoc
- rules/S4426/python/how-to-fix-it/pycryptodome.adoc
- rules/S4426/python/rule.adoc
> Modify rule S4426: Add how to fix it for cryptodome and pyOpenSSL and close gap with NIST

- rules/S4830/python/how-to-fix-it/aiohttp.adoc
- rules/S4830/python/rule.adoc
> Modify Rule S4830: Add aiohttp support (APPSEC-1361)

- rules/S1948/java/rule.adoc
SONARJAVA-4814 Improved S1948 RSPEC to better explain why public collections are a problem
> Modify rule S1948: Clarify the description (SONARJAVA-4814)

- rules/S1696/csharp/rule.adoc
I was looking for double dashes in cfamily rules for CPP-4910 and randomly stumbled upon S1696 for C#.
The link has two issues:
1. `--` is transformed into em-dash `—​`.
2. `]` in the link text was interpreted as the closing bracket instead of a regular text character.
In both cases, the fix is to escape such character.
FWIW, I did not attempt to search for other broken links in C#.
> Modify rule S1696: Fix link

- rules/S1236/cfamily/rule.adoc
- rules/S3657/cfamily/rule.adoc
- rules/S3692/cfamily/rule.adoc
- rules/S5019/cfamily/rule.adoc
- rules/S5829/cfamily/rule.adoc
- rules/S867/cfamily/rule.adoc
- rules/S877/cfamily/rule.adoc
> CPP-4910 Fix links to C++ Core Guideline with double dashes

- rules/S6169/cfamily/rule.adoc
> Modify rule S6169: minor rewordings

- rules/S3927/description.adoc
Changes suggested by the Docs Squad:
- use full word in place of short-hand text
> Modify rule S3927: Update rule description

- rules/S2551/csharp/rule.adoc
- rules/S2551/vbnet/rule.adoc
- rules/S2551/why-dotnet.adoc
Changes suggested by the Docs Squad:
- the example used to illustrate the rule did not consider if the case was in C# or VB
- In addition, the description was confusing so was simplified to make the case easier to understand.
> Modify rule S2551: clarify example used in the description

- rules/S3416/csharp/metadata.json
> Modify rule S3416: remove from SonarWay

- rules/S5542/common/fix/fix.adoc
- rules/S5542/rationale.adoc
Rule S5542 will be modified so that it is no longer raised on CBC mode. A new rule will be introduced that triggers on the use of unauthenticated encryption modes, which will cover CBC.
See APPSEC-1560.
> Modify rule S5542: Change text for rule update

- rules/S103/php/metadata.json
This PR addresses https://sonarsource.atlassian.net/browse/SONARPHP-1492 following a dogfood request https://discuss.sonarsource.com/t/php-rule-s103-lines-too-long-is-enabled-by-default/17909
> Modify rule S103: Remove from default profile for PHP

- rules/S2955/csharp/rule.adoc
Provide a better solution, that does not box value types to `object`.
For more details, see [this thread](https://github.com/SonarSource/sonar-dotnet/issues/8933#issuecomment-2004644300).
> Modify S2955 C#: Fix compliant solution

- rules/S1706/cfamily/rule.adoc
Also improve the rule in many other places.
> Modify rule S1706:  Mention std::expected as an alternative to exceptions (CPP-5054)

- rules/S1144/csharp/rule.adoc
> Modify Rule S1144: Add exception to C# RSPEC

- rules/S1854/cfamily/rule.adoc
- rules/S2589/cfamily/metadata.json
- rules/S2589/comments-and-links.adoc
- rules/S3516/cfamily/metadata.json
- rules/S3516/comments-and-links.adoc
- rules/S3626/cfamily/metadata.json
- rules/S3626/comments-and-links.adoc
> Modify rule S2589,S3516,S3626: Remove them from CFamily (CPP-5165)

- rules/S2275/cfamily/rule.adoc
- rules/S5281/cfamily/rule.adoc
`validate_links` fails for unrelated reasons.
> Modiful rules S5281,S2275: Mention the safer std::print alternative in the RSPEC (CPP-5027)

- rules/S6185/cfamily/rule.adoc
- rules/S6484/cfamily/rule.adoc
- rules/S6494/cfamily/rule.adoc
- rules/S6495/cfamily/rule.adoc
NB: to make Grammarly work a bit better, I ensured sentences start and end on the same line. We are not consistent (sometimes the sentence is broken over multiple lines, sometimes a whole paragraph is on one line). I did not attempt to fix this inconsistency.
NB2: Link validation fails in a JS/TS rule.
> Modify rules S6185,S6484,S6494,S6495: RSPEC improvements (CPP-5056)

- .github/workflows/update_coverage.yml
The frontend SQ analysis frequently fails during the night likely because it runs soon after SQ is redeployed. Move the update_coverage job 2h later to avoid that.
> Avoid hitting "Next" downtime by postponing the job later in the night

- rules/S6931/vbnet/metadata.json
Deprecates VB for S6931.
Hint: https://github.com/SonarSource/rspec/tree/master/rules/S6934 does not implement VB,so we do not need to do any changes there.
> Modify rule S6931: Deprecate VB for 

- rules/S2094/csharp/rule.adoc
- rules/S2094/exceptions-dotnet.adoc
- rules/S2094/vbnet/rule.adoc
Implementation tickets:
[Implicit parameterless constructor widens the scope of the base class constructor](https://github.com/SonarSource/sonar-dotnet/issues/7591)
[Should not raise for messages](https://github.com/SonarSource/sonar-dotnet/issues/9063)
> Modify rule S2094: Add an exception

- rules/S1085/html/metadata.json
Relates to https://sonarsource.atlassian.net/browse/SONARHTML-231
> Resolve SONARHTML-231 - Deprecate S1085:html

- rules/S1086/html/metadata.json
> Mark S1086 HTML variant as deprecated

- rules/S2951/vbnet/metadata.json
Rules should not be prefixed with their language name. We generally don't do that, as it doesn't make sense.
> S2951: Rename

- rules/S6803/csharp/metadata.json
- rules/S6803/csharp/rule.adoc
After discussing the impact of this rule we decided to deprecate it.
- The rule applies < .NET8
- It has a very low impact
- It applies only to sealed components
> Deprecate S6803

- rules/S2365/csharp/rule.adoc
- rules/S2365/vbnet/rule.adoc
See https://github.com/SonarSource/sonar-dotnet/issues/9254
> Modify S2365: Fix code examples

- rules/S6962/csharp/rule.adoc
Adding a link to a rule causes the creation of nested `a` tags:
```html
<a href="https://rules.sonarsource.com/csharp/RSPEC-6420/"><a href='/sonarqube/coding_rules#rule_key=csharpsquid:S6420'>S6420</a> - Client instances should not be recreated on each Azure\n  Function invocation</a>
```
This causes trouble e.g. in SonarLint for Visual Studio. See the discussion here:
https://sonarsource.slack.com/archives/C012KBFFYD6/p1715177821573109?thread_ts=1715166368.425089&cid=C012KBFFYD6
See also SonarSource/sonarlint-visualstudio/issues/5413
> Modify rule S6962: Fix rule link

- rules/S5786/java/rule.adoc
- rules/S6962/csharp/rule.adoc
See https://github.com/SonarSource/rspec/pull/3926
==================
> Modify rule S5786: Fix rule link

- rules/S1236/cfamily/metadata.json
- rules/S1236/cfamily/rule.adoc
> CPP-5096 S1236 Explain covered cases and exception

- rules/S4423/cloudformation/how-to-fix-it/api-gateway.adoc
- rules/S4423/cloudformation/rule.adoc
> Modify rule S4423: Remove instructions that are not relevant for API Gateway V2 (APPSEC-182)

- rules/S6945/jcl/metadata.json
> Modify rule S6945: fix typo in title

- rules/S2094/exceptions-dotnet.adoc
> Modify rule S2094: add exception for classes ending with Query

- rules/S6608/resources-dotnet.adoc
Related to: https://github.com/SonarSource/sonar-dotnet/issues/9390
> S6608: Update benchmarks code sample and results

- rules/S6459/cfamily/rule.adoc
> CPP-5375 S6459 Add exception for `std::convertible_to` concept

- rules/S1694/csharp/metadata.json
- rules/S1694/csharp/rule.adoc
Related to https://github.com/SonarSource/sonar-dotnet/issues/8795
> S1694: Promote C# to SonarWay and remove protected constructor

- rules/S5769/abap/rule.adoc
I believe it's Ok to simply remove it. I didn't find an alternative and the link is not on the wayback machine https://wayback-api.archive.org/web/20240000000000*/https://zevolving.com/use-of-field-symbols-vs-work-area
> Modify rule S5769: Remove dead link

- rspec-tools/rspec_tools/coverage.py
- rspec-tools/tests/test_coverage.py
When there are multiple sonarpedia.json files for the same language, the rules picked up for the next sonarpedia.json file will override the ones picked up previously. With this fix, the rules are not overwritten but all are collected, so one repository can have multiple sonarpedia.json files for the same language.
> RULEAPI-770 Fix bug due to multiple sonarpedia.json files

- rules/S1144/csharp/rule.adoc
> Update S1144: Add exception for DynamicallyAccessedMembersAttribute

- rules/S3624/cfamily/rule.adoc
> Modify rule S3624: fix error in documentation visibility

- rspec-tools/rspec_template/single_language/secrets/metadata.json
- rspec-tools/rspec_template/single_language/secrets/rule.adoc
- rspec-tools/rspec_tools/create_rule.py
This change allows single-language rules to use a specialized template when they're created.
The reason for this change is that the AppSec squad wants to improve the efficiency with which new `secrets` rules can be created. These rules only exist for a single language, `secrets`, and much of the rule content and metadata is similar/identical between rules.
The best way to realize this efficiency improvement for `secrets` rules is to have a specialized template that gets used when a new RSPEC is created. This template is used when a rule is created for a single language, and that language is `secrets`.
When a rule is created with a single language, the appropriate template folder is checked for a folder whose name matches the language. If such a folder is found, it will be used as the …
> Create specialized single-language rules

- rules/S6864/kubernetes/rule.adoc
> Modify rule S6864: Add examples for LimitRange

- rules/S2807/cfamily/rule.adoc
> Modify rule S2807: Add a longer explanation of the hidden friend pattern

- rules/S6873/kubernetes/rule.adoc
> Modify rule S6873: Add examples for LimitRange

- rules/S6870/kubernetes/rule.adoc
> SONARIAC-1228 S6870: Should not raise with LimitRange in the same namespace setting Storage Limits

- rules/S6864/kubernetes/rule.adoc
- rules/S6892/kubernetes/rule.adoc
> Modify rule S6892: Add examples for LimitRange

- rules/S3247/csharp/rule.adoc
- rules/S3247/rspecator.adoc
RSPEC update for https://github.com/SonarSource/sonar-dotnet/issues/2120
> Modify S3247: Improve description and update example

- rules/S824/cfamily/rule.adoc
New suggested message (the rule implementation has not been updated yet):
> Move this function declaration outside of this block scope, or if the intent was to declare a variable, use a syntax that avoids the most vexing parse.
> Modify rule S824: Clarify the most vexing parse (CPP-5122)

- rspec-tools/rspec_tools/coverage.py
> BUILD-4733: update clone command to use a github access-token

- rspec-tools/rspec_tools/coverage.py
> BUILD-4733: Use the correct url format for cloning with an access token

- .github/workflows/main.yml
flow and fix the usage of github-pages-deploy-action
> BUILD-5580: add missing pages:write permission to Build and Deploy work

- .github/workflows/update_coverage.yml
- Fixes error at https://github.com/SonarSource/rspec/actions/runs/10004012710
```
Run andymckay/cancel-action@0.2
Error: Resource not accessible by integration
```
- Enable testing: when manually triggered from a non-default branch, the results will not be pushed
Successful run: https://github.com/SonarSource/rspec/actions/runs/10004036543
> BUILD-4175 Fix permission issue when canceling the update coverage action

- .github/workflows/update_coverage.yml
The previous change to the task `'Push the updated coverage to master'` made it passthrough because it used `{{` as part of the condition, which seems to be forbidden.
Changing the condition to what we usually use to check default_branch in other workflow scripts throughout our repositories.
> Fix coverage script when there is no new coverage

- rules/S2807/cfamily/rule.adoc
> Update rule S2807: typos

- rules/S2387/csharp/metadata.json
- rules/S2387/vbnet/metadata.json
Superseded by [CS0108](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0108) in C#
Superseded by [BC40004](https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc40004) in VB.NET
> Deprecate rule S2387

- rules/S2674/csharp/metadata.json
- rules/S2674/csharp/rule.adoc
> Modifiy S2674: Promote it to SonarWay

- rules/S2325/csharp/metadata.json
- rules/S2325/csharp/rule.adoc
Although it rule is covered by the [CA1822](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822) Roslyn analyzer, but that doesn't show up in SQ, because by default it's only a Suggestion rather than a Warning.
> Modify S2325: Promote C# rule to Sonar-Way

- rules/S2325/csharp/rule.adoc
- rules/S2674/csharp/rule.adoc
> Modifiy S2325 & S2674: Fix typo and missing links

- rules/S2159/dart/rule.adoc
- rules/S2159/metadata.json
> Modify rule S2159: Add Dart language

- rules/S3257/dart/rule.adoc
> Modify rule S3257: add rspecator and fix resources layout

- rules/S4123/dart/rule.adoc
> Modify rule S4123: remove ref to other RSPEC

- rules/S6619/dart/rule.adoc
> Modify rule S6619: Add Dart language

- rules/S3715/cfamily/rule.adoc
Do not merge before MMF-3874 is merged
> Modify rule S3715: Mention empty initializer before C23

- rules/S6651/java/metadata.json
> Modify rule S6651: fix erroneous inclusion in SonarWay

- rules/S2175/dart/rule.adoc
> Modify rule S2175: add spaces to the why section

- rules/S5416/dart/rule.adoc
> Modify rule S5416: add spaces to the why section

- rules/S7045/dart/rule.adoc
> Modify rule S7045: fix list formatting in Why section

- rules/S7045/dart/rule.adoc
> Modify rule S7045: Fix underscore escaping in rule description

- rules/S6024/cfamily/rule.adoc
> Modify rule S6024: Remove useless paretheses

- rules/S7047/dart/rule.adoc
> Modify rule S7047: Fix formatting of inline code

- rules/S2637/cfamily/metadata.json
- rules/S2637/cfamily/rule.adoc
> Modify rule S2637(cfamily): CPP-5602 allow assigning nullptr to params

- rules/S2260/dart/metadata.json
As discussed with @agigleux , this rule should be included in "Sonar way" at least in the first release.
> Modify Rule S2260: update Dart metadata

- rules/S2259/java/metadata.json
- rules/S2259/java/rule.adoc
- rules/S2583/java/metadata.json
- rules/S2583/java/rule.adoc
- rules/S2589/java/metadata.json
- rules/S2589/java/rule.adoc
- rules/S3518/java/metadata.json
- rules/S3518/java/rule.adoc
- rules/S3655/java/metadata.json
- rules/S3655/java/rule.adoc
- rules/S3959/java/metadata.json
- rules/S3959/java/rule.adoc
- **Revert "Modify rules S2259;S2583;S2589;S3518;S3655;S3959 Remove replacement rules and update description for deprecated SE rules (#4207)"**
- **Revert "SONARJAVA-5102 Deprecate Java SE rules implemented by DBD (#4177)"**
> Modify rules S2259;S2583;S2589;S3518;S3655;S3959: undo deprecation

- rules/S7063/javascript/metadata.json
We decided not to go ahead with this rule. Let us close it.
> Close S7063 for javascript

- rules/S3881/csharp/rule.adoc
> Modify rule S3881: Remove typo in code example

- rules/S2301/javascript/metadata.json
> JS-332 Add `type-dependent` tag to TypeScript variant of RSPEC 2301

- .github/workflows/add_language.yml
- .github/workflows/create_new_rspec.yml
- .github/workflows/update_quickfix_status.yml
The default GITHUB_TOKEN permissions will be set to read-only organization-wide. See https://sonarsource.atlassian.net/browse/SSF-619 for background information.
Changes were tested in:
- https://github.com/SonarSource/rspec/actions/runs/10761394392
- https://github.com/SonarSource/rspec/actions/runs/10761442606
> Explicit permissions for GITHUB_TOKEN where write is needed

- rules/S1441/javascript/metadata.json
- rules/S1537/metadata.json
- rules/S2260/javascript/metadata.json
- rules/S2310/javascript/metadata.json
- rules/S3523/javascript/metadata.json
- rules/S3723/metadata.json
- rules/S6660/javascript/metadata.json
- rules/S6661/javascript/metadata.json
- rules/S6666/javascript/metadata.json
- rules/S6671/javascript/metadata.json
- rules/S6676/javascript/metadata.json
- rules/S6679/javascript/metadata.json
Went through the rules in the task description and added the missing "code" tag.
> JS-277 Update rules with missing `code` tag

- rules/S7036/text/metadata.json
> Modify rule S7036: mark as `beta`

- rules/S6485/java/metadata.json
> Modify rule S6485: quickfix set to covered

- rules/S7111/dart/rule.adoc
> Modify rule S7112: Fix spelling in description

- rules/S7113/dart/rule.adoc
> Modify rule S7113: Fix link prefix under resources documentation

- rules/S1721/python/rule.adoc
> SONARPY-2005: Modify rule S1721: Update rule for in (...)

- rules/S2068/python/metadata.json
> Modify rule S2068: Update title to "Hard-coded passwords are security-sensitive"

- docs/description.adoc
- docs/styling_guide.adoc
Since the information is split into different files, I thought it better to duplicate the new guideline (I did not want to fully reorganize the doc...)
> Add guidelines to format references to code elements

- docs/description.adoc
> Convention: use colon as separator in comments within code blocks

- rules/S2260/dart/rule.adoc
> Modify rule S2260: Fix list of actions to deal with analyzer failures

- rules/S5334/csharp/how-to-fix-it/dotnet.adoc
> Modify rule S5334: Add noncompliant comment in C# (APPSEC-258)

- rules/S6937/jcl/metadata.json
- rules/S6937/jcl/rule.adoc
> Modify rule S6937: Extend support to other statements

- rules/S6667/metadata.json
- rules/S6668/metadata.json
- rules/S6669/metadata.json
- rules/S6670/metadata.json
- rules/S6672/metadata.json
- rules/S6674/metadata.json
- rules/S6675/metadata.json
- rules/S6776/metadata.json
- rules/S6798/csharp/metadata.json
- rules/S6800/csharp/metadata.json
- rules/S6930/metadata.json
- rules/S6931/metadata.json
- rules/S6932/csharp/metadata.json
- rules/S6934/metadata.json
- rules/S6960/metadata.json
- rules/S6964/metadata.json
- rules/S6967/metadata.json
- rules/S6968/csharp/metadata.json
Reviewer: please mark as checked after review.
Discrepancies
Multiple CCT:
https://trello.com/c/uPdUhaFh
Discrepencies.txt
```
Historical defaultSeverity was Minor but CCT is MEDIUM for S1441 in javascript
Historical defaultSeverity was Major but CCT is HIGH for S2259 in cfamily
Historical defaultSeverity was Critical but CCT is MEDIUM for S2310 in javascript
Historical defaultSeverity was Critical but CCT is MEDIUM for S3523 in javascript
Historical defaultSeverity was Minor but CCT is MEDIUM for S3723 in javascript
Historical defaultSeverity was Major but CCT is LOW for S6485 in java
Historical defaultSeverity was Minor but CCT is MEDIUM for S6524 in kotlin
Historical defaultSeverity was Major but CCT is LOW for S6527 …
```
> Update impact or defaultSeverity to match each other

- rules/S6249/terraform/rule.adoc
> Modify rule S6249: fix Terraform code examples

- rules/S5408/cfamily/rule.adoc
> S5408 Remove constexpr static data members from rspec (CPP-5809)

- rules/S7133/description-dotnet.adoc
- rules/S7133/resources-dotnet.adoc
> NET-700 Modify S7133: Remove Monitor

- rules/S5148/html/rule.adoc
- rules/S5148/recommended.adoc
This PR should be merged once https://sonarsource.atlassian.net/browse/SONARHTML-220 is implemented.
> Modify rule S5148: Adjust description to fit improved detection

- rules/S6294/cloudformation/rule.adoc
> Modify rule S6294: "Log Groups" should be declared explicitly

- rules/S6258/cloudformation/rule.adoc
- rules/S6258/terraform/rule.adoc
> Modify rule S6258: Update S3 bucket examples

- rules/S5411/java/rule.adoc
Modify S5411 explaining that @NonNull values are ignored. The rule was recently improved in SONARJAVA-5184 to cover more @NonNull variables.
> Modify rule S5411: explain that @NonNull values are ignored.

- rules/S6299/javascript/metadata.json
This rule is not consistent with the rule quality the AppSec squad enforces:
The rule risks a non-negligible number of FPs for the chance of having TPs.
It is non-productive as TPs would get drowned in between FPs. we lose credibility and engagement even if we do find TPs
The rule is hardly actionable as is, as it only shows a “sink”, not the rest of where the variable is coming from, to check if it is an actual problem
Security Hotspots are meant to raise issues that require data that cannot be put in the same code base, such as organizational needs. The why of the rule seems related to the fact that the analyzer does not support VueJS and the specificator still wanted to make a move.
This is not a standard practice at AppSec and does not follow the company delivery model
A dedicated …
> Deprecate S6299: Disabling Vue.js built-in escaping is security-sensitive

- rules/S6327/metadata.json
- rules/S6327/recommended.adoc
> Modify S6327: Improve the recommended fix

- rules/S6255/terraform/metadata.json
> Modify S6255: Remove rule from SonarWay (APPSEC-2291)

- rules/S6433/kubernetes/metadata.json
> Modify rule S6433: Remove Kubernetes from Sonar Way profile (APPSEC-2276)

- rules/S3271/javascript/metadata.json
This rule is not implemented in SonarJS
> Close S3271 for javascript

- rules/S3168/csharp/rule.adoc
> Modify rule S3168: Add more exceptions

- rules/S1948/java/rule.adoc
https://sonarsource.atlassian.net/browse/SONARJAVA-5238
Existing documentation never mentions that serialization does not apply to static fields. We recently had a community post about fixing serialization issue by making a field static.
> Modify rule S1948: clarify that only non-static fields are serialized.

- rules/S5742/metadata.json
> Deprecate rule S5742

- rules/S1199/cfamily/metadata.json
> Modify rule S1199: Deprecate this rule with the intent of removing it when possible CPP-4895

- rules/S6984/python/rule.adoc
> Modify rule S6984: Update einsum link

- rules/S1172/cfamily/rule.adoc
Related to https://github.com/SonarSource/sonar-cpp/pull/4323
> Modify rule S1172 Fix FP for Objective-C block definitions CPP-5916

- rules/S6290/secrets/rule.adoc
> Modify rule S6290: Remove reference to AWS Access Key ID (APPSEC-526)

- rules/S3749/java/rule.adoc
>  Modify rule S3749: Update rule description to add new javax and jakarta annotations (SONARJAVA-5036)

- rules/S907/vb6/rule.adoc
> Modify rule S907: vb6 LaYC

- rules/S1542/vb6/rule.adoc
> Modify S1542 (VB6): Update rule Regex

- rules/S1542/vb6/rule.adoc
> Modify rule S1542: Prevent strong substitution

- rules/S4039/csharp/rule.adoc
[NET-912](https://sonarsource.atlassian.net/browse/NET-912)
Part of [NET-255](https://sonarsource.atlassian.net/browse/NET-255)
Fixes https://github.com/SonarSource/sonar-dotnet/issues/8372
[NET-912]: https://sonarsource.atlassian.net/browse/NET-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NET-255]: https://sonarsource.atlassian.net/browse/NET-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NET-912 Modify rule S4039: Improve description to match the implementation

- rules/S2930/csharp/rule.adoc
[NET-915](https://sonarsource.atlassian.net/browse/NET-915)
Part of [NET-255](https://sonarsource.atlassian.net/browse/NET-255)
Fixes https://github.com/SonarSource/sonar-dotnet/issues/8141
[NET-915]: https://sonarsource.atlassian.net/browse/NET-915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NET-255]: https://sonarsource.atlassian.net/browse/NET-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NET-915 Modify rule S2930: Include tracked types in the description

- rules/S1264/csharp/rule.adoc
[NET-913](https://sonarsource.atlassian.net/browse/NET-913)
Part of [NET-255](https://sonarsource.atlassian.net/browse/NET-255)
Fixes https://github.com/SonarSource/sonar-dotnet/issues/8249
[NET-913]: https://sonarsource.atlassian.net/browse/NET-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NET-255]: https://sonarsource.atlassian.net/browse/NET-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NET-913 Modify rule S1264: Improve description to match the implementation

- rules/S125/csharp/rule.adoc
[NET-920](https://sonarsource.atlassian.net/browse/NET-920)
Part of [NET-255](https://sonarsource.atlassian.net/browse/NET-255)
Fixes https://github.com/SonarSource/sonar-dotnet/issues/6062
[NET-920]: https://sonarsource.atlassian.net/browse/NET-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NET-255]: https://sonarsource.atlassian.net/browse/NET-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NET-920 Modify rule S125: Add dotnet example

- rules/S6018/cfamily/rule.adoc
> S6018 Add example showing use of `inline` out of line (CPP-4342)

- rules/S1643/csharp/rule.adoc
> NET-934 Modify S1643: Use NetFx 4.8.1 in Brenchmark

- rules/S7019/docker/rule.adoc
[SONARIAC-1856](https://sonarsource.atlassian.net/browse/SONARIAC-1856)
[SONARIAC-1856]: https://sonarsource.atlassian.net/browse/SONARIAC-1856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARIAC-1856 Modify S7019: remove second example id/diff

- rules/S3649/java/metadata.json
- rules/S5332/java/metadata.json
- rules/S5332/kotlin/metadata.json
- rules/S5332/xml/metadata.json
- rules/S6293/metadata.json
[APPSEC-2374](https://sonarsource.atlassian.net/browse/APPSEC-2374)
[APPSEC-2374]: https://sonarsource.atlassian.net/browse/APPSEC-2374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Apply missing `android` tags to rules that support Android APIs (APPSEC-2374)

- rules/S3330/go/metadata.json
- rules/S3330/go/rule.adoc
> Modify rule S3330: Add Go language

- rules/S7177/java/rule.adoc
[SONARJAVA-5291](https://sonarsource.atlassian.net/browse/SONARJAVA-5291)
[SONARJAVA-5291]: https://sonarsource.atlassian.net/browse/SONARJAVA-5291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5291 Modify rule S7177: specify spring context

- rules/S6809/java/rule.adoc
[SONARJAVA-5295](https://sonarsource.atlassian.net/browse/SONARJAVA-5295)
[SONARJAVA-5295]: https://sonarsource.atlassian.net/browse/SONARJAVA-5295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5295 Modify rule S6809: add support for @Cacheable

- rules/S2260/go/metadata.json
[SONARGO-175](https://sonarsource.atlassian.net/browse/SONARGO-175)
[SONARGO-175]: https://sonarsource.atlassian.net/browse/SONARGO-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARGO-175 ParsingError should be disabled by default

- rspec-tools/rspec_tools/coverage.py
> [NO-JIRA] Point coverage script to the enterprise sonar-go repository

- rules/S4036/go/rule.adoc
> Modify rule S4036: Fix Code Example

- rspec-tools/rspec_tools/coverage.py
[SONARPY-2586](https://sonarsource.atlassian.net/browse/SONARPY-2586)
[SONARPY-2586]: https://sonarsource.atlassian.net/browse/SONARPY-2586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-2586 Point coverage script to the enterprise sonar-python repository

- rules/S3385/vbnet/rule.adoc
[NET-1118](https://sonarsource.atlassian.net/browse/NET-1118)
Part of NET-987
[NET-1118]: https://sonarsource.atlassian.net/browse/NET-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NET-1118 S3385: Remove Exit For, Do, While and Try

- rules/S1227/metadata.json
[CPP-6131](https://sonarsource.atlassian.net/browse/CPP-6131)
After checking with .NET, the rule can be deprecated for both languages
[CPP-6131]: https://sonarsource.atlassian.net/browse/CPP-6131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Deprecate rule S1227 (CPP-6131 and NET-1116)

- rules/S6418/php/rule.adoc
`description.adoc` is using `detections` and not `detectons` as a variable:
```
This rule detects {detections} having a name matching a list of words (secret, token, credential, auth, api[_.-]?key) being assigned a pseudorandom hard-coded value.
```
This PR makes the value rendered correctly on https://sonarsource.github.io/rspec/#/rspec/S6418/php
> S6418/php: fix typo in variable name

- rules/S6977/jcl/metadata.json
S6977 definitely impacts RELIABILITY, but it was typed as a `CODE_SMELL`.
However, if reliability is the main quality of an issue, then it should be paired with the `BUG` type.
S6977 is not a BUG in the sense that correctness is affected. At the same time, the previous MAINTAINABILITY quality is not impacted at all. Also, the issue does negatively affect performance, so it is bug in that sense.
Thus, the decision was made to change the type to `BUG`.
Finally, this change **is necessary to address `SONARJCL-184`.**
[SONARJCL-188]: https://sonarsource.atlassian.net/browse/SONARJCL-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S6977: Change type to BUG

- rules/S6945/jcl/metadata.json
S6945 does not necessarily indicate a bug since COND might not be set on purpose.
Hence, keeping the type as `CODE_SMELL` appears correct.
However, as a code smell, we need to qualify its `MAINTAINABILITY` impact.
At the same time, we keep the existing `RELIABILITY` impact:
Not setting COND is a practice that not only leads to harder to debug code but it may also lead to bugs
Following the documentation, MAINTAINABILITY issues should have at least HIGH impact, and Critical severity, if they can lead to the introduction of bugs.
RELIABILITY issues should have at least HIGH impact, and Critical severity, if they can for example cause corrupted data.
Both applies here. Hence, we upgrade the `defaultSeverity` and impact levels.
These are the documentation link: …
> Modify rule S6945: Add MAINTAINABILITY quality, increase severity and impact levels

- rules/S1289/cobol/rule.adoc
Companion PR for ticket [COBOL-1701](https://sonarsource.atlassian.net/browse/SONARCOBOL-1701): data items marked as `EXTERNAL` should not be reported as "unused data item".
> Modify rule S1289 (`COBOL.UnusedDataItem`): Ignore `EXTERNAL` data items

- rules/S4423/go/how-to-fix-it/stdlib.adoc
Reverts SonarSource/rspec#4726
> Modify rule S4423 for Go: Add examples for HTTP servers

- frontend/sonar-project.properties
This workaround should no longer be required, the initial bug in SCA analysis has been fixed.
This reverts commit 1012f37ffaf9774ad41f4826ea5854ae08893ec7.
> Revert "Fix frontend_tests job long running times (#4829)"

- rspec-tools/rspec_tools/coverage.py
- rspec-tools/tests/test_coverage.py
[JS-676](https://sonarsource.atlassian.net/browse/JS-676)
In https://github.com/SonarSource/rspec/pull/4731, the compatibleLanguages were introduced for js/ts rules. For backward compatibility for the coverage.py script from rspec, these need to mapped to the same key. This leads to a split brain, as the older rules would map to 'JAVASCRIPT' and 'TYPESCRIPT' and in master we have 'js' and 'ts'.
Let us update the mapping so that we are consistent. I really, really hope, this will be the last time we change these mappings. Twice should be enough 😄 
Ran locally the coverage.py script and checked the contents of the generated `covered_rules.json`
`pipenv run rspec-tools update-coverage --repository SonarJS --rulesdir ../rules`
The resulting file has only 2 keys for languages: 'js' and 'ts' …
> JS-676 Update mapping for js/ts files

- rspec-tools/Pipfile
- rspec-tools/Pipfile.lock
- rspec-tools/README.adoc
- rspec-tools/rspec_tools/checklinks.py
- rspec-tools/rspec_tools/utils.py
- rspec-tools/rspec_tools/validation/description.py
- rspec-tools/tests/conftest.py
- rspec-tools/tests/links/__init__.py
- rspec-tools/tests/links/test_links.py
- rspec-tools/tests/test_coverage.py
- rspec-tools/tests/validation/__init__.py
When I tried to run the tests locally, I encountered two issues:
- rspec-tools ignore `REQUESTS_CA_BUNDLE`, which makes them fail given that I have traffic inspection on my work laptop
- rspec-tools assume `master` to be the default branch, which is not the case in my config
This change fixes both problems, and addreses the bs4 deprecation warning.
> Refresh rspec-tools to fix tests when run locally

- .cirrus.yml
- rspec-tools/Pipfile
- rspec-tools/Pipfile.lock
- rspec-tools/README.adoc
- rspec-tools/rspec_tools/__init__.py
- rspec-tools/rspec_tools/checklinks.py
- rspec-tools/rspec_tools/cli.py
- rspec-tools/rspec_tools/coverage.py
- rspec-tools/rspec_tools/create_rule.py
- rspec-tools/rspec_tools/errors.py
- rspec-tools/rspec_tools/modify_rule.py
- rspec-tools/rspec_tools/notify_failure_on_slack.py
- rspec-tools/rspec_tools/repo.py
- rspec-tools/rspec_tools/rules.py
- rspec-tools/rspec_tools/utils.py
- rspec-tools/rspec_tools/validation/description.py
- rspec-tools/rspec_tools/validation/metadata.py
- rspec-tools/rspec_tools/validation/sanitize_asciidoc.py
- rspec-tools/tests/conftest.py
- rspec-tools/tests/links/test_links.py
- rspec-tools/tests/test_cli.py
- rspec-tools/tests/test_coverage.py
- rspec-tools/tests/test_create_rule.py
- rspec-tools/tests/test_modify_rule.py
- rspec-tools/tests/test_repo.py
- rspec-tools/tests/test_rules_repository.py
- rspec-tools/tests/test_utils.py
- rspec-tools/tests/validation/test_description_validation.py
- rspec-tools/tests/validation/test_metadata_validation.py
- rspec-tools/tox.ini
Add the default python codestyle tools: Black and usort and reformat code to enforce the consistent coding style.
The PR features massive changes due to batch reformatting. You can validate the changes by running the tools yourself:
```
cd rspec-tools
pipenv run black rspec_tools tests/
pipenv run usort format rspec_tools tests
```
Once merged, we should add .git-blame-ignore-revs file to exclude it from git blame.
> Batch-reformat rspec-tools to follow the python conventions and enforce code style in CI

- rules/S1313/abap/rule.adoc
- rules/S1313/apex/rule.adoc
- rules/S1313/cfamily/rule.adoc
- rules/S1313/csharp/rule.adoc
- rules/S1313/go/rule.adoc
- rules/S1313/java/rule.adoc
- rules/S1313/javascript/rule.adoc
- rules/S1313/kotlin/rule.adoc
- rules/S1313/php/rule.adoc
- rules/S1313/python/rule.adoc
- rules/S1313/ruby/rule.adoc
- rules/S1313/scala/rule.adoc
- rules/S1313/tsql/rule.adoc
- rules/S1313/vb6/rule.adoc
- rules/S1313/vbnet/rule.adoc
> Modify rule S1313: Fix link to HTTP page

- rules/S6363/kotlin/rule.adoc
[SONARJAVA-5476](https://sonarsource.atlassian.net/browse/SONARJAVA-5476)
[SONARJAVA-5476]: https://sonarsource.atlassian.net/browse/SONARJAVA-5476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5476 Modify rule S6363: Disable a url not meant to be a documentation link

- rules/S7203/secrets/rule.adoc
- shared_content/secrets/fix/store_separately.adoc
- shared_content/secrets/fix/store_separatly.adoc
- shared_content/secrets/impact/private_key_disclosure.adoc
[SONARTEXT-350](https://sonarsource.atlassian.net/browse/SONARTEXT-350)
[SONARTEXT-350]: https://sonarsource.atlassian.net/browse/SONARTEXT-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARTEXT-350 Modify rule S7203: Fix typos

- rules/S5977/java/rule.adoc
[SONARJAVA-5410](https://sonarsource.atlassian.net/browse/SONARJAVA-5410)
[SONARJAVA-5410]: https://sonarsource.atlassian.net/browse/SONARJAVA-5410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5410 Modify rule S5977: Improve Rationale for Avoiding Randomness in Tests

- rules/S6767/javascript/rule.adoc
[JS-72](https://sonarsource.atlassian.net/browse/JS-72)
[JS-72]: https://sonarsource.atlassian.net/browse/JS-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> JS-72 S6767: Update rspec with FP explanation

- rules/S1699/csharp/rule.adoc
[NET-1348](https://sonarsource.atlassian.net/browse/NET-1348)
Part of NET-1253
[NET-1348]: https://sonarsource.atlassian.net/browse/NET-1348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NET-1348 Modify S1699: Add How to fix it section

- rules/S1186/java/rule.adoc
[SONARJAVA-5437](https://sonarsource.atlassian.net/browse/SONARJAVA-5437)
[SONARJAVA-5437]: https://sonarsource.atlassian.net/browse/SONARJAVA-5437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-5437 Hint in S1186 to add comment to explain why the method is empty

- rules/S2384/java/rule.adoc
[SONARJAVA-4473](https://sonarsource.atlassian.net/browse/SONARJAVA-4473)
This goes in pair with PR: https://github.com/SonarSource/sonar-java/pull/5112
[SONARJAVA-4473]: https://sonarsource.atlassian.net/browse/SONARJAVA-4473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4473 Add exception on S2384 for private methods

- rules/S2230/java/rule.adoc
[SONARJAVA-4881](https://sonarsource.atlassian.net/browse/SONARJAVA-4881)
Their is an associated PR on sonar-java to change the behaviour of the rule: [#5094](https://github.com/SonarSource/sonar-java/pull/5094)
[SONARJAVA-4881]: https://sonarsource.atlassian.net/browse/SONARJAVA-4881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4881 Update S2230 to only target Spring <= 5

- rules/S6691/secrets/rule.adoc
- shared_content/secrets/examples.adoc
The non-compliant example of S6691 should truly be non-compliant
> Modify rule S6691: Use a truly non-compliant example

- rules/S2384/java/rule.adoc
[SONARJAVA-4473](https://sonarsource.atlassian.net/browse/SONARJAVA-4473)
[SONARJAVA-4473]: https://sonarsource.atlassian.net/browse/SONARJAVA-4473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARJAVA-4473 Update exception for S2384 to correspond to update in implementation

- docs/header_names/allowed_framework_names.adoc
- rules/S4830/dart/how-to-fix-it/dart-io-library.adoc
- rules/S4830/dart/metadata.json
- rules/S4830/dart/rule.adoc
[DART-247](https://sonarsource.atlassian.net/browse/DART-247)
[DART-247]: https://sonarsource.atlassian.net/browse/DART-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DART-247 Modify rule S4830: Add Dart language

- rules/S6291/metadata.json
- rules/S6300/metadata.json
[SONARKT-659](https://sonarsource.atlassian.net/browse/SONARKT-659)
[SONARKT-654]: https://sonarsource.atlassian.net/browse/SONARKT-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARJAVA-5544]: https://sonarsource.atlassian.net/browse/SONARJAVA-5544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARKT-657]: https://sonarsource.atlassian.net/browse/SONARKT-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARKT-659]: https://sonarsource.atlassian.net/browse/SONARKT-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARKT-659 Deprecate rule S6291 and S6300

- .github/workflows/dogfood.yml
- .github/workflows/main.yml
- .github/workflows/update_coverage.yml
* trigger of `update-coverage` run: https://github.com/SonarSource/rspec/actions/runs/15142120153
* trigger of `dogfood` octopus: https://github.com/SonarSource/rspec/actions/runs/15142249897
* deploy of `dogfood-automerge`: https://github.com/SonarSource/rspec/actions/runs/15142223258/job/42569016997
> Add dogfood approach to publish `update-coverage` to `dogfood-automerge` and then to `gh-pages`

- rules/S6362/dart/metadata.json
- rules/S6362/dart/rule.adoc
[DART-248](https://sonarsource.atlassian.net/browse/DART-248)
[DART-248]: https://sonarsource.atlassian.net/browse/DART-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DART-248 Modify rule S6362: Add Dart language

- rules/S5308/cfamily/rule.adoc
- rules/S6183/cfamily/rule.adoc
See the discussion on Slack:
https://sonarsource.slack.com/archives/CFTDKT6RW/p1748421280851259
Fixing this: ![image](https://github.com/user-attachments/assets/d677a8e9-1d88-4392-b994-4b2fceb9c6c9)
https://rules.sonarsource.com/cpp/RSPEC-6183/
https://rules.sonarsource.com/cpp/RSPEC-5308/
> Modify rules S5308,S6183: Fix section level

- rules/S1215/csharp/rule.adoc
[Implementation PR](https://github.com/SonarSource/sonar-dotnet-enterprise/pull/1042)
> Modify Rule S1215: Add reference to GC.GetTotalMemory

- docs/header_names/allowed_framework_names.adoc
- rules/S5131/java/how-to-fix-it/nanohttpd.adoc
- rules/S5131/java/rule.adoc
- rules/S5131/kotlin/how-to-fix-it/nanohttpd.adoc
- rules/S5131/kotlin/rule.adoc
[APPSEC-2480](https://sonarsource.atlassian.net/browse/APPSEC-2480)
[APPSEC-2480]: https://sonarsource.atlassian.net/browse/APPSEC-2480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Modify rule S5131: Add support for NanoHTTPD (APPSEC-2480)

- rules/S7630/githubactions/rule.adoc
- shared_content/githubactions/impact/information_disclosure.adoc
- shared_content/githubactions/impact/repository_manipulation.adoc
- shared_content/githubactions/impact/supply_chain_attacks.adoc
- shared_content/githubactions/impact/system_compromise.adoc
This PR moves the impacts from S7630 under github actions shared content as they will likely be useful for other rules, too.
Done as part of APPSEC-2536, wanted to have this separated as we might not use these for it, but the work was already done.
> Extract common github action impacts into shared content

- rules/S2053/go/rule.adoc
[SONARGO-468](https://sonarsource.atlassian.net/browse/SONARGO-468)
[SONARGO-468]: https://sonarsource.atlassian.net/browse/SONARGO-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARGO-468 Adapt S2053 rule description for Argon2

- rules/S6380/terraform/rule.adoc
- rules/S6382/terraform/rule.adoc
[APPSEC-2665](https://sonarsource.atlassian.net/browse/APPSEC-2665)
Part of APPSEC-2395
[APPSEC-2665]: https://sonarsource.atlassian.net/browse/APPSEC-2665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APPSEC-2665 S6380/S6382: Replace deprecated terraform azurerm_function_app references
